pymc-devs/pytensor

.github/ISSUE_TEMPLATE/feature-request.yml, README.rst
Same as in https://github.com/pymc-devs/pymc/pull/6329
Closes #11
=> Fix YAML syntax in issue template

pytensor/tensor/slinalg.py, tests/scalar/test_basic.py, tests/tensor/test_slinalg.py
Downstreaming https://github.com/aesara-devs/aesara/pull/1020
=> Add solve_discrete_lyapunov and solve_continuous_lyapunov

pytensor/link/jax/dispatch/scalar.py, pytensor/scalar/math.py
=> Harmonize softplus implementations

pytensor/compile/builders.py, pytensor/scan/op.py, tests/scan/test_basic.py
Downstreaming https://github.com/aesara-devs/aesara/pull/1306
=> Downstreaming 1306

.github/ISSUE_TEMPLATE/plain.yml
Hey all, was checking out the project and figured I'd see if there were small ways I could contribute a bit.
Put together a basic template to address issue #22. Unfortunately I'm not aware of a way to preview it, but the yaml structure seems straightforward enough that I hope this should suffice.
=> Add plain issue template

README.rst
**Thank you for opening a PR!**
+ [x] The commits correspond to [_relevant logical changes_](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes), and there are **no commits that fix changes introduced by other commits in the same branch/BR**.
+ [x] There …
=> Fix contributing broken link

pytensor/misc/ordered_set.py
Fix https://github.com/pymc-devs/pytensor/issues/72
+ [x] The commits correspond to [_relevant logical changes_](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes), and there are **no commits that fix changes introduced by other commits in the same …
=> add dict for ordered set

bin/upstream_pr.sh
Analog to https://github.com/pymc-devs/pytensor/pull/39 but the other direction.
=> Add script to upstream PRs.

pytensor/link/numba/dispatch/basic.py, tests/link/numba/test_basic.py
Make sure we don't access invalid memory for bad indices.
=> Add boundschecks in numba backend

.pre-commit-config.yaml, pytensor/link/numba/dispatch/__init__.py, pytensor/link/numba/dispatch/sparse.py, pytensor/scan/op.py, tests/link/numba/test_sparse.py
https://github.com/aesara-devs/aesara/pull/1336
=> Downstream 1336

pytensor/link/jax/dispatch/random.py, tests/link/jax/test_random.py
Downstreaming https://github.com/aesara-devs/aesara/pull/1345. PR port done by downstream_pr.sh script.
=> 🔄 From Aesara: 1345: "Splitting before using JAX key"

.github/workflows/nightly.yml, .github/workflows/pypi.yml, .github/workflows/test.yml, DESCRIPTION.rst, pyproject.toml
Trying to fix the release & PyPI upload.
Bundling GitHub Actions updates proposed by dependabot.
+ [x] Fill out the short …
=> Fix PyPI description and update GitHub Actions

.github/workflows/test.yml
This PR improves CI pipelines to address the issue #5 
It is a work-in-progress since I need to test several different configurations of github actions on Github hosted servers.
=> Improve CI pinelines

pytensor/scalar/math.py, pytensor/tensor/inplace.py
Towards #199 
Fix math typo (sigmoid)
+ [ ] Explain motivation and implementation 👆
+ [ ] The commits correspond to [_relevant logical changes_](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes). Note that if they don't, we will [rewrite/rebase/squash the git history](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#_rewriting_history) before merging.
+ [ ] Fill out the short summary sections 👇
None
None
None
fixes math typo in sigmoid. …
=> Fix math typo in sigmoid

doc/extending/creating_a_c_op.rst, doc/extending/creating_an_op.rst, doc/extending/scan.rst, doc/library/tensor/random/utils.rst, doc/scripts/docgen.py, doc/tutorial/shape_info.rst, pytensor/compile/function/types.py, pytensor/compile/profiling.py, pytensor/configdefaults.py, pytensor/graph/replace.py, pytensor/graph/rewriting/db.py, pytensor/link/numba/dispatch/elemwise_codegen.py, pytensor/link/numba/dispatch/scalar.py, pytensor/link/numba/dispatch/scan.py, pytensor/misc/ordered_set.py, pytensor/misc/pkl_utils.py, pytensor/scan/op.py, pytensor/tensor/basic.py, pytensor/tensor/rewriting/basic.py, pytensor/tensor/subtensor.py, tests/tensor/random/test_op.py, tests/tensor/rewriting/test_math.py, tests/tensor/rewriting/test_subtensor.py, tests/tensor/test_subtensor.py
I used [typos](https://github.com/crate-ci/typos) to spell-check code, docs and comments.
+ [x] Fill out the short summary …
=> Spell-check the repository

pytensor/link/jax/dispatch/tensor_basic.py, pytensor/tensor/basic.py, tests/link/jax/test_tensor_basic.py, tests/tensor/test_basic.py
=> Implement JAX dispatch for Split Op

pytensor/tensor/subtensor.py, tests/tensor/test_subtensor.py
=> Fix bug in gradient of `set_subtensor`

.github/release.yml
Eventually... we'll get there :D
=> Fix configuration bug in release.yml

pytensor/link/jax/dispatch/__init__.py, pytensor/link/jax/dispatch/sparse.py, tests/link/jax/test_sparse.py
=> Implement JAX dot with sparse constants

tests/tensor/test_math_scipy.py
=> Fix chained condition in test

pytensor/tensor/rewriting/jax.py
=> Fix bug in `boolean_indexing_set_or_inc`

tests/link/jax/test_tensor_basic.py
CI started failing in other PRs
=> Fix failing test due to change in JAX behavior

pytensor/tensor/rewriting/math.py
This is blocking: https://github.com/pymc-devs/pymc/pull/6830
=> Fix overly strict check in `local_pow_specialize` rewrite

pytensor/graph/rewriting/basic.py, tests/graph/rewriting/test_basic.py
This can avoid some infinite rewrite loops where a SpecifyShape is lifted, removed and then reintroduced at the bottom by the MergeOptimizer, as happened in https://github.com/pymc-labs/pymc-marketing/issues/332
We had seen this problem before in Aesara but had not addressed it at the root due to performance concerns. I think it's time now.
=> Retain more precise types in MergeOptimizer

pytensor/graph/replace.py, pytensor/tensor/blockwise.py, tests/graph/test_replace.py
@ferrine had suggested this, but I forgot to implement it!
=> Allow single variable output in vectorize

environment.yml, pyproject.toml
=> Pin numpy upper version

pytensor/tensor/nlinalg.py
Fixes failure in more recent versions of jaxlib
Closes #466
=> Use boolean `__props__` in `SVD` `Op`

pytensor/tensor/basic.py
Down-stream of https://github.com/aesara-devs/aesara/commit/49ae74ebdb1fc550a657e3bb47aa23ad239f0d12
=> Fix memory leak in TensorFromScalar

pyproject.toml
Closes https://github.com/pymc-devs/pytensor/issues/491
=> Unpin numpy in pyproject.toml

pytensor/link/jax/dispatch/scalar.py
=> Defer the use of nfunc_spec in JAX scalar dispatch

pytensor/graph/replace.py
=> Fix deprecation wrapper for vectorize_graph

pytensor/scan/rewriting.py, tests/scan/test_rewriting.py
=> Do not merge while scans with different until condition

pytensor/tensor/shape.py, tests/tensor/test_shape.py
=> Fix vectorized shape

.github/workflows/test.yml
May be useful to take a look one of these days
=> Show duration of slowest tests in CI

README.rst
=> Add background section of fork history

.github/workflows/test.yml, .pre-commit-config.yaml
I ran `pre-commit autoupdate` to update `.pre-commit-config.yaml`.
For an automatized solution, see my proposal in #599.
=> pre-commit autoupdate

tests/link/numba/test_scan.py
I couldn't reproduce locally, but the function was outputting insane values. Hopefully taming them will help. Magnitude of values is not relevant for the benchmark at all.
=> Tame test values on flaky test

.pre-commit-config.yaml
=> Disable pre-commit-ci autofix on PRs

.github/dependabot.yml
=> Add labels automatic in dependabot.yml

pyproject.toml
This will help with publishing a repodata patch for conda-forge as per <https://github.com/pymc-devs/pytensor/issues/688#issuecomment-2040160108>. This will no longer be necessary when we are finished with <https://github.com/pymc-devs/pytensor/pull/689>.
=> Pin Numpy version to <2

pytensor/__init__.py
```if_else``` now is accessible from root. Does it need tests?
=> Make `ifelse` accesible from root

pytensor/compile/compiledir.py, pytensor/compile/debugmode.py, pytensor/compile/function/__init__.py, pytensor/compile/function/pfunc.py, pytensor/compile/io.py, pytensor/gradient.py, pytensor/graph/basic.py, pytensor/graph/fg.py, pytensor/graph/rewriting/basic.py, pytensor/graph/rewriting/unify.py, pytensor/link/basic.py, pytensor/link/c/cmodule.py, pytensor/link/utils.py, pytensor/misc/may_share_memory.py, pytensor/printing.py, pytensor/scan/basic.py, pytensor/sparse/__init__.py, pytensor/sparse/type.py, pytensor/tensor/basic.py, pytensor/tensor/blas_headers.py, pytensor/tensor/math.py, pytensor/tensor/rewriting/basic.py, pytensor/tensor/rewriting/elemwise.py, pytensor/tensor/rewriting/math.py, pytensor/tensor/rewriting/subtensor.py, pytensor/tensor/shape.py, pytensor/tensor/subtensor.py, pytensor/utils.py, tests/sparse/test_basic.py, tests/tensor/rewriting/test_math.py
Just some trivial stuff like not doing instance checks in `node_rewriter`s that have `tracks` and not accessing the same attribute multiple times in a loop
=> Cleanup some code

pytensor/tensor/basic.py, tests/tensor/test_basic.py
Importantly, it now provides broadcastability information which is needed elsewhere
=> Add more specialized static output shape to Eye

pytensor/link/jax/dispatch/__init__.py, pytensor/link/jax/dispatch/sort.py, pytensor/link/jax/dispatch/tensor_basic.py, pytensor/tensor/sort.py, tests/link/jax/test_sort.py, tests/link/jax/test_tensor_basic.py, tests/tensor/test_sort.py
Also cleanup useless stuff from `tensor.sort` and add new `stable` kwarg for compat with numpy 2.0 signature.
=> Implement JAX dispatch for Argsort and add `stable` argument to sorting functions

pyproject.toml, pytensor/compile/debugmode.py, pytensor/compile/profiling.py, pytensor/graph/destroyhandler.py, pytensor/link/c/basic.py, pytensor/link/c/cmodule.py, pytensor/link/c/lazylinker_c.py, pytensor/link/vm.py, pytensor/scalar/basic.py, pytensor/scan/op.py, pytensor/scan/rewriting.py, pytensor/tensor/conv/abstract_conv.py, pytensor/tensor/subtensor.py, pytensor/utils.py, tests/misc/test_pkl_utils.py, tests/scan/test_basic.py, tests/sparse/test_basic.py, tests/tensor/test_math.py, tests/tensor/test_subtensor.py, tests/tensor/utils.py, tests/typed_list/test_type.py
These concern performance issues, and pathlib (the return).
=> Apply PERF and PTH rules from ruff

pyproject.toml, pytensor/graph/basic.py, pytensor/link/basic.py, pytensor/scalar/basic.py, pytensor/tensor/rewriting/linalg.py, pytensor/tensor/slinalg.py, scripts/mypy-failing.txt
=> Clear three files from mypy errors

MANIFEST.in, pyproject.toml
=> Remove versioneer.py from the manifest

README.rst
The README badge now shows if the latest tests on the main branch passed.
=> Only consider main branch in README test badge

environment.yml
Update `environment.yml` with a new package `sphinx-design` so that doc can be built locally. Package is already added in `doc/environment.yml`.
=> Include sphinx-design in environment.yml

tests/compile/test_builders.py
=> Fix test error message

pytensor/link/c/cmodule.py
This is a maintenance PR to help me debug Mac OS issues that other users are facing.
----
📚 Documentation preview 📚: https://pytensor--1053.org.readthedocs.build/en/1053/
=> Add extra logging information for cmodule

.github/workflows/mypy.yml, .github/workflows/pypi.yml, .github/workflows/rtd-link-preview.yml, .github/workflows/test.yml, .github/workflows/zizmor.yml
This should reduce the chance that we do something dangerous with GHA that might lead to a compromise of the repo.
Mirrors https://github.com/pymc-devs/pymc/pull/7624
----
📚 Documentation preview 📚: https://pytensor--1136.org.readthedocs.build/en/1136/
=> Audit GHA workflows with zizmor

.github/workflows/pypi.yml
----
📚 Documentation preview 📚: https://pytensor--1163.org.readthedocs.build/en/1163/
=> Update actions/attest-build-provenance to v2

.github/workflows/pypi.yml
Otherwise it fails with:
```
Error: Failed to get ID token: Error message: Unable to get ACTIONS_ID_TOKEN_REQUEST_URL env variable
```
----
📚 Documentation preview 📚: https://pytensor--1168.org.readthedocs.build/en/1168/
=> Fix attestations

.github/workflows/pypi.yml
Updates all wheel builder platforms to their github latest version
----
📚 Documentation preview 📚: https://pytensor--1171.org.readthedocs.build/en/1171/
=> Use latest platforms to build wheels

doc/tutorial/prng.rst
=> Small tweaks the prng doc

pytensor/configdefaults.py
For more context, see the discussion in:
https://github.com/conda-forge/pytensor-suite-feedstock/pull/133#issuecomment-2673831166
----
📚 Documentation preview 📚: https://pytensor--1238.org.readthedocs.build/en/1238/
=> Fix warning message since m2w64-toolchain is no longer installable

environment-osx-arm64.yml
Backwards 
----
📚 Documentation preview 📚: https://pytensor--1349.org.readthedocs.build/en/1349/
=> correct comparison in env yaml

pytensor/d3viz/html/template.html
This was missing from pytensor
https://github.com/pymc-devs/pytensor/tree/main/pytensor/d3viz
Took from aesara
https://github.com/aesara-devs/aesara/tree/main/aesara/d3viz
Looks to be caused from the gitignore here: 
https://github.com/pymc-devs/pytensor/blob/a7610765df0a0da5b1075ab98c212f5e365bb0a5/.gitignore?plain=1#L36
----
📚 Documentation preview 📚: https://pytensor--1380.org.readthedocs.build/en/1380/
=> Restore d3viz/html/template.html
