pymc-devs/pytensor

.github/release.yml, README.rst
Closes #26.
This PR adds the capability of autogenerating release notes akin to the [one PyMC has](https://github.com/pymc-devs/pymc/blob/main/.github/release.yml). The first commit fixes some minor link display issue in the README.
+ [x] The commits correspond to [_relevant logical …
=> Allow autogeneration of release notes

pytensor/link/numba/dispatch/scan.py, tests/link/numba/test_scan.py
Partially solves #20 for the NUMBA backend. I did not change or test JAX because that's currently completely broken.
=> Optimize Scan inner graph when compiling to Numba

pytensor/compile/profiling.py, pytensor/gradient.py, pytensor/graph/features.py, pytensor/graph/fg.py, pytensor/graph/rewriting/basic.py, pytensor/link/c/cmodule.py, pytensor/link/vm.py, pytensor/misc/check_blas.py, pytensor/misc/elemwise_time_test.py, pytensor/misc/latence_gpu_transfert.py, pytensor/scan/op.py, pytensor/tensor/blas.py, pytensor/tensor/rewriting/elemwise.py, tests/link/test_vm.py, tests/sandbox/test_rng_mrg.py, tests/sparse/sandbox/test_sp.py, tests/sparse/test_basic.py, tests/tensor/nnet/speed_test_conv.py, tests/tensor/nnet/test_conv.py, tests/tensor/nnet/test_conv3d2d.py, tests/tensor/rewriting/test_math.py, tests/tensor/test_gc.py
https://github.com/aesara-devs/aesara/pull/1312
=> Downstream 1312

pytensor/graph/basic.py
Fixes #64 
- renamed `f_node` to `f_apply`
- corrected doc string
- verified all the related tests
+ [x] The commits correspond to [_relevant logical changes_](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes), and there are **no commits that fix changes …
=> Fix argument name

pytensor/link/numba/dispatch/basic.py
Numba is deprecating `generated_jit` in favor of `overload`.
=> Stop using deprecated generated_jit

pytensor/configdefaults.py, pytensor/link/numba/dispatch/basic.py, pytensor/link/numba/dispatch/cython_support.py, pytensor/link/numba/dispatch/elemwise.py, pytensor/link/numba/dispatch/extra_ops.py, pytensor/link/numba/dispatch/nlinalg.py, pytensor/link/numba/dispatch/scalar.py, pytensor/sparse/sandbox/sp.py, pytensor/tensor/nnet/corr.py, tests/link/numba/test_basic.py, tests/link/numba/test_cython_support.py, tests/link/numba/test_elemwise.py, tests/link/numba/test_extra_ops.py, tests/link/numba/test_nlinalg.py
- implementations for numba special functions
- numba impl fix for cumop
- Fix for numba svd
- Preserve names in graph replacements
- Remove broken AdvancdIndexing numba op
- Deal with negative axis args
- numba impl for checkandraise
=> Some numba backend fixes

pytensor/tensor/elemwise.py, pytensor/tensor/random/basic.py, pytensor/tensor/random/op.py, pytensor/tensor/random/rewriting.py, pytensor/tensor/random/utils.py, tests/tensor/random/test_basic.py, tests/tensor/random/test_op.py, tests/tensor/random/test_rewriting.py, tests/tensor/test_basic.py
This PR improves a couple of edge issues related to RandomVariable static shape inference, and simplifies and extends the `local_dimshuffle_rv_lift rewrite`. 
Allowing the rewrite to apply in more cases increases the range of graphs we can infer the logprob in PyMC: https://github.com/pymc-devs/pymc/blob/a0d6ba079eac2f044ed40cc5747f1079d99f9f16/pymc/logprob/tensor.py#L288-L290
Closes #60 and makes progress related to #49
=> Misc RandomVariable improvements

pytensor/__init__.py, pytensor/compile/builders.py, pytensor/graph/__init__.py, pytensor/graph/basic.py, pytensor/graph/replace.py, pytensor/ifelse.py, pytensor/scan/basic.py, pytensor/scan/op.py, pytensor/scan/rewriting.py, pytensor/scan/utils.py, tests/graph/test_basic.py, tests/graph/test_replace.py, tests/graph/utils.py, tests/scan/test_rewriting.py
Implementing graph replace that preserves references from the inherited graph (https://github.com/pymc-devs/pytensor/issues/19)
+ [x] The commits correspond to [_relevant logical changes_](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes), and there are …
=> Graph replace

pytensor/tensor/shape.py
Downstreaming https://github.com/aesara-devs/aesara/pull/1313. PR port done by downstream_pr.sh script.
=> Add type hint None to specify_shape

pytensor/link/numba/dispatch/elemwise.py
Compile time for DimShuffle ops is pretty long:
```python
import numba
z = pt.dscalar("z")
out = z[None, None]
z_val = np.array(0.1)
%%time
func = pytensor.function([z], out, mode="NUMBA")
func(z_val)
CPU times: user 1.6 s, sys: 23.5 ms, total: 1.62 s
Wall time: 1.62 s
CPU times: user 661 ms, sys: 36.1 ms, total: 697 ms
Wall time: 697 ms
```
Still ways to go, and unfortunately it doesn't seem to have as big an impact on the compile times for larger models as I hoped, but it is a start...
Going forward I think we should try to find more ops like this, where individually the compile time is large, and try some other things:
- Do we really need to ask for O3 optimization all the time? I guess O2 might be enough for most cases
- …
=> Improve numba DimShuffle compile time

tests/graph/test_fg.py
Function graph tests did not have clear error messages to check
Added `match=...` to existing `pytest.raises`
+ [x] Fill out …
=> Match error message in function graph tests

.github/PULL_REQUEST_TEMPLATE.md, .github/release.yml, bin/downstream_pr.sh
Towards #115 
Sister PR in https://github.com/pymc-devs/pymc/pull/6392
=> Update Release Notes template

pytensor/link/jax/dispatch/scalar.py, tests/link/jax/test_scalar.py
Spinoff from #121 
- Fix JAX dispatch for multi-output Composite
=> Fix JAX dispatch for multi-output Composite

pytensor/sparse/basic.py, pytensor/sparse/rewriting.py, pytensor/tensor/basic.py, pytensor/tensor/blas.py, pytensor/tensor/io.py, pytensor/tensor/math.py, pytensor/tensor/shape.py, pytensor/tensor/type.py, tests/graph/test_basic.py, tests/link/numba/test_elemwise.py, tests/link/numba/test_random.py, tests/scan/test_printing.py, tests/tensor/random/test_basic.py, tests/tensor/random/test_op.py, tests/tensor/random/test_utils.py, tests/tensor/rewriting/test_basic.py, tests/tensor/rewriting/test_elemwise.py, tests/tensor/rewriting/test_math.py, tests/tensor/rewriting/test_shape.py, tests/tensor/rewriting/test_subtensor.py, tests/tensor/test_basic.py, tests/tensor/test_elemwise.py, tests/tensor/test_extra_ops.py, tests/tensor/test_shape.py, tests/tensor/test_type.py, tests/test_ifelse.py
Closes #61
- `pytensor.tensor.tensor` now accepts name as the only positional argument. All other arguments must be provided via keyword
- Tensor creator helpers now accept static input shapes (e.g., `pt.matrix(shape=(10, None))`)
=> Allow passing static shape to tensor creation helpers

tests/link/jax/test_basic.py
Tests started failing with JAX 0.4.1 in #121
=> Make tests compatible with newer version of JAX

pytensor/link/jax/dispatch/random.py, tests/link/jax/test_random.py
Downstreaming https://github.com/aesara-devs/aesara/pull/1362. PR port done by downstream_pr.sh script.
=> 🔄 From Aesara: 1362: "Add `HalfNormalRV` JAX implementation"

.github/workflows/test.yml, environment.yml, pyproject.toml, tests/link/jax/test_elemwise.py, tests/link/numba/test_basic.py, tests/link/numba/test_scan.py, tests/link/numba/test_tensor_basic.py, tests/scan/test_basic.py, tests/scan/test_rewriting.py
https://github.com/aesara-devs/aesara/pull/1347
https://github.com/aesara-devs/aesara/pull/1365
=> 🔄 From Aesara: #1347 and # 1365: " Add CI support for benchmarking"

pytensor/link/numba/dispatch/basic.py, pytensor/link/numba/dispatch/scalar.py, tests/link/numba/test_basic.py
This allows numba to reuse previous typing and compilation
results if the same function is reused, which then also
leads to smaller llvm modules.
For the tests to continue to work we have to return
those global functions through a wrapper (`basic.global_numba_func`)
so that the tests are still able to disable compilation.
Also remove some inline="always" arguments that don't seem
to be helpful.
=> Remove some inline arguments and make some njit functions global

pytensor/tensor/math.py
from `(1 / (1 + exp(x))` to `(1 / (1 + exp(-x))`
...
...
+ [ ] Explain motivation and implementation 👆
+ [ ] The commits correspond to [_relevant logical changes_](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes). Note that if they don't, we will [rewrite/rebase/squash the git history](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#_rewriting_history) before merging.
+ [ ] Fill out the short summary sections 👇
- ...
- ...
- ...
- ... …
=> fix: logit sigmoid function typo

.github/release.yml
Oops... would be nice if github would error when labels don't exist
=> Fix automatic release notes label reference

doc/conf.py, doc/environment.yml, environment.yml, pyproject.toml, pytensor/tensor/basic.py, pytensor/tensor/rewriting/subtensor.py, tests/tensor/test_basic.py
Making static shapes propagate through `Join`s such as `pt.concatenate`.
Closes #163
The previous double-`for` implementation was rather tricky to refactor, which is why I went with a simple matrix-based approach.
The first commit makes the corresponding tests and their output easier to read.
+ [x] The commits correspond to [_relevant logical changes_](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes). Note that if they don't, we will …
=> Compute static shape types in outputs of `Join`

pytensor/scalar/math.py, pytensor/tensor/inplace.py, pytensor/tensor/math.py, pytensor/tensor/special.py, tests/tensor/test_math_scipy.py, tests/tensor/test_special.py
This PR is a continuation of https://github.com/pymc-devs/pytensor/pull/87 in a new fork and adds `Op`s  for the Gaussian Hypergeometric Function, Pochhammer Symbol, and Factorials as `hyp2f1`, `poch`, and `factorial`, respectively.
`hyp2f1` involves an infinite summation and uses a `scipy` implementation for this reason, but once `scan` is performant enough to assume this task, `hyp2f1` can be rewritten in terms of `poch` and `factorial` in a future PR.
The only test failing is `test_grad` for `hyp2f1`. It seems to be a data type issue:
```
TypeError: ('float() argument must be a string or a number, not \'ScalarVariable\'\n
Apply node that caused the error: Elemwise{hyp2f1_der}(input 0, input 1, input 2, input 3, TensorConstant{(1, 1) of 0.0})\n
Toposort index: 0\nInputs types: …
```
=> Add Ops for Gaussian Hypergeometric Function, Pochhammer Symbol, and Factorials

pytensor/tensor/extra_ops.py, tests/tensor/test_extra_ops.py
=> Handle invalid BroadcastTo shape in C backend

pytensor/link/jax/dispatch/nlinalg.py, pytensor/link/numba/dispatch/nlinalg.py, pytensor/tensor/nlinalg.py, tests/link/jax/test_nlinalg.py, tests/link/numba/test_nlinalg.py, tests/tensor/test_nlinalg.py
This PR relates to #161 and adds `slogdet` [numpy method](https://numpy.org/doc/stable/reference/generated/numpy.linalg.slogdet.html) for Numba. Please share your feedback! 🙂
=> Add `slogdet` for Numba and JAX

tests/link/jax/test_elemwise.py, tests/link/numba/test_elemwise.py
There is quite some variability left, so I am not sure this suffices. 
I've also seen other benchmark tests "fail", so maybe we just need live with it, or increase the cutoff value.
=> Seed logsumexp benchmark tests

.github/workflows/test.yml
This is in hopes of resolving sporadic errors.
Ref: <https://github.com/conda-incubator/setup-miniconda/issues/274>
...
...
+ [ ] Explain motivation and implementation 👆
+ [ ] The commits correspond to [_relevant logical changes_](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes). Note that if they don't, we will [rewrite/rebase/squash the git history](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#_rewriting_history) before merging. …
=> Adjust setup-miniconda parameters

.github/workflows/test.yml, pytensor/link/jax/dispatch/extra_ops.py, pytensor/link/jax/dispatch/random.py, pytensor/tensor/random/rewriting/jax.py, tests/link/jax/test_random.py
This PR extends the number of RandomVariables supported in the JAX backend, with two strategies:
1. Rewrites that convert RVS to equivalent expressions that use RVs supported natively by JAX
2. Optional dependency on NumPyro routines for more complex expressions
The rewrites from 1. may be reused with other backends later (e.g, Numba). This seems like a cleaner solution than implementing the same logic in the different dispatched functions of each backend.
=> Extend support of RandomVariables in JAX backend

pytensor/tensor/basic.py, tests/tensor/test_basic.py
Seeking to address #193, making type hints for `pt.stack` more accurate.
I chose to type hint as TensorLike, defined [here](https://github.com/pymc-devs/pytensor/blob/main/pytensor/tensor/__init__.py#L14) as Variable | Sequence[Variable] | npt.ArrayLike. I hope this will address all cases that mypy was complaining about. I also updated the docs and errors accordingly.
Lastly, because there was a case that coerces a list of zero-dim Variables into MakeVector, I also allowed a parallel case of zero-dim numpy arrays to use MakeVector rather than Join and updated a test to cover this case.
+ ^Yes although I had to update …
=> Fix `pt.stack` type hints

pytensor/tensor/rewriting/math.py, tests/tensor/rewriting/test_math.py
Hi,
Could someone please check whether I'm on the right track with this attempt to solve https://github.com/pymc-devs/pytensor/issues/54
This commit adds rewrites for e^x * e^y as e^(x+y) and e^x / e^y as e^(x-y). If you confirm that this is more or less the appropriate way, I'm happy to continue with power(base, x) * power(base, y) => power(base, x + y)
Apart from the general request for comments, I have a specific question too: I don't yet really understand how exactly the added decorators (@register_canonicalize and @register_specialize) change behaviour. I'd naively presume this particular node rewriter should be a genuine specializer, not sure about the canonicalize part though. Is there any document somewhere that explains this? Unfortunately, I haven't come across anything related …
=> Rewrite products of exponents as exponent of sum

pytensor/tensor/math.py, tests/tensor/test_math.py
`MaxAndArgmax` propagates broadcastable flags but not static shape information. Now we have full shape info. Connected to #203 
```python
>>> x = pt.max_and_argmax([[1,2,3],[4,5,6]],axis=1)
>>> x[0].type.shape, x[1].type.shape 
((2), (2,))
```
I've updated the test suite to test this in a number of places. I'd appreciate close eyes on this to make sure I did the tests right.
I also `parametrized` a few of the updated tests to help me identify a few cases that were failing. Currently I've left them that way since I figure that less monolithic tests are preferable.
+ [x] Link relevant issues, preferably in [nice commit …
=> Propagate static shape in MaxAndArgmax

.github/workflows/test.yml, .pre-commit-config.yaml, pyproject.toml, pytensor/link/numba/dispatch/elemwise_codegen.py
In addition:
* Make annotations compatible with oldest supported Python version (mypy was failing on Python 3.8)
* Test pre-commit in all supported versions
* Updated isort dependency
Closes #76
=> Drop support for Python 3.7

.github/workflows/test.yml
The CI currently always stops after the first test failure. This makes it very awkward to debug issues that only appear in the CI online, but not locally.
I think the reason for canceling the tests is that it might reduce CI usage, I'm not really sure this actually is the case if that just means that we need more CI runs...
=> Don't cancel tests in CI early

.pre-commit-config.yaml, pytensor/compile/mode.py, pytensor/gradient.py, pytensor/graph/fg.py, pytensor/graph/op.py, pytensor/graph/rewriting/basic.py, pytensor/link/c/cmodule.py, pytensor/link/numba/dispatch/elemwise_codegen.py, pytensor/printing.py, pytensor/sparse/type.py, pytensor/tensor/random/rewriting/basic.py, pytensor/tensor/random/utils.py, pytensor/tensor/slinalg.py, pytensor/tensor/type.py, tests/link/numba/test_scan.py
Allows to keep up with python versions.
...
+ [x] Fill out the short summary sections 👇
- ...
- ...
- ...
- ...
- Add …
=> Add pyupgrade to pre-commit and apply it

pytensor/sparse/basic.py
Scipy versions after 1.8 deprecated a bunch of namespaces in order to clarify the intended public namespaces: https://docs.scipy.org/doc/scipy/release.1.8.0.html
Turns out that the annotation on `sparse.basic.as_symbolic_sparse` accesses a "private" scipy namespace, so importing pytensor when a newer scipy is installed will yield the following warning.
```python
>>> import scipy, warnings
>>> scipy.__version__
'1.10.0'
>>> warnings.resetwarnings()
>>> import pytensor
/home/cove/pytensor/pytensor/sparse/basic.py:132: DeprecationWarning: Please use `spmatrix` from the `scipy.sparse` namespace, the `scipy.sparse.base` namespace is deprecated.
@_as_symbolic.register(scipy.sparse.base.spmatrix)
```
Not a big deal (and `numba-scipy` currently requires `scipy<=1.7.3`), but newer scipy happened …
=> Fix DeprecationWarning from scipy.sparse.base

pytensor/tensor/rewriting/elemwise.py, tests/tensor/rewriting/test_elemwise.py
Showed up in https://github.com/pymc-devs/pymc/pull/6531
=> Fix spurious warning from FusionOptimizer

pytensor/scan/op.py, pytensor/scan/rewriting.py, pytensor/tensor/rewriting/subtensor.py, pytensor/tensor/subtensor.py, tests/scan/test_rewriting.py
=> Optimize while scans when only last state is needed

doc/library/sparse/index.rst, doc/library/tensor/basic.rst, pytensor/compile/profiling.py, pytensor/scalar/basic.py, pytensor/sparse/basic.py, pytensor/tensor/inplace.py, pytensor/tensor/math.py, pytensor/tensor/rewriting/math.py, pytensor/tensor/subtensor.py, tests/sparse/test_basic.py, tests/tensor/rewriting/test_math.py, tests/tensor/test_inplace.py, tests/tensor/test_math.py
fixes #162
- Rename sgn with sign
- Deprecated sgn
=> Rename `sgn` with `sign`

pytensor/scan/rewriting.py, tests/scan/test_rewriting.py
This would be triggered when the initial state was something like `pt.zeros(2)`, but not `pt.arange(2)`
=> Fix scan save memory rewrite bug

pytensor/misc/safe_asarray.py
Led to #198 failing
Closes #146
=> Fix numpy DeprecationWarning when converting integers to PyTensor Constants

.github/workflows/test.yml, pyproject.toml
~~Depends on next Numba release for support of Python 3.11: https://github.com/numba/numba/issues/8304~~
Not testing Numba on Python 3.11 for now
The last two commits of this PR should be removed once:
1. Numba supports Python 3.11
2. The mypy issue mentioned below is sorted out
***
1. Don't run both fast-compile and float32 to reduce a big chunk of the tests combinations. Both modes are arguably very specialized on their own, and if we need tests to check their interaction we should add them explicitly. In general, the biggest issue with float32 is some Ops that would upcast stuff to float64. Fast-compile has less optimizations / introduces less specialized Ops, so this should be less of a concern for maintaining float32.
2. Exclude fast-compile/float32 from the oldest supported Python …
=> Add explicit support for Python 3.11

tests/link/jax/test_scalar.py
JAX behavior at the boundary changed and no longer returns `inf` like scipy does, in version 0.4.6
Fixed test by evaluating at a non-boundary value.
Closes #241
=> Fix JAX erfinv failing test

pytensor/link/numba/dispatch/elemwise.py, tests/link/numba/test_elemwise.py
`np.reshape(x, some_shape)` fails in numba if x is not contiguous. This can lead to compilation failures. We can work around this by converting to a contiguous array if it is not already the case. This is happening in code in dim_shuffle where the output shape is `()`, so a valid input array will always be contiguous, but numba doesn't seem to realize this.
Fixes https://github.com/pymc-devs/nutpie/issues/40.
+ [x] The commits correspond to [_relevant logical …
=> Fix non-contiguous reshapes in numba backend

pytensor/tensor/random/basic.py
Closes #204 
Renamed the RV names in `_print_name` to their long versions.
+ [x] Are the changes covered by tests and docstrings? No
+ [x] Fill out the short summary sections 👇
- …
=> Refactored RV `_print_name` to long names

pytensor/link/numba/dispatch/basic.py, pytensor/link/numba/dispatch/sparse.py, pytensor/link/numba/linker.py, tests/link/numba/test_basic.py, tests/link/numba/test_sparse.py
Downstream https://github.com/aesara-devs/aesara/pull/1337
=> :arrows_counterclockwise: From Aesara: 1337:  Add basic overloads for Numba sparse types

pytensor/graph/basic.py, tests/graph/test_basic.py
Closes #227 
I have implemented a function that converts the dictionary with string keys to pytensor. The pytensor variable for the corresponding name is found using the function "get_var_by_name".
+ [x] The commits correspond to [_relevant logical changes_](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes). Note that if they don't, we will [rewrite/rebase/squash the git history](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#_rewriting_history …
=> Allow string keys in `eval` utility

doc/library/tensor/basic.rst, pytensor/__init__.py, pytensor/gradient.py, pytensor/link/jax/dispatch/tensor_basic.py, pytensor/scan/basic.py, pytensor/scan/rewriting.py, pytensor/tensor/basic.py, pytensor/tensor/blas.py, pytensor/tensor/conv/abstract_conv.py, pytensor/tensor/elemwise.py, pytensor/tensor/exceptions.py, pytensor/tensor/extra_ops.py, pytensor/tensor/random/op.py, pytensor/tensor/rewriting/basic.py, pytensor/tensor/rewriting/elemwise.py, pytensor/tensor/rewriting/math.py, pytensor/tensor/rewriting/shape.py, pytensor/tensor/rewriting/subtensor.py, pytensor/tensor/shape.py, pytensor/tensor/subtensor.py, pytensor/tensor/var.py, tests/sparse/test_basic.py, tests/tensor/test_basic.py, tests/tensor/test_elemwise.py, tests/tensor/test_math.py
Closes #226 
- Added a `get_scalar_constant()` method that raises NotScalarConstantError when non-scalar outputs are passed.
- Renamed the current `get_scalar_constant_value()` to `get_underlying_scalar_constant()`
+ [x] The commits correspond to [_relevant logical changes_](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes). Note that if they don't, we will [rewrite/rebase/squash the git history](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#_ …
=> `get_scalar_constant_value` now raises for non-scalar inputs

pytensor/scalar/basic.py, pytensor/tensor/sharedvar.py, tests/tensor/test_basic.py, tests/tensor/test_sharedvar.py
Closes #258 
Feature request issue #259
=> Raise NotImplementedError when trying to convert MaskedArrays

doc/extending/graph_rewriting.rst
There's a very minor incorrect mention of `SequenceDB` instead of `EquilibriumDB` in the Graph Rewriting Doc.
+ [ ] The commits correspond to [_relevant logical changes_](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes). Note that if they don't, we will [rewrite/rebase/squash the git history](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#_rewriting_history) before merging.
+ [ ] Fill out …
=> Fix a typo in Graph Rewriting Doc

.pre-commit-config.yaml, pytensor/link/c/exceptions.py
In combination wtih https://github.com/python/typeshed/pull/10057, closes #240.
Fix failing CI
Update deprecated import
+ [X] Explain motivation and implementation 👆
+ [X] Make sure that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html).
+ [X] Link relevant issues, preferably in [nice commit messages](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html).
+ [X] The commits correspond to [_relevant logical changes_](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes). Note that if they don't, we will [rewrite/rebase/squash the git history](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#_rewriting_history) before merging.
+ [ …
=> Import CompileError from setuptools not distutils

pytensor/tensor/rewriting/math.py, tests/tensor/rewriting/test_math.py
Modified downstream of https://github.com/aesara-devs/aesara/pull/1399
=> Add stabilization rewrite for `log_diff_exp`

pytensor/link/numba/dispatch/scan.py, tests/link/numba/test_scan.py
Related to #233 
In talks with @jessegrabowski and @aseyboldt we found out that there is a large overhead of `asarray` when indexing vector inputs to create taps, as these become non-array numerical variables that must be wrapped again into a scalar tensor (at least until we allow proper scalar inputs in Scan).
The new benchmark test runs 2.5x faster on my machine compared to main. 
The scan function used to look like this
```python
def scan(n_steps, outer_in_1, outer_in_2, outer_in_3, outer_in_4):
outer_in_3_len = outer_in_3.shape[0]
outer_in_3_mitsot_storage = outer_in_3
outer_in_4_len = outer_in_4.shape[0]
outer_in_4_sitsot_storage = outer_in_4
i = 0
cond = np.array(False)
while i < n_steps and not cond.item():
(inner_out_0, inner_out_1) = scan_inner_func(np.asarray(outer_in_1[i]), …
```
=> Speedup Numba Scans with vector inputs

pytensor/link/jax/dispatch/scan.py, tests/link/jax/test_scan.py
Closes #287 Currently, JAX compilation of scans with n-dimensional outputs fails.
Checks input and output dimensions, and adds a batch dimension to initial inputs where necessary.
Marked as draft because there are still some problems:
1. Currently, just check if output.ndim > 1 and insert a single dimension to the initial input if so. I think this is the only case possible given the shape checking that is done by `scan` itself. Since all outputs must be 1 dimension smaller than the inputs, I don't think it's possible to reach a case where more than 1 batch dimension needs to be inserted. Nevertheless, the machinery to do this exists in this code if necessary.
2. Big problem: nd sequences and mit_sots do not work. This is captured by two tests in this PR:  `test_nd_scan_mit_sot` and …
=> Fix JAX Scan for output ndim > 1

pytensor/link/jax/dispatch/nlinalg.py, tests/link/jax/test_nlinalg.py
Add a jax implementation of `pt.linalg.pinv`
Not the most elaborate PR:
```
@jax_funcify.register(MatrixPinv)
def jax_funcify_Pinv(op, **kwargs):
def pinv(x):
return jnp.linalg.pinv(x)
return pinv
```
+ [ x] Explain motivation and implementation 👆
+ [ x] Make sure that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html).
+ [x ] The commits correspond to [_relevant logical changes_](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes). Note that if they don't, we will [rewrite/rebase/squash the git history](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#_rewriting_h …
=> Add jax implementation of `pt.linalg.pinv`

pytensor/link/jax/dispatch/nlinalg.py, tests/link/jax/test_nlinalg.py
My fault, I missed the failing test in #294
I went ahead and also added support for the `hermitian` flag
=> Fix pinv jax test and support hermitian flag

.github/workflows/test.yml
The benchmark CI seems too flaky to be used as a required condition.
We will leave it to the reviewers to assess the need to investigate individual cases where it fails.
=> Don't fail on benchmark alert

pytensor/graph/basic.py, pytensor/scalar/basic.py, pytensor/scalar/loop.py, pytensor/scalar/math.py, pytensor/tensor/elemwise.py, pytensor/tensor/rewriting/elemwise.py, tests/scalar/test_loop.py, tests/scalar/test_math.py, tests/tensor/test_math_scipy.py
Used in the derivatives of `betainc`, `gammainc`, `gammaincc` and `hyp2f1`. 
It should be considerably faster than the old numpy loops, and easier to dispatch to numba and jax as well.
Alternative to #174 
Closes #83 
This is the kind of C code that is generated for the gammaincc gradient inner loop:
<details>
<summary>Toggle C code</summary>
```c
{
bool until = 1;
// Set carried inputs to initial state variables
// Expressions in the loop will depend on these ones
npy_float64 V41_i_copy0 = V41_i;
npy_float64 V41_i_copy1 = V41_i;
npy_float64 V41_i_copy2 = V41_i;
npy_float64 V43_i_copy3 = V43_i;
npy_float64 V43_i_copy4 = V43_i;
npy_float64 V43_i_copy5 = V43_i;
npy_int8 V39_i_copy6 = V39_i;
npy_int8 V39_i_copy7 = V39_i;
npy_int8 V39_i_copy8 = V39_i;
npy_float64 V41_i_copy9 = V41_i;
npy_int8 …
```
=> Implement scalar loop for iterative gradients

pytensor/link/jax/dispatch/tensor_basic.py, tests/link/jax/test_tensor_basic.py
`pm.LJKCholesky` users `pt.tri` to unpack the cholesky decomposed covariance matrix, so this PR adds support for the underlying `Tri` `Op`.
The only wrinkle is the requirement for static shape args -- `jnp.tri` is exactly the same as `jnp.arange` in this respect. So I copied the code from the `pt.arange` jax implementation.
+ [ ] Explain motivation and implementation 👆
+ [ ] The commits correspond to [_relevant logical changes_](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes). Note that if they …
=> Add JAX support for `pt.tri`

pytensor/compile/mode.py, pytensor/misc/elemwise_openmp_speedup.py, pytensor/misc/elemwise_time_test.py, pytensor/scalar/loop.py, pytensor/scalar/math.py, pytensor/tensor/elemwise.py, pytensor/tensor/rewriting/elemwise.py, tests/scalar/test_loop.py, tests/tensor/test_math_scipy.py
* Recompile Elemwise when `openmp_elemwise_minsize` changes (otherwise it won't have an effect)
* Remove warnings and errors from ScalarLoop (OpenMP fails if any are raised)
=> Some OpenMP tweaks

MANIFEST.in
Fixes #309 by including missing *.cc and *.hh files in the packages.
+ [X] Explain motivation and implementation 👆
+ [X] Make sure that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html).
+ [X] Link relevant issues, preferably in [nice commit messages](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html).
+ [X] The commits correspond to [_relevant logical changes_](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes). Note that if they don't, we will [rewrite/rebase/squash the git history](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#_rewriting_history) before merging.
+ [ ] Fill out the short summary sections 👇
- ...
- ... …
=> Include missing Faddeeva files

.github/workflows/test.yml, environment.yml, pytensor/link/numba/dispatch/random.py, setup.py, tests/link/numba/test_basic.py, tests/link/numba/test_extra_ops.py
This reverts commit 277559b411886c3dc1161cf197c5f250048ecec5 and  tests numba compatibility with py311
Closes #239
=> Revert "Run numba tests in python 3.10 instead of 3.11"

pytensor/link/jax/dispatch/random.py, pytensor/link/jax/linker.py, tests/link/jax/test_random.py
=> Fix bug in JAX cloning of RNG shared variables

pytensor/scalar/math.py, tests/scalar/test_math.py
Introduced in #283 
CC @tomicapretto
=> Fix mixed dtype bug in `gammaincc_grad`

.github/workflows/test.yml, setup.cfg, tests/link/jax/test_tensor_basic.py, tests/link/numba/test_basic.py, tests/link/numba/test_cython_support.py, tests/link/numba/test_performance.py, tests/link/numba/test_sparse.py
Also closes #322 even though the main goal was to fix the failing CI
=> Fix failing CI in Python 3.8 and install numba/jax on specific runs

pytensor/compile/profiling.py
I think this self-explanatory :) Lazily tested by making the same change inplace in the installed package. Example output (the numbers in the first column were missing):
```
<Sum apply outputs (bytes)> <Apply outputs shape> <created/inplace/view> <Apply node>
195504B  [(24438,), (24438,)] c c Elemwise{Composite}(increments, playerDayRatingSDevs {[11.512925...14543837]}, TensorConstant{(1,) of -0.5}, TensorConstant{(1,) of 0...5175704956}, TensorConstant{[ 2.443470..1.9280028]})
186496B  [(23312,), (23312,)] c c Elemwise{Composite}(Reshape{1}.0)
97752B  [(24438,)] c Alloc(TensorConstant{0.0}, TensorConstant{24438})
97752B  [(24438,)] i IncSubtensor{InplaceSet;int64:int64:}(extRatings, Subtensor{int64:int64:}.0, ScalarConstant{0}, ScalarConstant{2081})
...
```
=> Add missing "f" before format string (memory profiling)

README.rst, pytensor/graph/basic.py, pytensor/graph/op.py, pytensor/graph/utils.py, pytensor/printing.py, pytensor/scalar/basic.py, pytensor/scan/op.py, pytensor/tensor/elemwise.py, pytensor/tensor/math.py, pytensor/tensor/rewriting/math.py, pytensor/tensor/subtensor.py, pytensor/tensor/type.py, pytensor/tensor/var.py, tests/compile/test_builders.py, tests/graph/rewriting/test_basic.py, tests/link/test_utils.py, tests/scalar/test_basic.py, tests/scan/test_printing.py, tests/tensor/rewriting/test_basic.py, tests/tensor/rewriting/test_elemwise.py, tests/tensor/test_elemwise.py, tests/tensor/test_type.py, tests/tensor/test_var.py, tests/test_printing.py
**Please if you can: try with some examples of your own and give feedback** Specially if you have suggestions for Ops that have awful names that could be rendered better. I only tackled some I could think from memory.
Closes #313 
Closes #196 
Example from the issue:
```python
x = pt.scalar("x")
y = pt.vector("y")
z = x + pt.exp(y)
pytensor.dprint(z)
```
Before:
```
Elemwise{add,no_inplace} [id A]
|InplaceDimShuffle{x} [id B]
| |x [id C]
|Elemwise{exp,no_inplace} [id D]
|y [id E]
```
After:
```
Add [id A]
├─ ExpandDims{axis=0} [id B]
│  └─ x [id C]
└─ Exp [id D]
└─ y [id E]
```
Before with `print_type=True`
```
Elemwise{add,no_inplace} [id A] <TensorType(float64, (?,))>
|InplaceDimShuffle{x} [id B] <TensorType(float64, (1,))>
| |x [id C] …
```
=> Improve Op string representation and debug_print formatting

doc/library/d3viz/index.rst
The `pydot_ng` recommendation should be dropped since that project is officially archived in favor of pydot: https://github.com/pydot/pydot-ng. The idea for fixing this came out of this discussion: https://github.com/pymc-devs/pytensor/issues/333
Just fixed an install comand.
=> Don't recommend `pydot-ng`

pytensor/scalar/basic.py, pytensor/tensor/rewriting/jax.py, tests/link/jax/test_subtensor.py, tests/scalar/test_basic.py
Closes #338 
Closes #337 
Closes #331
=> Fix misc bugs

pytensor/tensor/basic.py, tests/link/numba/test_tensor_basic.py, tests/tensor/rewriting/test_basic.py, tests/tensor/test_basic.py
Closes #343 
Originally I was forcing a copy in the Numba implementation, but it makes more sense to make the Split Op a view on the inputs.
The C implementation does not exploit this, but we could if we wanted. Because of this, C graphs may become a bit more inefficient because they can no longer inplace on the outputs of `Split` even if these are always copies for now.
=> Make Split a view op

pytensor/graph/features.py, pytensor/graph/rewriting/basic.py, pytensor/scalar/basic.py
=> Don't change constant names in Features

pytensor/tensor/extra_ops.py, tests/tensor/rewriting/test_basic.py, tests/tensor/rewriting/test_math.py, tests/tensor/test_extra_ops.py, tests/unittest_tools.py
As discussed [here](https://github.com/pymc-devs/pytensor/discussions/100) we want to go back to static broadcasting only, and one this simplifies the rules for the expected shapes of broadcasted arrays quite a bit. This PR changes the broadcast_shape function to take advantage of this, which then simplifies a lot of graphs significantly.
I'm not sure yet how we should code the condition that triggers the assert for arrays that aren't compatible.
The current code contains an implementation that uses Elemwise, and one that uses scalar expressions.
The scalar expressions seem a bit more reasonable to me (not tensors and no allocations), but since most rewrites only work on Elemwise, this can prevent a lot of optimizations right now.
+ [ ] Make …
=> Use static-only broadcasting rules to compute shape of broadcasting

pytensor/scalar/basic.py, tests/link/jax/test_extra_ops.py, tests/tensor/test_extra_ops.py, tests/tensor/test_subtensor.py
CI started failing in other PRs because of this deprecation
=> Stop using deprecated `numpy.product`

pytensor/graph/basic.py, pytensor/graph/op.py, pytensor/tensor/basic.py, pytensor/tensor/extra_ops.py, pytensor/tensor/random/op.py, pytensor/tensor/shape.py, pytensor/tensor/var.py, tests/scan/test_rewriting.py, tests/tensor/random/test_basic.py, tests/tensor/test_basic.py, tests/tensor/test_extra_ops.py, tests/tensor/test_nlinalg.py, tests/tensor/test_shape.py, tests/tensor/test_var.py
=> Allow rebuilding graphs when output type depends on input values

pytensor/tensor/basic.py, pytensor/tensor/extra_ops.py, pytensor/tensor/math.py, pytensor/tensor/rewriting/elemwise.py, pytensor/tensor/rewriting/subtensor.py, pytensor/tensor/slinalg.py, pytensor/tensor/var.py, tests/tensor/rewriting/test_elemwise.py
This makes more sense as the rest of the codebase prioritizes `dimshuffle` over other reshape operations, and most rewrites target those.
There is even a rewrite to use expand_dims from reshape when safe.
=> Use Dimshuffle for `expand_dims`

pytensor/tensor/rewriting/special.py, pytensor/tensor/special.py, tests/d3viz/models.py, tests/tensor/rewriting/test_special.py, tests/test_rop.py
This makes the rewrite applicable to cases like the PMF of a Categorical, when probabilities are provided as a softmax and there is an expand_dims or indexing in between the `log` and `softmax`
Also removes the `axis` warning in softmax functions
=> Extend `log_softmax` stabilization rewrite to graphs with indexing and `expand_dims`

pytensor/compile/mode.py
The inplace rewrites have no effect whatsoever, and neither do the fusion, since we were not dispatching it to any lower level XLA. 
JAX docs state that JAX has comprehensive fusion rewrites so I think we can safely leave it to their implementation. 
Closes #122
=> Don't run useless fusion and inplace rewrites in JAX mode

pytensor/compile/mode.py, pytensor/configdefaults.py, pytensor/tensor/rewriting/basic.py, pytensor/tensor/rewriting/elemwise.py, pytensor/tensor/rewriting/math.py, tests/tensor/rewriting/test_elemwise.py, tests/tensor/rewriting/test_math.py
* Fix a couple of bugs in the careduce_fusion rewrite. These are very much related to some discussion on
https://github.com/pymc-devs/pytensor/pull/346 about tricky aspects of the CAReduce Ops. This rewrite was accidentally rarely used because it was registered outside the fusion database, and ran before the fusion rewrites. This explains why the failures where hidden for so long. It is now included in the same database, which is also related to the next point:
* Remove the flag to create the fusion database. This unnecessarily complicated the codebase logic, and the flag was not even "mutable". The same behavior can be done by excluding "fusion" tags from the compilation mode.
* Remove specialize_device database. This seems to be a left-over from the time Theano supported GPU. Only one …
=> Cleanup fusion rewrite database

pytensor/graph/basic.py, pytensor/graph/rewriting/utils.py, pytensor/tensor/elemwise.py, pytensor/tensor/rewriting/math.py, tests/tensor/rewriting/test_math.py, tests/tensor/test_elemwise.py
=> Fix miscelaneous bugs

pytensor/scalar/basic.py, pytensor/scan/rewriting.py, pytensor/tensor/basic.py, pytensor/tensor/rewriting/elemwise.py, pytensor/tensor/rewriting/math.py, pytensor/tensor/rewriting/shape.py, pytensor/tensor/var.py, tests/scalar/test_basic.py, tests/tensor/rewriting/test_elemwise.py, tests/tensor/rewriting/test_math.py, tests/tensor/rewriting/test_shape.py
This PR inlines constants in composite graphs, which reduces the number of variables that must be iterated over in the fused Elemwise graphs. I noticed some speedups when combined with `openmp` but not really otherwise. 
Would be interesting to check if `numba` benefits more from this. 
Regardless, this seems like a reasonable rewrite to include, if for nothing else that it also simplifies the debug_print of the final compiled graphs.
```python
x = pt.vector("x")
out = pt.exp(x + 2)
fn = pytensor.function([x], out)
pytensor.dprint(fn)
```
```
Composite{exp((2.0 + i0))} [id A] 0
└─ x [id B]
Inner graphs:
Composite{exp((2.0 + i0))} [id A]
← exp [id C] 'o0'
└─ add [id D]
├─ 2.0 [id E]
└─ i0 [id F]
```
There is no further constant folding triggered …
=> Inline constants in composite graphs

pytensor/link/jax/dispatch/elemwise.py, pytensor/link/numba/dispatch/elemwise_codegen.py, pytensor/tensor/__init__.py, pytensor/tensor/elemwise.py, pytensor/tensor/elemwise_cgen.py, pytensor/tensor/extra_ops.py, tests/link/jax/test_elemwise.py, tests/link/numba/test_elemwise.py, tests/tensor/rewriting/test_basic.py, tests/tensor/rewriting/test_math.py, tests/tensor/rewriting/test_shape.py, tests/tensor/test_elemwise.py
Related to #100 
Related to #149 
Related to #371
=> Forbid runtime broadcasting in Elemwise

pytensor/tensor/rewriting/basic.py, tests/tensor/rewriting/test_basic.py
I've seen graphs like these recently quite a bit, and we can avoid the allocation by removing the MakeVector call:
```
Sum{axes=None} [id A]
└─ MakeVector{dtype='int64'} [id B]
├─ Subtensor{i} [id C]
│  ├─ Shape [id D]
│  │  └─ x [id E]
│  └─ 0 [id F]
└─ Add [id G]
├─ Subtensor{i} [id H]
│  ├─ Shape [id I]
│  │  └─ x [id E]
│  └─ 1 [id J]
└─ 1 [id K]
```
This now gets rewritten to
```
Add [id A] 2
├─ 1 [id B]
├─ Shape_i{0} [id C] 1
│  └─ x [id D]
└─ Shape_i{1} [id E] 0
└─ x [id D]
```
In the same models I've also come across cases like this, that we could also rewrite, but this is not included here (there already is a rewrite for `Subtensor(MakeVector)`, but not for `IncSubtensor(MakeVector)`)
```
IncSubtensor{i} [id A] 4
├─ MakeVector{dtype='int64'} [id B] 3
│  ├─ Shape_i{0} [id C] 2
│ …
```
=> Add rewrite for Sum(MakeVector)

pytensor/tensor/extra_ops.py, pytensor/tensor/random/rewriting/basic.py, pytensor/tensor/rewriting/shape.py, pytensor/tensor/subtensor.py, tests/tensor/random/rewriting/test_basic.py, tests/tensor/test_extra_ops.py, tests/tensor/test_subtensor.py
This facilitates the logic in `local_subtensor_rv_lift` (where some bugs were also fixed)
=> Infer shape of advanced boolean indexing

pytensor/tensor/rewriting/linalg.py, tests/tensor/rewriting/test_linalg.py
Currently, the `tag_solve_trangular` rewrite looks for graphs like this:
```python
from numpy.testing import assert_allclose
A = pt.dmatrix('A')
b = pt.dmatrix('b')
L = pt.linalg.cholesky(A)
L_inv = pt.linalg.solve(L, b, assume_a='gen')
f = pytensor.function([A, b], [L_inv])
pytensor.dprint(L_inv)
Solve{assume_a='gen', lower=True, check_finite=True} [id A]
├─ Cholesky{lower=True, destructive=False, on_error='raise'} [id B]
│  └─ A [id C]
└─ b [id D]
```
And replaces then with this:
```python
pytensor.dprint(f)
Solve{assume_a='sym', lower=True, check_finite=True} [id A] 1
├─ Cholesky{lower=True, destructive=False, on_error='raise'} [id B] 0
│  └─ A [id C]
└─ b [id D]
```
The `Solve(assume_a='sym', lower=True)` solver was …
=> Fix bug in `tag_solve_triangular` rewrite

pytensor/tensor/random/basic.py, pytensor/tensor/random/op.py, pytensor/tensor/random/utils.py, tests/tensor/random/test_basic.py, tests/tensor/random/test_op.py, tests/tensor/random/test_utils.py, tests/tensor/rewriting/test_linalg.py
The default method is not robust and can lead to cryptic error messages.
In a discussion with a user https://discourse.pymc.io/t/pm-sample-prior-predictive-fails-with-incorrect-size-info-passed-to-the-rng-fn-function-of-the-randomvariable/12513 , they were trying to fake a multivariate distribution as a univariate because of the cryptic error induced by the default method.
We now raise `NotImplementedError` by default, and include illustrative examples in the docstrings that should help users implementing this method.
Also fixed a couple of minor bugs.
The changes will break RVs that relied on the default implementation. This should be easy to fix and won't go unnoticed.
=> Don't try to infer support shape of multivariate RVs by default

.github/workflows/test.yml, environment.yml, pyproject.toml, pytensor/graph/basic.py, tests/graph/test_basic.py
Compilation in some cases goes off for some reason and enters infinite loops. This fix resolves the issue, while the infinite loop in this check indicates that the real cause is some other bug.
As proposed by @aseyboldt I implemented the same logic with small refactoring
```diff
diff --git a/pytensor/graph/basic.py b/pytensor/graph/basic.py
index 0f9655647..ea1dfaed3 100644
--- a/pytensor/graph/basic.py
+++ b/pytensor/graph/basic.py
@@ -1091,6 +1091,8 @@ def truncated_graph_inputs(
ancestors_to_include = blockers.copy()
+    seen = {}
+
while candidates:
node = candidates.pop()
@@ -1099,6 +1101,12 @@ def truncated_graph_inputs(
if node in truncated_inputs:
continue
+        seen.setdefault(node, 0)
+        seen[node] += 1
+        if seen[node] > 1:
+            continue
+
if node in …
```
=> Speedup `truncated_graph_inputs`

pytensor/compile/function/pfunc.py, pytensor/graph/replace.py, tests/graph/test_replace.py
`pytensor.graph_replace` and `pytensor.clone_replace` have different signatures yet provide similar functionality. Sometimes it is handy to decide on which one to use, but since signatures are different it is hard to make changes.
I've changed typing to use `overload` in the appropriate places.
+ [x] The commits correspond to [_relevant logical changes_](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes). Note that if they don't, we will …
=> Unify signatures of `graph_replace` and `clone_replace`

pytensor/compile/mode.py
Temporarily minimizes #395 
Graphs may still fail if users explicitly create `uint` indexes but that's not very likely, and anyway it's a JAX bug.
=> Don't include `local_uint_constant_indices` rewrite in JAX mode due to XLA bug

.github/workflows/test.yml, pytensor/link/jax/dispatch/scalar.py, tests/link/jax/test_scalar.py
Closes #43 
Closes #91 
Closes #256
=> Provide JAX Ops from Optional tensorflow-probability dependency

pytensor/tensor/__init__.py
One can thus write:
```python
x = pt.scalar("x")
y = x * pt.pi
```
=> Add numpy constants to pytensor.tensor scope

pytensor/configdefaults.py, pytensor/link/jax/dispatch/extra_ops.py, pytensor/link/numba/dispatch/extra_ops.py, pytensor/tensor/basic.py, pytensor/tensor/extra_ops.py, pytensor/tensor/rewriting/basic.py, pytensor/tensor/rewriting/elemwise.py, pytensor/tensor/rewriting/extra_ops.py, pytensor/tensor/rewriting/math.py, tests/link/jax/test_extra_ops.py, tests/link/numba/test_extra_ops.py, tests/tensor/rewriting/test_basic.py, tests/tensor/rewriting/test_extra_ops.py, tests/tensor/test_basic.py, tests/tensor/test_extra_ops.py
* Remove `BroadcastTo` in favor of `Alloc`
* Address spoken inconsistencies between Second / Alloc in rewrites
* Add tag to easily exclude rewrites that can hide shape errors
* Simplify such rewrites
* Improve static shape of Alloc
Note that from a user standpoint, providing static shapes (via `vector("x", shape=(5,))` or `specify_shapes`) will many times reveal shape errors immediately (this is the case for 99% of PyMC models). In this case users should feel pretty safe about "shape_unsafe" rewrites because they aren't really masking anything that wasn't checked before already. 
`Alloc.make_node` now also raises early when it can see the provided shape is inconsistent. Alloc and Elemwise make up all of the tagged "shape_unsafe" rewrites so far.
With this PR, users can also do …
=> Add `shape_unsafe` tag to rewrites that can hide shape errors

pytensor/scalar/math.py
Currently, the [betainc_grad()](https://github.com/pymc-devs/pytensor/blob/0b558d8e65ee6603b80be566d36a036b68a97ee0/pytensor/scalar/math.py#L1363C24-L1363C52) and [gammainc_grad()](https://github.com/pymc-devs/pytensor/blob/0b558d8e65ee6603b80be566d36a036b68a97ee0/pytensor/scalar/math.py#L715C36-L715C36) functions have the same docstring:
```
Gradient of the regularized lower gamma function (P) wrt to the first
argument (k, a.k.a. alpha).
Adapted from STAN `grad_reg_lower_inc_gamma.hpp`
Reference: Gautschi, W. (1979). A computational procedure for incomplete gamma functions.
ACM Transactions on Mathematical Software (TOMS), 5(4), 466-481.
```
The fix attempts to clarify the function and indicates a probable resource that was utilized during the development of the function. I attempted to …
=> Fix docstrings reference for the betainc_grad function

pytensor/graph/rewriting/basic.py, tests/test_printing.py
The following fails on `main` because of a typo in an attribute name in the method `print_profile` of `EquilibriumGraphRewriter`:
``` python
pytensor.config.profile_optimizer = True
f = pytensor.function(inputs=[], outputs=[], profile=True)
f.profile.summary()
```
+ [x] The commits correspond to [_relevant logical changes_](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes). Note that if they don't, we will [rewrite/rebase/squash the git …
=> Fix typo in profile summary printing function

pytensor/link/numba/dispatch/extra_ops.py, pytensor/tensor/extra_ops.py, pytensor/tensor/var.py, tests/link/numba/test_extra_ops.py
=> Fix numba implementation of CumOp when axis is None

pytensor/link/jax/dispatch/tensor_basic.py, pytensor/link/numba/dispatch/basic.py, pytensor/link/numba/dispatch/tensor_basic.py, pytensor/tensor/basic.py, tests/link/jax/test_slinalg.py, tests/link/jax/test_tensor_basic.py, tests/link/numba/test_tensor_basic.py, tests/tensor/test_basic.py
* Extend ExtractDiag gradient to all cases
* Fixes wrong gradient for negative offsets  
* Fix/extend ExtractDiag Numba implementation to all cases
* Deprecate AllocDiag Op and use symbolic graph instead
* Gets rid of wrong Numba and JAX implementations 
* Extra: do not raise in JAX dispatch of Arange, when a non-constant input comes from a shape
=> Extend ExtractDiag gradient and numba implementation to higher dimensional inputs

pytensor/link/jax/dispatch/tensor_basic.py, pytensor/link/numba/dispatch/tensor_basic.py, pytensor/tensor/basic.py, tests/link/jax/test_elemwise.py, tests/link/jax/test_tensor_basic.py, tests/link/numba/test_elemwise.py, tests/link/numba/test_tensor_basic.py, tests/tensor/test_basic.py, tests/tensor/test_elemwise.py
Also fixes a bug encountered when doing alloc on a specify shape
Closes #379
=> Forbid runtime broadcasting by Alloc

pytensor/tensor/slinalg.py, tests/tensor/test_slinalg.py
Move `solve_discrete_are` from `pymc_experimental/statespace/pytensor_scipy.py` to here.
I also did a few cleanups in `tensor.slinalg.py`:
- Removed unused helper function `is_complex_obj`
- Removed unused `solvetriangular` instance of `SolveTriangular` (the `SolveTriangular` `Op` is instead accessed through the `solve_triangular` wrapper function)
- Changed return type hint on `Op` wrapper functions from `TensorVariable` to `Variable` to appease the linter
- Added `solve_discrete_lyapunov`, `solve_cotinuous_lyapunov`, `solve_discrete_are`, and `solve_triangular` to  `__all__`, so there are no more "hidden functions" in `nlinalg`
`Op` is just a wrapper around `scipy.linalg.solve_discrete_are`, with gradients taken from Kao and Hennequin (2020), https://arxiv.org/pdf/2011.11430.pdf
The …
=> Add `Op` corresponding to `scipy.linalg.solve_discrete_are`

pytensor/link/jax/dispatch/shape.py, pytensor/link/numba/dispatch/basic.py, pytensor/tensor/basic.py, pytensor/tensor/subtensor.py, tests/link/jax/test_shape.py, tests/tensor/test_subtensor.py
A collection of small fixes I have accumulated...
I thought it would be easier to just submit this as one PR instead of 5 small ones. The individual commits contain one fix each.
=> Various small fixes

pytensor/gradient.py
Fix docstrings that are not formatted correctly.
Closes #414 
According to https://numpydoc.readthedocs.io/en/latest/format.html#returns, return type is always required. Missing return types are added to gradient.py `grad` `Lop` and `Rop`.
+ [ ] The commits correspond to [_relevant logical changes_](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes). Note that if they don't, we will [rewrite/rebase/squash the git …
=> DOC: Fix docstrings in gradient.py

pytensor/compile/mode.py, pytensor/graph/__init__.py, pytensor/graph/replace.py, pytensor/link/numba/dispatch/nlinalg.py, pytensor/scalar/loop.py, pytensor/tensor/basic.py, pytensor/tensor/blockwise.py, pytensor/tensor/elemwise.py, pytensor/tensor/nlinalg.py, pytensor/tensor/random/op.py, pytensor/tensor/rewriting/__init__.py, pytensor/tensor/rewriting/blockwise.py, pytensor/tensor/rewriting/linalg.py, pytensor/tensor/slinalg.py, pytensor/tensor/utils.py, scripts/mypy-failing.txt, tests/graph/test_replace.py, tests/link/numba/test_nlinalg.py, tests/tensor/random/test_op.py, tests/tensor/rewriting/test_blockwise.py, tests/tensor/rewriting/test_linalg.py, tests/tensor/test_blockwise.py, tests/tensor/test_elemwise.py, tests/tensor/test_slinalg.py
Critical for https://github.com/pymc-devs/pymc/issues/5383
This PR was done almost completely from scratch, although the general principles and some of the code were obviously inspired by https://github.com/aesara-devs/aesara/pull/1215
For fairness, all authors of the commits in that PR were added as co-authors here.
CC @purna135
Some design questions:
1. Do we want to make Blockwise the "default" form of an Op (in terms of rewrites), and only later specialize if they were not needed?  **Decided yes**
2. Do we want to fuse consecutive Blockwises with the same batched dims, similarly to how we fuse consecutive Elemwises? **Not for now**
3. Can Rop be implemented just as the batched core Rop, like L_op?
Important follow-up:
1. Dispatch to JAX and Numba
2. ~~Create a PyTensor "vectorize" …
=> Implement Blockwise Op to vectorize existing Ops

pytensor/tensor/basic.py, pytensor/tensor/nlinalg.py, tests/tensor/test_basic.py, tests/tensor/test_blockwise.py, tests/tensor/test_nlinalg.py, tests/tensor/test_variable.py
Provide the same function names and behavior as numpy to reduce confusion
=> Deprecate `extract_diag` and `linalg.trace` in favor of numpy look-alikes

pytensor/link/numba/dispatch/elemwise.py, tests/link/numba/test_elemwise.py
Closes #434 
CC @kc611, am I missing a better solution?
=> Fix SoftmaxGrad failure with constant dy in numba backend

pytensor/tensor/rewriting/uncanonicalize.py, tests/tensor/rewriting/test_uncanonicalize.py
This showed up now that we improved the static type of subtensors and there are more cases where we can "squeeze" degenerate dims coming out of subtensor operations.
Showed up in https://github.com/pymc-devs/pymc/pull/6897
=> Fix bug in `local_dimshuffle_subtensor` rewrite

pytensor/link/jax/dispatch/scan.py, pytensor/link/numba/dispatch/scan.py, tests/link/jax/test_scan.py
The whole inner mode is still a problem, but for now another bandaid
Closes #426
=> Exclude backend incompatible rewrites in Scan dispatch

pytensor/compile/mode.py
=> Exclude local_careduce_fusion from Numba backend

pytensor/ifelse.py, pytensor/tensor/math.py, pytensor/tensor/rewriting/blockwise.py, pytensor/tensor/variable.py, tests/tensor/test_math.py, tests/tensor/test_variable.py
We use a Blockwised Dot for matmul so that we get gradients for free.
C-performance won't be great for Blockwised Dot, since that doesn't have a C-implementation. 
We could Blockwise more specialized Dot22 / GEMM Ops but that code is a bit of a mess at the moment and not useful long term as we deprecate the C backend
~~Alternatively we probably could use `tensor_dot`/`batched_dot`?~~ They are fundamentally different (or it would be rather inefficient to convert one to the other) 
Closes #451 
Needed for https://github.com/pymc-devs/pymc/pull/6897
=> Use Blockwise for matmul

.github/workflows/pypi.yml, pytensor/tensor/rewriting/linalg.py, tests/tensor/rewriting/test_linalg.py
Also restrict to 2D Dot cases
Also reverts #455
=> Extend cholesky of triangular dot rewrite to matmul Ops

pytensor/link/jax/dispatch/random.py, pytensor/tensor/random/basic.py, pytensor/tensor/random/rewriting/jax.py, tests/link/jax/test_random.py, tests/link/numba/test_random.py, tests/tensor/random/test_basic.py
The current implementation of `GammaRV` inverts the passed `rate` (`beta`) parameter upon each call. This breaks functionality in `pymc` [as described in this bug report](https://github.com/pymc-devs/pymc/issues/6931). ~~This PR changes the parameterization so that we only invert `beta` when we draw samples. Along with [this pytensor PR](https://github.com/pymc-devs/pymc/pull/6934), the bug is fixed.~~ This PR changes the parameterization to store `scale` (`1/beta`) and adds a helper function to convert `rate` to `scale` and warn the use that `rate` is deprecated.
No changes to API.
+ [X] Explain motivation and implementation 👆
+ [X] Make sure that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html).
+ [X] Link relevant issues, …
=> Do not invert Gamma rate and fix JAX implementation of Gamma and Pareto

pytensor/tensor/rewriting/math.py, tests/tensor/rewriting/test_math.py
=> Fail graciously in local_pow_to_nested_squaring when static type shape is updated

pytensor/tensor/variable.py, tests/tensor/test_variable.py
Introduced in #452 
Closes #464
CC @tomicapretto
=> Fix bug in `TensorVariable.__rmatmul__`

pytensor/link/numba/dispatch/elemwise.py, tests/link/numba/test_elemwise.py
Fix a bug where inplace operations in numba mode could lead to a mismatch between reported and actual numba types, which then lead to errors like the following:
```python
import pymc as pm
with pm.Model() as model:
pm.ZeroSumNormal("x", shape=(3, 7))
dlogp = model.dlogp()
func_fail = pytensor.function(model.value_vars, [dlogp], mode=pytensor.compile.mode.NUMBA)
func_fail(np.zeros((3, 6)))
```
```
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
File ~/git/pytensor/pytensor/link/utils.py:202, in streamline.<locals>.streamline_default_f()
199 for thunk, node, old_storage in zip(
200     thunks, order, post_thunk_old_storage
201 ):
--> 202     thunk()
203 …
```
=> Correctly report the elemwise output type in Numba

pytensor/tensor/random/op.py, pytensor/tensor/type.py, tests/tensor/random/test_basic.py, tests/tensor/test_basic.py, tests/tensor/test_type.py
This bug showed up in https://github.com/pymc-devs/pymc/pull/6947
```python
p = pt.ones(3) / 3
x = pt.random.categorical(p=pt.stack([p, 1-p], axis=-1))
assert x.type.shape == (3,)  # AssertionError
```
Which would later lead to a rewrite error during compilation.
It was caused by the presence of `np.int` in the static shape of Join, (and corresponding `np.bool` in the broadcastable), which would then be overlooked by an explicit check `broadcastable is False` in the `RandomVariable.infer_shape`.
=> Fix static type shape bug

pytensor/link/c/exceptions.py
fix #481 when setuptools is too old
=> Fix import errors if setuptools is too old

environment.yml, pyproject.toml, pytensor/link/c/cmodule.py, tests/link/c/test_cmodule.py
Closes #441 
`numpy.__config__.get_info` has been deprecated and removed, so we have to set default link libraries some other way.
This is a very rough first implementation. The idea is to use something like python's `sys.path` to look for libraries files (this would match a conda env lib folder and also the system level python lib folders, I still need to figure out what to do with venvs). Then look for some default libraries to link against, like mkl or openblas. I added LAPACK, but maybe the c code that is generated by `pytensor` doesn't have the proper includes to be able to link against that.
I haven't changed any other code yet, but the long term goal would be to remove most of the blas ldflag logic from the startup. In particular, I flagged a couple of platforms for deprecation …
=> Change default blas_info dictionary in cmodule

pytensor/link/jax/dispatch/__init__.py, pytensor/link/jax/dispatch/blockwise.py, pytensor/tensor/blockwise.py, tests/link/jax/test_blockwise.py, tests/tensor/test_blockwise.py
Also adds checks for runtime broadcasting that were missing
Related to #430
=> Support Blockwise in JAX backend

pytensor/tensor/rewriting/linalg.py, tests/tensor/rewriting/test_linalg.py, tests/tensor/test_blockwise.py
Related to https://github.com/pymc-devs/pymc/issues/6993 and https://discourse.pymc.io/t/version-dependant-slowing-down-of-gaussian-mixture-sampling-in-ubuntu-20-04/13219
This PR adds a rewrite that optimizes solve when there is a batched vector b (b_ndim=1) and a single a. 
This form was previously used for the logp of MvNormal in PyMC and is potentially much faster when the batched dimensions of b are large. More importantly the grad will look better. 
I have a couple of other PRs that improve the blockwise grads for the truly new supported cases, but that it's slower work.
PS: Obviously we should also implement the JAX Ops https://github.com/pymc-devs/pytensor/issues/430, but this looks like a nice optimization, specially if it solves the regression described in the discourse issue …
=> Add specialization rewrite for solve with batched b

pytensor/tensor/variable.py, tests/tensor/test_variable.py
Uses a similar syntax as JAX, which is considerably less verbose.
```python
x = pt.matrix()
x[0].set(5)  # Equivalent to `pt.set_subtensor(x[0], 5)`
x[0].add(5)  # Equivalent to `pt.inc_subtensor(x[0], 5)`
```
=> Add `set` and `add` TensorVariable methods for `set_subtensor` and `inc_subtensor` operations`

pytensor/link/jax/dispatch/scalar.py, tests/link/jax/test_scalar.py
Closes #497 
Let's open a separate issue for adding the general PolyaGamma Op
=> Implement JAX dispatch for TriGamma

doc/library/tensor/random/basic.rst, pytensor/link/numba/dispatch/random.py, pytensor/tensor/random/basic.py, pytensor/tensor/random/rewriting/jax.py
Simplify by using the gamma distribution directly based on [PyMC PR](https://github.com/pymc-devs/pymc/pull/7007)
Remove any ChiSquare reference including the rewrites and documentation
+ [x] The commits correspond to [_relevant logical changes_](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes). Note that if they don't, we will [rewrite/rebase/squash the git history](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#_rewriting_history) before …
=> Implement ChiSquare via Gamma

pytensor/graph/__init__.py, pytensor/graph/replace.py, pytensor/tensor/__init__.py, pytensor/tensor/blockwise.py, pytensor/tensor/functional.py, pytensor/tensor/utils.py, tests/graph/test_replace.py, tests/tensor/test_blockwise.py, tests/tensor/test_functional.py
Just a difference between providing a function or working on an existing graph. 
Creating dummy inputs may not be intuitive to many users, so this helps with that. Also behaves more like NumPy.
```python
def func(x):
return pt.exp(x) / pt.sum(pt.exp(x))
vec_func = pt.vectorize(func, signature="(a)->(a)")
x = pt.matrix("x")
y = vec_func(x)
fn = pytensor.function([x], y)
fn([[0, 1, 2], [2, 1, 0]])
```
=> Implement vectorize helper with similar semantics to that of NumPy

pytensor/tensor/variable.py, tests/tensor/test_variable.py
For consistency with the existing name. I also think it's more intuitive.
=> Rename `add` `inc_subtensor` helper method to `inc`

pytensor/gradient.py, pytensor/scalar/math.py, pytensor/tensor/math.py, pytensor/tensor/rewriting/math.py, tests/link/jax/test_scalar.py, tests/tensor/rewriting/test_math.py, tests/tensor/test_math.py
=> Implement Polygamma Op

pytensor/graph/replace.py, pytensor/tensor/blockwise.py, pytensor/tensor/elemwise.py, pytensor/tensor/shape.py, tests/tensor/test_shape.py
It also fixes a bug when Blockwising a Reshape Op, as the perform method had a non-optional (useless) `params` kwarg
=> Vectorize dispatch for shape operations

pytensor/link/c/cmodule.py, tests/link/c/test_cmodule.py
Closes #504 
- ...
- ...
- Default blas_ldflags are empty if no compiler is configured
- ...
- ...
=> Use empty blas_ldflags if no cxx is configured

pytensor/link/c/cmodule.py, tests/link/c/test_cmodule.py, tests/link/c/test_op.py, tests/test_printing.py
Closes #515
- ...
- ...
- Fix conda C library detection on Windows
- ...
- ...
=> Handle windows conda library directories in default blas

doc/extending/using_params.rst, pytensor/graph/basic.py, pytensor/graph/op.py, pytensor/link/c/basic.py, pytensor/link/c/interface.py, pytensor/link/c/op.py, pytensor/link/numba/dispatch/basic.py, pytensor/raise_op.py, pytensor/scan/op.py, pytensor/tensor/basic.py, pytensor/tensor/blas.py, pytensor/tensor/elemwise.py, pytensor/tensor/extra_ops.py, pytensor/tensor/math.py, pytensor/tensor/rewriting/uncanonicalize.py, pytensor/tensor/shape.py, pytensor/tensor/subtensor.py, tests/link/c/test_params_type.py, tests/link/c/test_type.py, tests/tensor/test_blockwise.py
=> Make params exclusive to `COp`s

pytensor/compile/function/types.py, pytensor/compile/profiling.py
This can be a big chunk of time in the first function that is compiled.
=> Include C cache preloading in profile output

pytensor/graph/replace.py
It also prevents node duplication
=> Faster vectorize by walking sorted nodes

pytensor/tensor/basic.py, pytensor/tensor/rewriting/basic.py, pytensor/tensor/rewriting/math.py, pytensor/tensor/rewriting/shape.py, pytensor/tensor/rewriting/subtensor.py, pytensor/tensor/shape.py, scripts/mypy-failing.txt
This method which is called every time we create an Alloc or RandomVariable Op, can be pretty slow, because it calls canonicalize + constant_folding on the shape graph, which can be pretty large sometimes. This can also be pretty wasteful if the shapes are already constant to begin with!
The utility is now much more targeted, using only rewrites that are directly relevant for static shape propagation. It also avoids doing costly C-compilation
This should result in much snappier creation of RandomVariables and rewrites
=> Faster `infer_static_shape`

pytensor/link/c/cmodule.py
=> Add _logger.debug statements to cmodule default blas ldflags

pytensor/tensor/rewriting/math.py, tests/tensor/rewriting/test_elemwise.py, tests/tensor/rewriting/test_math.py
Extend the Sum of Mul rewrite beyond the scalar case. We extract variables that have only degenerate dims along the reduced dimensions. In the case of a total sum only scalars can be pulled out, which was exactly the case supported by the old rewrite.
I am not so hot on the Prod of Mul rewrite, but since it was there already, we keep it. This actually fixes a bug when the prod only does a partial reduction, in which case the old logic of raising the extracted values to the power of the whole inner size was wrong. I added a test that failed in main in the first commit. The expanded rewrite comes up in the second commit, and fixes the failing test.
I also separated the rewrite for Sum(-mul) since it shares almost no logic with the larger rewrite. The usefulness of generalizing this rewrite …
=> Extend sum of mul rewrite for multiple axis

pytensor/graph/basic.py, pytensor/link/jax/dispatch/nlinalg.py, pytensor/link/numba/dispatch/basic.py, pytensor/tensor/basic.py, pytensor/tensor/blas.py, pytensor/tensor/blockwise.py, pytensor/tensor/extra_ops.py, pytensor/tensor/math.py, pytensor/tensor/rewriting/basic.py, pytensor/tensor/rewriting/blas.py, pytensor/tensor/rewriting/blockwise.py, pytensor/tensor/rewriting/linalg.py, pytensor/tensor/rewriting/subtensor.py, pytensor/tensor/shape.py, pytensor/tensor/subtensor.py, tests/link/jax/test_nlinalg.py, tests/link/numba/test_basic.py, tests/tensor/rewriting/test_basic.py, tests/tensor/rewriting/test_blas.py, tests/tensor/rewriting/test_blockwise.py, tests/tensor/rewriting/test_subtensor.py, tests/tensor/test_basic.py, tests/tensor/test_blockwise.py, tests/tensor/test_subtensor.py
This PR adds a bunch of blockwise improvements, using `test_batched_mvnormal_logp_and_dlogp` as a benchmark.
```
BEFORE:
------------------------------------------------------------------------------------------------------------------------- benchmark: 9 tests -------------------------------------------------------------------------------------------------------------------------
Name (time in us)                                                             Min                     Max                    Mean                 StdDev                  Median                     IQR            Outliers         OPS            Rounds  Iterations
--------------------------------------------------------------------------------------------------------------------------------------------------------- …
```
=> Blockwise improvements

pytensor/link/jax/dispatch/scalar.py, pytensor/scalar/math.py, pytensor/tensor/inplace.py, pytensor/tensor/math.py, tests/tensor/test_math_scipy.py
Fixes #542
As with `Iv`, uses scipy implementation in C code and tensorflow probability implementation for jax.
=> Add Exponentially scaled modified Bessel Op

pytensor/tensor/basic.py, pytensor/tensor/random/op.py, pytensor/tensor/rewriting/shape.py, tests/tensor/random/test_op.py, tests/tensor/test_basic.py
The PyMC CI revealed two bugs in the PyTensor release:
1. A rewrite that did not handle the shape of scalars correctly introduced in the latest release in #521
2. A bug in the shape inference of multivariate RVs when size is not provided and the parameters batch dimensions require broadcasting. This bug was lurking for a long time now.
=> Fix bugs in shape inference

pytensor/tensor/blas.py, tests/tensor/test_blas.py
=> Do not generate C code for BatchedDot when BLAS flags are missing

pytensor/raise_op.py, tests/test_raise_op.py
Implement vectorize dispatch for Assert. This crops up a lot when vectorizing logp graphs in PyMC.
=> Implement `vectorize_node` for `CheckAndRaise` `Op`

pytensor/graph/replace.py
Docstring still uses old name of `vectorize`
=> Update vectorize_graph docstring

pytensor/tensor/rewriting/math.py, tests/tensor/rewriting/test_math.py
This rewrites replaces a batched matmul by a core matmul by raveling the batched dimensions of the batched input, doing a 2D matmul and then unravelling the batched dimensions of the output.
This sidesteps the Blockwise Dot operation and allows specialization into BLAS routines.
The idea was taken from these two discussions:
https://github.com/numpy/numpy/issues/7569
https://github.com/numpy/numpy/issues/8957
=> Add rewrite for matmul when only one of the inputs has batched dimensions

.github/workflows/pypi.yml, .github/workflows/test.yml
This reverts commit 0fc2cd8e11be7a4d679cc78a3a8c0d4f825a2db6 which caused the CI to start failing
=> Revert "Bump actions/download-artifact from 3 to 4"

pytensor/tensor/rewriting/shape.py, tests/tensor/rewriting/test_shape.py
=> Fix bug where ShapeFeature would create circular shape graph

pytensor/tensor/basic.py, pytensor/tensor/elemwise.py, pytensor/tensor/math.py, pytensor/tensor/shape.py, pytensor/tensor/special.py, tests/tensor/test_math.py, tests/tensor/test_special.py
The Softmax and LogSoftmax unfortunately don't support partial axes, so we have to fallback to Blockwise when more than one axis was used in the core case.
=> Vectorize softmax and argmax nodes

pytensor/tensor/rewriting/linalg.py, tests/tensor/rewriting/test_linalg.py
To invert a positive semi-definite matrix, it is faster to first cholesky factorize the matrix then use two triangular solves rather than directly using solve. Here's a lazy benchmark:
```python
from scipy import linalg
N = 10_000
Z = np.random.normal(size=(N, N))
X = Z @ Z.T
def direct_solve(X, N):
return linalg.solve(X, np.eye(N), assume_a='pos')
def tri_solve(X, N):
L = linalg.cholesky(X, lower=True)
b = np.eye(N)
Li_b = linalg.solve_triangular(L, b, lower=True)
x = linalg.solve_triangular(L.T, Li_b, lower=False)
return x
direct_time = %timeit -o direct_solve(X, N)
tri_time = %timeit -o tri_solve(X, N)
12.7 s ± 369 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
11.5 s ± 165 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
The triangular method is …
=> Remove incorrect `solve` usage in `psd_solve_with_chol` rewrite

pytensor/link/jax/dispatch/slinalg.py, pytensor/link/numba/dispatch/slinalg.py, pytensor/sparse/basic.py, pytensor/tensor/basic.py, pytensor/tensor/slinalg.py, tests/link/jax/test_slinalg.py, tests/link/numba/test_slinalg.py, tests/sparse/test_basic.py, tests/tensor/test_slinalg.py
There are a number of generic math-type operations in `pymc.math` that make more sense in `pytensor`. This PR moves one of them -- `block_diag`, to `pytensor.tensor.slinalg`. There are others that could likely be moved as well.
`block_diag` uses a few support functions that also present opportunities to implement some missing numpy functions in pytensor. I re-wrote `largest_common_dtype` to use `np.promote_types`, but there should probably be a `pt.promote_types` and `pt.result_type`. The latter should just replace this helper function entirely.
There was also a function `ix`, which is an implementation of `np.ix_`. We're missing all of these numpy quick constructors: `np.r_`, `np.c_`, `np.ogrid`, `np.mgrid`. Plus `np.meshgrid`, which is an actual function people use.
`floatX` and `intX` …
=> Add `linalg.block_diag` and sparse equivalent 

pytensor/graph/basic.py, pytensor/graph/replace.py, tests/graph/test_basic.py, tests/graph/test_replace.py
The provided output could be silently ignored and replaced by the new output of the vectorized node.
Also avoids vectorizing multiple-output nodes when none of the unreplaced outputs are needed.
=> Fix `vectorize_graph` bug when replacements were provided for only some outputs of a node

pytensor/tensor/blas.py, pytensor/tensor/blas_scipy.py, scripts/mypy-failing.txt, tests/tensor/test_blas_scipy.py
This is a preliminary PR that hopes to address the various issues that came up around `pymc` with pickling `fortran` objects. For reference, [here](https://discourse.pymc.io/t/typeerror-cannot-pickle-fortran-object/9786/6), [here](https://github.com/pymc-devs/pymc/issues/5864), [here](https://discourse.pymc.io/t/bambi-error-cannot-pickle-fortran-object/10858), and there might be more that I'm missing.
This is still a very early draft because I haven't built a reproducible code that shows the error, I hope to be able to do so next week. Once I do, I'll open a proper issue here on `pytensor`, add unit tests and promote this PR from its draft status.
=> Don't store `fortran` objects in `ScipyGer` tag

pytensor/link/jax/linker.py, tests/link/jax/test_random.py
When transpiling functions with Shared RNGs to the JAX backend, we replace the original variables by copies so that we can update them in the same container without changing the data type (JAX PRNGs vs numpy Generator), so that the same shared variable can be reused in other functions, which may use distinct backends.
There was a bug in that this replacement could change the position of the input variable in the FunctionGraph, and disalign it with the pre-defined input_storage list. This PR fixes the bug by forcing the position of the new input variable in the FunctionGraph to be the same as the one in input_storage list.
AFAICT the order of the FunctionGraph inputs is not stored/referenced anywhere internally, so this should be safe.
This showed up when trying to use PyMC VI with the JAX …
=> Fix bug in storage_input alignment of the JAX backend

pyproject.toml
Makes downstream packaging simpler and more robust, avoiding the need for downstream patches when versioneer is updated.
Building with versioneer v0.29.0 works fine on Arch Linux, see: https://aur.archlinux.org/packages/python-pytensor.
=> Loosen versioneer version requirement from exact to min version

pytensor/compile/profiling.py, pytensor/graph/rewriting/basic.py, pytensor/link/utils.py, pytensor/tensor/rewriting/elemwise.py
In the course of #586 we observed that newer versions of `pyupgrade` (the current latest `3.15.0` vs the outdated `3.3.1` configured in `.pre-commit-config.yaml`) caught a few more issues that `ruff` missed. I'm not sure why; perhaps `pyupgrade` is more up-to-date than `ruff`.
We can merge these particular fixes, but it's probably worth considering what to do here in general. Like should we still run `pyupgrade`, and perhaps also `flake8` in the CI to ensure that `ruff` isn't missing stuff?
=> Apply pyupgrade fixes missing from ruff

pytensor/graph/basic.py, pytensor/graph/rewriting/basic.py, tests/tensor/test_math.py
This is a refactor designed to make these parts of code slightly more inspectable by type checkers like `mypy`.
1. We use `@overload` to distinguish between the two distinct usages of `general_toposort` for which different sets of arguments are specified.
2. When a variable represents a callable, we differentiate between the variable definition and the function definition. The principle is as follows:
Worse:
```python
if cond:
def chosen_function()
...
else:
def chosen_function()
...
```
Better:
```python
def function_option_1():
...
def function_option_2():
...
if cond:
chosen_function = function_option_1
else:
chosen_function = function_option_2
```
The first option is worse because the definition of the underlying function changes based on the runtime logic. The second option is …
=> Fix redefinitions

pytensor/link/numba/dispatch/basic.py, pytensor/link/numba/dispatch/slinalg.py, pytensor/tensor/slinalg.py, tests/link/numba/test_nlinalg.py, tests/link/numba/test_slinalg.py
Tests are failing on #577 for the numba overloaded cholesky routine and I realized we didn't have a real one, so here it is. Now fully compatible with all the scipy keyword arguments. In addition, it will no longer drop numba into object mode.
=> Implement numba overload for POTRF, LAPACK cholesky routine

.github/workflows/test.yml, .pre-commit-config.yaml, pyproject.toml, pytensor/tensor/shape.py
Closes #472
Get the latest Python goodness
Basically just 3.11→3.12
+ [X] Explain motivation and implementation 👆
+ [X] Make sure that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html).
+ [X] Link relevant issues, preferably in [nice commit messages](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html).
+ [X] The commits correspond to [_relevant logical changes_](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes). Note that if they don't, we will [rewrite/rebase/squash the git history](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#_rewriting_history) before merging.
+ [X] Are the changes covered by tests and docstrings?
+ [X] Fill out the short summary sections 👇
- ...
- …
=> Support Python 3.12

pytensor/tensor/math.py, tests/tensor/test_math.py
This PR discards the past implementation of `tensordot` and uses the one from `numpy`. The past implementation had many problems:
- It had two completely independent branches of execution so code was not thoroughly testes.
- It was recursive. If you passed in `axes` as a sequence of sequences, it tried to do transpose the dimensions and then call `tensordot` again using `axes` as an integer. This made things harder to maintain.
- It had bugs as shown by #606.
- It lost the static shape information.
Taking the implementation from `numpy` works well. It handles all the cases of `axes`, it has a single execution branch, and preserves the static shape information. The only downside is that it does not have the logic to implement `batched_tensordot`. From my point of view, this is **a good …
=> Fix tensordot implementation

tests/test_printing.py
=> Do not change global config flag in printing test

pytensor/link/c/cmodule.py
This fixes an error encountered when importing `pymc` in a rmarkdown document code chunk. 
In that context, `sys.stdout` is replaced with a `StringIO()` object to capture all output, and `sys.stdout.encoding` returns `None`, raising an exception.
closes https://github.com/rstudio/reticulate/issues/1508
=> Replace usage of `sys.stdout.encoding` with `sys.getdefaultencoding()`

.github/workflows/test.yml
This reverts commit 69319ef8795712427d41902e4fcf24260af716df.
=> Test Numba with Python 3.12 instead of 3.11

pytensor/tensor/sharedvar.py, tests/tensor/test_sharedvar.py
As explained in the related issue this class is messy because it internally upcasts the values to 0d arrays, so that `shared(shared(5).get_value())` belongs to a different class than `shared(5)` but are exactly the same objects otherwise!
This was a source of bugs in PyMC. The way you create an object shouldn't matter for type checks, only what you actually ended up creating!
There is a proper ScalarSharedVariable if someone really wants to work with scalar types
=> Deprecate ScalarSharedVariable

pytensor/tensor/nlinalg.py, tests/tensor/test_nlinalg.py
Currently, `pt.linalg.norm` does not match the signature of `np.linalg.norm` -- it is missing the `axis` and `keepdims` arguments, and has no logic for handling complex-valued matrices. This PR fixes this by copy-pasting the `np.linalg.norm` code to pytensor.
In addition, some extra logic is needed to allow for tensor-valued inputs to `norm`. This part is still a WIP. The tests need to be refactored to test all the new combinations of keyword arguments as well.
This is a preliminary step to addressing https://github.com/pymc-devs/pymc/issues/7101, because the correct transformation between unconstrained lower-triangular matrices to cholesky factorized matrices involves row-normalizing the unconstrained lower-triangular matrix; see …
=> Refactor `nlinalg.norm` to match `np.linalg.norm` signature and functionaly

pytensor/scalar/c_code/gamma.c, pytensor/scalar/math.py, tests/scalar/test_math.py
gammainc C code does not have a special case for np.inf.
Instead of returning 0, 1 or nan it always return nan.
The solution is to add special cases conditions following scipy implementation: https://github.com/scipy/scipy/blob/4ecf5638c36c3a87b473056f5fffecfeddffd368/scipy/special/cephes/igam.c#L149-L151
=> Add inf special cases to gamma.c function

pytensor/tensor/special.py, tests/tensor/test_special.py
Implement tensor helper equivalent for [scipy.special.logit](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.logit.html#scipy.special.logit)
=> Implement `tensor.special.logit` helper

pytensor/link/jax/dispatch/tensor_basic.py, tests/link/jax/test_tensor_basic.py
Implement JAX conversion for SortOp
=> Add JAX support for SortOp

pytensor/tensor/rewriting/basic.py, tests/tensor/rewriting/test_basic.py
This PR changes the behavior of `local_sum_make_vector` to skip rewriting whenever the internal accumulator is more precise than both the input/output data and `config.floatX`. Otherwise, the internal accumulator is added to the graph, which can introduce forbidden `float64` to the graph when the user requests `config.floatX="float32"`.
Replaces PR https://github.com/pymc-devs/pytensor/pull/655 and https://github.com/pymc-devs/pytensor/pull/656
=> Prevent `local_sum_make_vector` from introducing forbidden `float64`

pytensor/link/c/cmodule.py
I tested PyTensor with PyPy and it fails with:
```
ld: cannot find -lpypy3-c: No such file or directory
```
The problem is this code that handles PyPy as a special case.
For example, the correct value for libname may be `"pypy3.9-c"` and can be inferred from `LDLIBRARY`, but setting it to `"pypy3-c"` leads to the aforementioned failure.
=> Fix PyPy by eliminating deprecated library detection code

pytensor/tensor/rewriting/basic.py, tests/link/jax/test_scan.py, tests/tensor/rewriting/test_basic.py
=> Allow more dynamic shape scans to be compiled

pytensor/tensor/random/op.py, pytensor/tensor/random/utils.py, tests/tensor/random/test_op.py
=> Handle implicit broadcasting correctly in RandomVariable vectorization

pytensor/scalar/basic.py, tests/scalar/test_basic.py
Prevent `log10` `L_op` from upcasting.
=> prevent `log10` `L_op` from upcasting

pytensor/link/numba/dispatch/basic.py, pytensor/link/numba/dispatch/scalar.py, tests/link/numba/test_basic.py
=> Suppress caching warning when compiling Numba functions

.github/workflows/test.yml, environment.yml, pyproject.toml
The project seems abandoned and we are not using it anymore anyway afaict.
=> Remove numba-scipy dependency

pytensor/compile/builders.py, tests/compile/test_builders.py
Also adds a strict flag
This changes make working with OpFromGraph much simpler, as we can fully control the signature of OpFromGraph without having to worry whether the variables we are using to define the inner graph are shared/constants. 
This facilitates the work being done in https://github.com/pymc-devs/pymc/pull/6947
=> Allow defining an OpFromGraph from constant and shared inputs

pytensor/sparse/basic.py, pytensor/sparse/sharedvar.py, pytensor/tensor/sharedvar.py
=> Make Constant and Shared variables subclasses of the respective Variables

pytensor/tensor/rewriting/basic.py, tests/tensor/rewriting/test_basic.py
Showed up in https://github.com/pymc-devs/pymc/pull/6947
=> Fix bug when broadcasting branches in local_useless_switch rewrite

pytensor/link/c/cmodule.py
This is an attempt to solve
```python
tests\distributions\test_transform.py:347: in check_vectortransform_elementwise_logp
self.check_transform_elementwise_logp(model, vector_transform=True)
tests\distributions\test_transform.py:318: in check_transform_elementwise_logp
test_array_untransf = x_val_untransf.eval({x_val_transf: test_array_transf})
C:\Users\runneradmin\miniconda3\envs\pymc-test\Lib\site-packages\pytensor\graph\basic.py:616: in eval
self._fn_cache[inputs] = function(inputs, self)
C:\Users\runneradmin\miniconda3\envs\pymc-test\Lib\site-packages\pytensor\compile\function\__init__.py:315: in function
fn = pfunc(
C:\Users\runneradmin\miniconda3\envs\pymc-test\Lib\site-packages\pytensor\compile\function\pfunc.py:469: in pfunc
return orig_function( …
```
=> Ensure that gcc path is only added once to DLL search path

tests/compile/test_builders.py
The tests in #676 were incomplete :)
=> Cleanup OpFromGraph tests

pytensor/link/c/cmodule.py
As reported in <https://github.com/pymc-devs/pytensor/pull/678#issuecomment-2036674730>, mypy was failing on Windows due to an unnecessary `# type: ignore`. This fixes it by ignoring the `unused-ignore` so that Windows is covered.
I'm marking this as maintenance since it's not a runtime bugfix.
Fixes an issue introduced and reported in #678.
=> Fix mypy problem on Windows due to platform differences

pytensor/tensor/basic.py, pytensor/tensor/rewriting/linalg.py, pytensor/tensor/variable.py, scripts/mypy-failing.txt, tests/tensor/test_basic.py
Added support for ```matrix_transpose``` operation using pytensor. The function and the tests are similar to its [numpy implementation](https://github.com/numpy/numpy/blob/main/numpy/_core/fromnumeric.py#L675-L704).
Also added a temporary fix for the [mypy error](https://github.com/pymc-devs/pytensor/pull/678#issuecomment-2047623270).
=> Added support for matrix_transpose

pytensor/configdefaults.py
Update configdefaults to only attempt to retrieve gcc_version_str iff config.cxx is non-empty.
=> Only invoke config.cxx if non-empty

.github/workflows/test.yml
Closes #714
From looking at [this failed coverage report upload](https://github.com/pymc-devs/pytensor/actions/runs/8637210115/job/23914548773#step:6:116), the codecov action was saying that we were not using the upload token when we tried to upload the coverage reports. To be honest, I have no idea why we were ever able to upload the reports without setting the token. I've added the token as an action secret and placed it as an env variable for that step of the upload job.
=> Add codecov_token env variable to upload coverage report

pytensor/tensor/shape.py, scripts/mypy-failing.txt, tests/tensor/test_shape.py
Normalized the axes argument in ```specify_broadcastable``` using ```normalize_axis_tuple``` from numpy. Also added tensor/shape.py to mypy-failing-list as import statements cause expected failure.
=> Add support for negative axis in `specify_broadcastable`

pytensor/graph/op.py, tests/graph/test_op.py
Add `name` keyword in `Op.__call__` allowing arbitrary `Op`s to be given names
=> Add name kwarg to Op.__call__

pytensor/tensor/basic.py
A small eager optimization to avoid useless `dimshuffle`s in `expand_dims`, follwing `squeeze` logic.
=> Avoid dimshuffle if expand_dims has empty axis

pytensor/graph/basic.py, tests/graph/test_basic.py
This PR adds a `dprint` method to PyTensor nodes (i.e., Variables and Apply). 
It also allow passing keyword arguments to the debug `eval` method of Variables. This allows setting the `mode` or other useful configurations.
Both of these are quite useful during interactive debugging, where it saves having to import PyTensor.
=> Improve variable debugging methods

pytensor/compile/builders.py, pytensor/tensor/nlinalg.py, pytensor/tensor/rewriting/linalg.py, tests/compile/test_builders.py, tests/tensor/rewriting/test_linalg.py, tests/tensor/test_nlinalg.py, tests/tensor/test_slinalg.py
Adds rewrites to lift certain linear algebra ops (inv, pinv, cholesky) through "compositions" of matrices (block_diag, kron).
Kron is currently broken, so it's marked as a draft.
=> Add rewrite to lift linear algebra through certain linalg ops

pytensor/tensor/nlinalg.py, tests/tensor/test_nlinalg.py
Implement gradients for SVD
I just copied the implementation from autograd [here](https://github.com/HIPS/autograd/blob/01eacff7a4f12e6f7aebde7c4cb4c1c2633f217d/autograd/numpy/linalg.py#L192-L194). The base case `compute_uv=False`, `full_matrices=False` works and test passes.
Marked as a draft because I'm not sure how to handle multiple output gradients in a test. I'm not sure my copy/paste job is correct until I verify (there are some slight differences between our SVD and the reference I was following -- I think we return `V`, but they returned `V.conj().T`. This is a numpy vs matlab thing I think.
Even if we compute all the matrices, we only get a gradient for the singular values. Is there a way to return `[NoGrad, GradientGraph, NoGrad]`?
=> Implement gradient for SVD

pytensor/graph/basic.py, tests/graph/test_basic.py
This PR aims to integrate a helper that builds on the current [graph_input](https://github.com/pymc-devs/pytensor/blob/5e612abbc8fe11d9f1a723154521c0a68070c1a9/pytensor/graph/basic.py#L887) helper to return only variable inputs as in [pymc.pytensorf.inputvars ](https://github.com/pymc-devs/pymc/blob/5f95fc292adebbeb31b6de825b7b407042e382fd/pymc/pytensorf.py#L230).
=> Add helper `explicit_graph_inputs`

pytensor/tensor/extra_ops.py, tests/tensor/test_extra_ops.py
Added support to allow squeezing of valid non-broadcastable axis. The axis will be checked and if it is valid and non_broadcastable, we first specify it as broadcastable and then squeeze it.
=> Allow squeezing of specific non-broadcastable axis

pytensor/tensor/rewriting/math.py, tests/tensor/rewriting/test_math.py
Showed up in #740 and it was a result of a conservative fixed to #456 in #461
=> Make `local_pow_to_nested_squaring` more permissive

doc/conf.py
Closes #746.
The links were coming from the [theme's template](https://github.com/pymc-devs/pymc-sphinx-theme/blob/main/src/pymc_sphinx_theme/components/pymc_icon_links.html). I overwrote them using the [configuration file that sphinx uses](https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/header-links.html#icon-links).
=> Change github link in documentation header

pytensor/tensor/elemwise.py, tests/tensor/test_elemwise.py
Compute the outer product of two vectors.
Given two vectors `a` and `b` of length ``M`` and ``N``, respectively, the outer product [1]_ is:
```
[[a_0*b_0  a_0*b_1 ... a_0*b_{N-1} ]
[a_1*b_0    .
[ ...          .
[a_{M-1}*b_0            a_{M-1}*b_{N-1} ]]
```
=> Implement `ufunc_outer` like `add.outer` for binary `Elemwise` operations

pytensor/tensor/rewriting/blockwise.py
This is very similar in flavor to #742 
I'm a bit weary of the fact broadcastability can be redefined by our rewrites, specially after user graph manipulations, because it can mean some graphs may allow broadcasting depending on whether certain rewrites happen or not, and these should be static!
I think the proper solution will come through #408, so that we can both know something has shape 1 and is or is not allowed to broadcast
=> Remove restrictive broadcastability check in `local_blockwise_alloc`

pytensor/tensor/random/op.py, pytensor/tensor/random/utils.py, tests/tensor/random/test_op.py
This showed up in #691 and was introduced/not properly handled by #664 
We need to explicitly broadcast the new parameters to define the new size!
=> Fix broadcasting bug in vectorization of RandomVariables

pytensor/tensor/basic.py, pytensor/tensor/subtensor.py, tests/tensor/test_basic.py, tests/tensor/test_subtensor.py
=> Vectorize some cases of join and advanced subtensor

pytensor/tensor/random/basic.py, tests/tensor/random/test_basic.py
Incorporate ```Rayleigh``` distribution as square root of ```chi2```  distribution with degree of freedom 2.
As per the [reference](https://stats.libretexts.org/Bookshelves/Probability_Theory/Probability_Mathematical_Statistics_and_Stochastic_Processes_(Siegrist)/05%3A_Special_Distributions/5.14%3A_The_Rayleigh_Distribution#:~:text=Connections%20to%20the,standard%20Rayleigh%20distribution.).
=> Implement numpy-like Rayleigh distribution

pytensor/tensor/variable.py, tests/tensor/test_variable.py
Reverting back to the option first suggested in https://github.com/pymc-devs/pytensor/pull/493 and then overridden in https://github.com/pymc-devs/pytensor/pull/494
The `[ ]` is the only way that allows for the Python slice `:` syntax, and cannot be reproduced otherwise. The current helper methods of `set`/`inc` require indexes to be passed as a tuple, and so users would need to write `x.set((..., slice(None), 0), y)` if they wanted a shortcut to `pt.set_subtensor(x[..., :, 0], y)`, at which point the helper ceases to help at all. The reverted API instead looks like `x[..., :, 0].set(y)`
I still think a helper is useful because it's more discoverable and considerably more succinct than the function alternatives. If people disagree I would instead remove the method helpers altogether.
=> Change behavior of helper set/inc to act on an indexed variable directly

pytensor/scan/checkpoints.py, tests/scan/test_checkpoints.py
Found this by accident while working with Join and trying to understand the view flag (see #753)
This was completely broken for sequences, but the fix is simple enough, so I took a stab at it.
=> Fix `scan_checkpoints` with sequences

pytensor/link/numba/dispatch/basic.py, pytensor/link/numba/dispatch/elemwise.py, pytensor/link/numba/linker.py, tests/link/numba/test_tensor_basic.py
Disabling the generation of cpython wrappers should speed up compilation quite a bit.
Most of our intermediate functions are never called from python, so we don't need numba to generate wrapper code.
Note, that calling a `njit` function with `no_cpython_wrapper` directly from python (so not within a different njit function) will not work, and usually segfault.
The compilation time should further improve, if something like https://github.com/numba/numba/pull/9566 lands in numba.
=> Enable no-cpython-wrapper in numba where possible

pytensor/compile/mode.py, pytensor/link/jax/dispatch/random.py, tests/link/jax/test_random.py
Spinoff from problems found in #691 
Also closes #395
=> Fix implementation of several RandomVariables in JAX backend

pytensor/tensor/rewriting/basic.py, tests/tensor/rewriting/test_basic.py
Reported by @tomicapretto in https://github.com/pymc-devs/pymc/pull/7315#pullrequestreview-2057678377
The rewrite implicitly assumed Elemwise nodes have a single output which is not true. The reported issue involved the gradient of BetaIncGrad which includes a ScalarLoop Op with multiple outputs.
The changes get rid of the eager sink at the local node rewriter level. This was actually not working because the nested replacements referenced variables that were never part of the original fgraph and those replacements were being ignored altogether. Instead we wrap the rewrite in an in2out that will safely achieve the intended behavior.
The new test works as a regression for the bug, in that if we were to call the old rewrite (or just try to compile the graph) it would lead to the reported …
=> Fix `local_fill_sink` rewrite for multiple output Elemwise Ops

pytensor/graph/basic.py, pytensor/scalar/basic.py, tests/graph/test_basic.py
```list_of_nodes``` and ```applys_between``` do the exact same thing i.e. extract the apply node contained between the input and output vars. Replaced all instances of ```list_of_nodes ``` with ```applys_between```.
=> Remove list_of_nodes in favour of similar applys_between

pytensor/link/jax/dispatch/random.py, tests/link/jax/test_random.py
This gets around some limitations in JAX jitting system
This is required for https://github.com/pymc-devs/pymc/pull/7324 to pass
=> Inline static size inputs in JAX implementation of RandomVariables

pytensor/link/numba/dispatch/basic.py, tests/link/numba/test_basic.py
=> Fix numba AdvancedIncSubtensor1 with broadcasted values

pytensor/tensor/rewriting/basic.py, tests/tensor/rewriting/test_basic.py
The strict assumption that one of the existing variables could make the rewritten output broadcastable pattern match the original one, led to a failure in https://github.com/pymc-devs/pymc/pull/7327 (https://github.com/pymc-devs/pymc/actions/runs/9253581078/job/25453566092?pr=7327#step:7:265)
This is related to #408, the sooner we fix that the better, as this kind of problems keep popping all the time, and makes graph subject to changes in behavior depending on whether rewrites are performed or not
=> Allow fill_sink rewrite to accomodate changes in broadcastability

pytensor/compile/builders.py, pytensor/gradient.py, tests/compile/test_builders.py
PyTensor uses `DisconnectedType` and `NullType` variables to raise informative errors when users request gradients wrt to inputs that can't be computed. This is a problem for OpFromGraph which may include parallel graphs, some of which are disconnected/null and others not. We don't want to fail when the user only needs the gradient that's supported. 
There was already some special logic before, to handle cases where `NullType` and `DisconnectedType` arise from the OFG inner graph. Instead of outputing those types (which OFG cannot produce out of thin air, as they are root variables), we were outputing dummy zeros, and then masking those with the original `NullType` or `DisconnectedType` variables created in the internal call to `grad`/`Rop`. This seems reasonable if only a bit tedious. …
=> Fix gradient of `OpFromGraph` with disconnected/related outputs

pytensor/graph/rewriting/basic.py, tests/graph/rewriting/test_basic.py
The existing check was to restrictive, because it would reject a rewrite due to completely unrelated multiple clients above the replaced subgraph, as well as multiple uses of the output being replaced, neither of which make sense.
=> Do not reject PatternNodeRewriter due unrelated multiple clients

pytensor/tensor/rewriting/elemwise.py
This warning is confusing and has detracted dev work in case it is likely to not matter at all. Since we are not actively pushing the C-backend anymore seems like a good time as any to stop emitting it by default. Now it's only triggered when `optimizer_verbose` is True (by default it's not)
We still need to address the fact that the absense of a C-implementation may be leading to less fusion in unrelated backends (only Numba atm, since we don't fuse stuff for JAX, they do it themselves).
=> Do not emmit confusing warning from FusionOptimizer by default

pytensor/link/numba/dispatch/scan.py, pytensor/scan/rewriting.py, tests/scan/test_rewriting.py
We were trying to test scan rewrites and hit again the fact that the name reported by the `optimizer_verbose=True` is not the name we can use to filter out rewrites due to the arbitrary custom names given. If we make them match the function it will work, because in2out gives the name of the function to the rewrite by default.
=> Harmonize Scan rewrite and tag names

pytensor/printing.py, tests/test_printing.py
=> Add types to functions in printing.py

pytensor/tensor/nlinalg.py, tests/tensor/test_nlinalg.py
=> Fix bug in nlinalg.slogdet and expose it in linalg module

pyproject.toml, pytensor/link/c/exceptions.py
=> Bump setuptools version to >=59

environment.yml, pyproject.toml
We no longer depend on `typing-extensions`, so let's remove it.
Also, to be somewhat pedantic, `llvmlite` should be an explicit dependency under the `numba` category.
This doesn't solve any current problem, but you know me, I like to be precise about the dependencies. :joy:
=> Minor: Fix dependencies

.github/workflows/mypy.yml, .github/workflows/test.yml
Switch from using setup-miniconda to setup-micromamba in GitHub Actions for 3 current workflows
=> Switched from miniconda-setup to micromamba-setup for mypy workflow

pytensor/link/numba/dispatch/slinalg.py, tests/link/numba/test_basic.py, tests/link/numba/test_slinalg.py
The cholesky blas function returns an array with values stored in the triagonal part of the array that is zero by definition.
This is the equivalent of the scipy code here: https://github.com/scipy/scipy/blob/d5e1e03ac12fb5ad7fa4949e7ffea2137e780b15/scipy/linalg/flapack_pos_def.pyf.src#L132
fixes #814
=> fix(numba): cholesky did not set off-diag entries to zero

pytensor/link/jax/dispatch/nlinalg.py, tests/link/jax/test_nlinalg.py
#622 broke the JAX dispatch for `pt.nlinalg.kron`, because we're wrapping it in a dummy `OpFromGraph(inline=False)`. I tried just changing it to `inline=True`, but got some dynamic shape errors when the graph was converted to JAX. I think it's easier to just directly register the new OpFromGraph to `jnp.kron`, which this PR does. It also adds a test.
=> Add jax dispatch for `KroneckerProduct` `Op`

pytensor/link/pytorch/dispatch/basic.py, tests/link/pytorch/test_basic.py
=> Implement basic Alloc Ops in PyTorch

pytensor/tensor/basic.py, tests/tensor/test_basic.py
Allows `tensor.where` to work similar to `np.where` in case only a condition is given
=> Update `tensor.where` to allow for case with only condition

pytensor/__init__.py, pytensor/graph/basic.py, pytensor/tensor/random/op.py, pytensor/tensor/random/utils.py, pytensor/tensor/shape.py, pytensor/tensor/subtensor.py, pytensor/tensor/type.py, scripts/mypy-failing.txt, tests/tensor/test_subtensor.py
I started fixing type hints here and there, and then focused on the `pytensor.tensor.subtensor` module.
It was tricky, but by adding some overloads (to help mypy) and refactoring one function, I managed to clear errors in that file.
The only remaining error is the `Cannot determine type` thing for an imported dispatched function.
=> Fix typing in subtensor module

environment.yml, pyproject.toml
Due to #862 the CI started to fail
Given there is multiple work going on with GSOC that would be otherwise stalled or have to wait for #859 I suggest we temporarily upper pin scipy.
=> Upper pin scipy temporarily

pytensor/link/jax/dispatch/slinalg.py, tests/link/jax/test_slinalg.py
Added JAX backend for Eigvalsh Op.
=> Implemented JAX backend for Eigvalsh

pytensor/link/jax/dispatch/subtensor.py, tests/link/jax/test_subtensor.py
The check was failing incorrectly for cases that are supported such as constant Boolean arrays. Besides that, user may dispatch without necessarily jitting the graph. There is no reason to fail eagerly.
=> Remove conservative checks for supported Subtensors operations in JAX

pytensor/tensor/nlinalg.py, tests/tensor/test_nlinalg.py
Raise a ValueError if non square matrix (with non shapes) is passed to the Det Op
=> added check for square matrix in make_node to Det

pytensor/tensor/random/rewriting/basic.py, tests/tensor/random/rewriting/test_basic.py
By only replacing the output variable (dimshuffle, subtensor), we were leaving the second output of the lifted RV (the rng update) linked to the old node. In a normal function this RNG update is an output of the function and we want to also replace it to link to the new RV node.
Not doing this would result in "invalid random graphs", with the same RNG leading to two RVs of different sizes/shapes.
Also simplified a bit the rewrites in the first commit, now that RandomVariable always adds expand dims to the batch dimensions of the parameters
=> Replace RNG update in RV lift rewrites

pytensor/compile/function/types.py, pytensor/graph/fg.py, tests/compile/function/test_types.py, tests/graph/test_fg.py
=> Add dprint shortcut to FunctionGraph and Function

pytensor/link/pytorch/dispatch/basic.py, pytensor/link/pytorch/dispatch/elemwise.py, tests/link/pytorch/test_basic.py, tests/link/pytorch/test_elemwise.py
Add pytorch support for common CARdeuce Ops (sum, prod, all, any, ...)
=> Pytorch support for Join and Careduce Ops

doc/conf.py, doc/environment.yml, doc/extending/creating_a_numba_jax_op.rst, pytensor/link/pytorch/dispatch/__init__.py, pytensor/link/pytorch/dispatch/extra_ops.py, pytensor/tensor/extra_ops.py, tests/link/pytorch/test_extra_ops.py
This PR can be used as an example for implementing `Op`s in PyTorch
cc @ricardoV94
=> Add Pytorch support for Cum Op

pytensor/tensor/subtensor.py, tests/tensor/test_subtensor.py
Introduced in f9dfe702dac141be4f006e9bfa042be9ad64ce16
Causing PyMC CI to fail in https://github.com/pymc-devs/pymc/pull/7400
https://github.com/pymc-devs/pymc/actions/runs/9790920723/job/27033597109?pr=7400#step:7:3094
=> Fix too restrictive type assert

pytensor/link/jax/dispatch/nlinalg.py, tests/link/jax/test_extra_ops.py, tests/link/jax/test_nlinalg.py
"Omnistaging can't be disabled" was added as reason for some expected failures due to [breaking changes introduced in JAX 0.2.12 onwards](https://jax.readthedocs.io/en/latest/jep/4410-omnistaging.html). As omnistaging already became default in JAX for 4 years, more descriptive reasons are needed for the tests affected (3 in total).
=> Fix JAX implementation of Argmax

pytensor/tensor/rewriting/subtensor.py, tests/link/numba/test_subtensor.py
Follow up to #805 
Support more multidimensional advanced indexing cases by converting them to vector advanced indexing via rewrites.
We could do similar stuff to support multi-dimensional Set/IncSubtensor
=> Support more cases of advanced indexing in Numba

pytensor/tensor/random/op.py, tests/tensor/random/test_op.py
Bug left out from when we fixed shape=None != shape=()
=> Fix bug in vectorize of random variables with empty size

pytensor/scalar/basic.py, pytensor/tensor/math.py, tests/tensor/test_math.py
Added pytensor equivalent of numpy's [nan_to_num](https://numpy.org/doc/stable/reference/generated/numpy.nan_to_num.html). Also added ```isposinf``` and ```isneginf``` similar to ```isinf```.
=> Add `nan_to_num` helper

pytensor/link/pytorch/dispatch/basic.py, tests/link/pytorch/test_basic.py
- Implemented Eye Op with diagonal offset in `PyTorch`
- `torch.eye` doesn't support a diagonal offset param `k` directly.  The implementation of this offset required composing two `torch` functions.
-  Added tests for different dimensions and diagonal offset, including corner cases.
=> Implemented Eye Op in PyTorch

pytensor/tensor/rewriting/shape.py, tests/tensor/rewriting/test_shape.py
With improvements in some Op static shape, I see an increase in redundant SpecifyShape that were introduced earlier on, but become irrelevant after more clever Ops were introduced or recreated.
This PR removes useless SpecifyShape when all the specified dims are already encoded in the static shape of the input.
=> Remove useless SpecifyShape

pytensor/tensor/random/rewriting/basic.py, tests/tensor/random/rewriting/test_basic.py
We should keep the stack trace during our rewrites, so that when the Op fails to perform we can point to the moment where the node was created. We do this very patchily at the moment.
This discourse issue revolves around this very problem: https://discourse.pymc.io/t/debug-mode-in-pytensor/14348
After these changes, the traceback ends like this:
```python
File "<ipython-input-2-9b04c63d3b82>", line 7, in <module>
s = pm.HalfNormal('s', sigma=-1)
File "/home/ricardo/Documents/Projects/pymc/pymc/distributions/distribution.py", line 555, in __new__
rv_out = cls.dist(*args, **kwargs)
File "/home/ricardo/Documents/Projects/pymc/pymc/distributions/continuous.py", line 846, in dist
return super().dist([0.0, sigma], **kwargs)
File "/home/ricardo/Documents/Projects/pymc/pymc/distributions/distribut …
```
=> Keep stack trace in random_make_inplace

pytensor/tensor/basic.py, tests/tensor/test_basic.py
Showed up in some vectorized logps in https://github.com/pymc-devs/pymc-experimental/pull/353
We can always convert a vectorized MakeVector (stack of scalars) into a join (concatenate) of tensors. May just need to explicitly broadcast them first. No good reason not to do it eagerly
=> Vectorize `make_vector`

pytensor/compile/debugmode.py, pytensor/compile/function/types.py, pytensor/compile/profiling.py, pytensor/graph/destroyhandler.py, pytensor/graph/fg.py, pytensor/graph/rewriting/basic.py, pytensor/graph/rewriting/utils.py, pytensor/link/c/basic.py, pytensor/link/vm.py, pytensor/printing.py, pytensor/scan/rewriting.py, pytensor/tensor/basic.py, pytensor/tensor/random/rewriting/basic.py, pytensor/tensor/rewriting/elemwise.py, pytensor/tensor/rewriting/linalg.py, pytensor/tensor/rewriting/math.py, pytensor/tensor/rewriting/shape.py, tests/graph/test_fg.py
This is often a source of bug, because everything in the clients graph is a node with an Op, except these sneaky string labels "output". It also messes up mypy in multiple places.
The whole point of having "output" in the clients dictionary is so we know if a variable is used in multiple places (i.e., may still need to be computed even if we do a rewrite that gets rid of it as an intermediate operation). For that purpose it doesn't really matter if it's an output or used by another node. This approach allows handling these cases more easily because it looks like just another client.
We could also get rid of this dummy client, and force rewrites to check if a node is in fgraph.outputs separately but that feels more cumbersome. I understand why they added "output" as a client. I just think …
=> Replace str "output" by a dummy Op in the clients of the FunctionGraph

pytensor/tensor/elemwise.py, pytensor/tensor/math.py, pytensor/tensor/rewriting/linalg.py, pytensor/tensor/utils.py, tests/tensor/test_math.py, tests/test_rop.py
Spinoff from #888 and follow up to #731
=> Cleanup Max and Argmax

pytensor/raise_op.py, tests/test_raise_op.py
Continues @ricardoV94 s work in #739 . Solves the one test error it faces due to change in assert representation.
=> Improve string representation of Assert Ops

pytensor/configdefaults.py, pytensor/utils.py
Fixes https://github.com/pymc-devs/pytensor/pull/806#issuecomment-2218316650
=> Fix Windows build

pytensor/link/pytorch/dispatch/__init__.py, pytensor/link/pytorch/dispatch/sort.py, tests/link/pytorch/test_sort.py
* Implements `SortOp` in `PyTorch`
* Implements `ArgSortOp` in `PyTorch`
* :warning: passing `axis=None` throws an exception because `Reshape` is not yet implemented
=> Implemented Sort/Argsort Ops in PyTorch

pytensor/link/pytorch/dispatch/extra_ops.py, tests/link/pytorch/test_extra_ops.py
Implements `Repeat` and `Unique` Ops in `PyTorch`.
=> Implemented Repeat and Unique Ops in PyTorch

pytensor/link/jax/dispatch/__init__.py, pytensor/link/jax/dispatch/blas.py, pytensor/link/jax/dispatch/math.py, pytensor/link/jax/dispatch/nlinalg.py, tests/link/jax/test_blas.py, tests/link/jax/test_math.py, tests/link/jax/test_nlinalg.py
Moved math and blas `Op`s that are currently in nlinalg.py to math.py and blas.py. Split from #878.
=> Reorganized JAX link folder structure

pytensor/configdefaults.py, tests/test_config.py
Fixes the bug signaled in https://discourse.pymc.io/t/changing-the-base-compiled-in-pytensor/14764
=> Fix supplying (base_)compiledir as str

doc/tutorial/index.rst, doc/tutorial/prng.rst
Added new tutorial on PRNGs with RandomVariables per @ricardoV94 suggestions.
=> Added new tutorial on PRNGs with RandomVariables

pytensor/link/pytorch/dispatch/__init__.py, pytensor/link/pytorch/dispatch/basic.py, pytensor/link/pytorch/dispatch/shape.py, tests/link/pytorch/test_basic.py, tests/link/pytorch/test_extra_ops.py, tests/link/pytorch/test_shape.py, tests/link/pytorch/test_sort.py
Implements
- Shape
- Shape_i
- Reshape
- SpecifyShape
- Unbroadcast
- MakeVector
=> Implements shape Ops and MakeVector in PyTorch

pytensor/tensor/rewriting/linalg.py, tests/tensor/rewriting/test_linalg.py
Adds rewrite for inv(inv(x)) -> x
=> Added rewrite for matrix inv(inv(x)) -> x

doc/library/config.rst, pytensor/compile/profiling.py, pytensor/configdefaults.py, pytensor/configparser.py, pytensor/scalar/basic.py, tests/link/c/test_type.py, tests/tensor/test_blas.py, tests/test_config.py
Note that I changed the value of `in_c_key` for `cast_policy` because I assumed that it was meant to be `False`, but I could be wrong.
=> Remove more unused config options

pytensor/link/pytorch/dispatch/__init__.py, pytensor/link/pytorch/dispatch/nlinalg.py, tests/link/pytorch/test_nlinalg.py
Implemented Ops:
- SVD
- Det
- SLogDet
- Eig
- Eigh
- KroneckerProduct
- MatrixInverse
- MatrixPinv
- QRFul
=> Implemented nlinalg in PyTorch

environment-osx-arm64.yml, environment.yml
My work machine is an M2 mac with the apple silicon. Not sure if this is a machine y'all are planning on supporting, but these were the changes I needed to make to environment.yaml to get off the ground.
=> Update for m1

pytensor/link/jax/dispatch/__init__.py, pytensor/link/jax/dispatch/einsum.py, pytensor/tensor/__init__.py, pytensor/tensor/basic.py, pytensor/tensor/einsum.py, pytensor/tensor/functional.py, pytensor/tensor/rewriting/__init__.py, pytensor/tensor/rewriting/basic.py, pytensor/tensor/rewriting/blockwise.py, pytensor/tensor/rewriting/einsum.py, pytensor/tensor/rewriting/ofg.py, pytensor/tensor/rewriting/shape.py, pytensor/tensor/shape.py, tests/link/jax/test_einsum.py, tests/link/jax/test_tensor_basic.py, tests/tensor/rewriting/test_blockwise.py, tests/tensor/rewriting/test_einsum.py, tests/tensor/rewriting/test_shape.py, tests/tensor/test_basic.py, tests/tensor/test_einsum.py, tests/tensor/test_shape.py
=> Add `einsum`

CONTRIBUTING.md
Issue - #963 
This pull request addresses a minor but important typo in the contributing guidelines for the PyTensor project. By correcting this typo, we aim to improve the readability and accuracy of our documentation, making it easier for contributors to follow the guidelines.
- **Original Text:** "an PyTensor"
- **Corrected Text:** "a PyTensor"
The original text contained an incorrect article usage before the project name. The phrase "an PyTensor" has been updated to "a PyTensor" to reflect proper grammar and improve readability.
- Reviewed and ensured the corrected phrase is consistent with the rest of the documentation.
This change helps maintain the professionalism and clarity of our contributing guidelines, ensuring that contributors are not confused by incorrect grammar.
The …
=> #963 - Correct Article Usage Typo in PyTensor Contributing Guidelines Documentation

tests/test_config.py
=> Pickle error message changed

.github/workflows/pypi.yml, setup.py
Closes https://github.com/pymc-devs/pytensor/issues/285 and https://github.com/pymc-devs/pytensor/issues/360.
These require pure-python wheels which does not work if we ship a cython-version of scan, so this build does not include this extension module.
=> Add building of pyodide universal wheels

doc/tutorial/adding.rst
Removed data type examples and added basics on tensors at start
=> Removed types examples and introduced tensor

environment-osx-arm64.yml, environment.yml, pyproject.toml, pytensor/gradient.py, pytensor/graph/basic.py, pytensor/scalar/basic.py, pytensor/tensor/elemwise.py, tests/scalar/test_loop.py, tests/tensor/utils.py
=> Unpin scipy upper version

pytensor/tensor/elemwise.py, pytensor/tensor/elemwise_cgen.py, pytensor/tensor/math.py, tests/tensor/test_elemwise.py
This PR adds runtime loop re-ordering for CAReduce operations in the C-backend, to alleviate the bad performance reported in #935 
Using the new benchmark test, I confirm substantial speedup on summation along leading axis (30-110x) depending on C-contiguity or not.  A full reduction on a non C-contiguous array is also 7.5x faster than before
On the down side, there are some slowdowns when summing the last axis, but those are smaller in magnitude (2-3.3x). This is probably harder for the compiler to optimize due to the many to one location when iterating over the array (not trivially parallelizable).
The old speedup had probably to do with defining a temporary allocation variable and only writing it to the output after consuming all the reduced axis at each step. I didn't want to add a …
=> Speedup CAReduce C-implementation with loop reordering

pytensor/compile/mode.py, pytensor/link/pytorch/dispatch/__init__.py, pytensor/link/pytorch/dispatch/basic.py, pytensor/link/pytorch/dispatch/subtensor.py, tests/link/pytorch/test_basic.py, tests/link/pytorch/test_subtensor.py
Implement indexing ops in pytorch
=> Implement indexing operations in PyTorch

pyproject.toml, pytensor/compile/builders.py, pytensor/gradient.py, pytensor/graph/basic.py, pytensor/link/c/interface.py, pytensor/link/c/params_type.py, pytensor/link/c/type.py, pytensor/link/numba/dispatch/elemwise.py, pytensor/printing.py, pytensor/scalar/basic.py, pytensor/scan/basic.py, pytensor/tensor/basic.py, pytensor/tensor/einsum.py, pytensor/tensor/elemwise.py, pytensor/tensor/extra_ops.py, pytensor/tensor/functional.py, pytensor/tensor/io.py, pytensor/tensor/math.py, pytensor/tensor/utils.py
=> Enable ruff to format code in docstrings

pytensor/compile/builders.py
=> Fix typo in error message

.github/workflows/mypy.yml, .github/workflows/test.yml, pytensor/configdefaults.py
=> Do not use deprecated `find_executable`

pytensor/configparser.py, tests/test_config.py
I can't quite tell why this check was added, but it is causing `pymc_experimental` tests to fail here:  https://github.com/pymc-devs/pymc-experimental/actions/runs/11140715111/job/30960085934?pr=300#step:5:1176
which as best as I could track happens when pytest import pymc (multiple times) and this function is executed: https://github.com/pymc-devs/pymc/blob/45069a966d3e123bf98efbc4f28008e31b243df8/pymc/__init__.py#L27-L46
I don't know why PyMC has to add those specific flags, but it seems like the behavior should be supported? I also don't know what pytest is doing to trigger this error.
=> Remove error check in ConfigParser

pytensor/compile/profiling.py
=> Correct usage of file context in profiling outputs

.github/workflows/pypi.yml
=> Upgrade cibuildwheel

pytensor/tensor/rewriting/subtensor.py, tests/tensor/rewriting/test_subtensor.py
Herein I aim to convert all:
- X[0:-1:1] -> X[:-1]
- X[0:-1] -> X[:-1]
- X[:-1] -> X[:-1]
=> Canonicalize Subtensor slices

pytensor/tensor/extra_ops.py, pytensor/tensor/rewriting/shape.py, pytensor/tensor/shape.py, pytensor/tensor/subtensor.py, tests/tensor/test_shape.py
This PR cleans up the use of obscure shape utilities, removing them from Unique.infer_shape and and other places where they are not needed.
=> Remove rarely used shape utilities

pytensor/sparse/sandbox/sp.py, pytensor/tensor/basic.py, pytensor/tensor/elemwise.py, pytensor/tensor/extra_ops.py, pytensor/tensor/fft.py, pytensor/tensor/inplace.py, pytensor/tensor/math.py, pytensor/tensor/random/rewriting/jax.py, pytensor/tensor/rewriting/basic.py, pytensor/tensor/rewriting/elemwise.py, pytensor/tensor/rewriting/jax.py, pytensor/tensor/rewriting/linalg.py, pytensor/tensor/rewriting/shape.py, pytensor/tensor/variable.py, tests/link/jax/test_elemwise.py, tests/link/numba/test_elemwise.py, tests/link/pytorch/test_elemwise.py, tests/tensor/rewriting/test_elemwise.py, tests/tensor/rewriting/test_math.py, tests/tensor/test_basic.py, tests/tensor/test_blas.py, tests/tensor/test_elemwise.py, tests/tensor/test_extra_ops.py, tests/tensor/test_fft.py, tests/tensor/test_keepdims.py
Make DimShuffle less concerned about it's input static broadcastable type when dropping dims, since no behavior depends on it being specified at runtime. 
But there is no reason the input broadcastable type had to be known in advance, since no behavior of the Op changes with that information. It's true that dropping it only works when the runtime shape is of length 1, but that will naturally fail when we try to do it for different shape lengths. 
Alternatively / in addition we could plaster `specify_broadcastable` during make_node. Beyond this potential extension, I see no reason why DimShuffle should be so strict.
This fixes the bug reported in #969
=> Dimshuffle does not need input broadcastable info

pytensor/tensor/rewriting/math.py, tests/tensor/rewriting/test_math.py
This PR does some cleanup and extends reduction rewrites. Check each commit for the individual changes. Summary:
1. Remove list of ALL_REDUCE. AFAICT the `tracks` machinery already handles subclasses automatically. It did not always do it, which is probably why the list existed
2. ~~Stop defining Min as negative of Max, to later undo it and actually use Min. I think this is just some historical accident?~~ Reverted, too many things depend on this for me to tackle now: #904 
3. Generalize a chain of reductions of the same type to any CAReduce. It was previously limited only to Sum and Prod, but I can't see a good reason for it. This showed up in vectorized logps where All reductions (related to the parameter checks) were not being combined.
4. Generalize local_reduce_join to any axis and …
=> Merge consecutive reduces

pytensor/tensor/rewriting/linalg.py, tests/tensor/rewriting/test_linalg.py
Added the following rewrites :
- diag(block_diag(*sub_matrices)) -> concatenate(diag(sub_matrices)) 
- det(block_diag(*sub_matrices)) -> prod(det(sub_matrices))
- slogdet(block_diag(*sub_matrices)) -> prod(sign(a), sign(b), sign(c),...), sum(logdet(a), logdet(b), logdet(c),....)
=> Added rewrites involving block diagonal matrices

pytensor/ifelse.py, pytensor/scalar/basic.py, pytensor/tensor/basic.py, pytensor/tensor/blas.py, pytensor/tensor/math.py, pytensor/tensor/rewriting/basic.py, pytensor/tensor/rewriting/blas.py, pytensor/tensor/rewriting/math.py, pytensor/tensor/rewriting/subtensor.py, pytensor/tensor/subtensor.py, tests/tensor/test_math.py
Just a small cleanup. The need to know whether we are adding / multiplying 0, 1, or more inputs logic shows up in several places (also in our downstream packages) that I think we're better of just adding a helper
This change revealed a bug in the grad of TrueDiv that was also fixed, and I cleaned up the insane test that revealed this error (the error would still be found with the new test)
=> Simplify logic with `variadic_add` and `variadic_mul` helpers

pytensor/tensor/rewriting/linalg.py, tests/tensor/rewriting/test_linalg.py
Adds the following rewrites :
- diag(kron(a,b)) -> outer(diag(a), diag(b))
- slogdet(kron(a,b)) -> prod(sign(a), sign(b)), sum(logdet(a), logdet(b))
=> Adding rewrites involving kronecker product

pytensor/tensor/rewriting/linalg.py, tests/tensor/rewriting/test_linalg.py
Add a function to rewrite cholesky(eye) -> eye and cholesky(diag) -> sqrt(diag)
=> Adds functions to rewrite cholesky decomposition of identity and diagonal matrices

pytensor/link/pytorch/dispatch/scalar.py, tests/link/pytorch/test_elemwise.py
Related to #821 
----
📚 Documentation preview 📚: https://pytensor--1023.org.readthedocs.build/en/1023/
=> Implement Cast in PyTorch backend

.github/workflows/test.yml, pyproject.toml, pytensor/link/pytorch/dispatch/shape.py, pytensor/link/pytorch/dispatch/subtensor.py, pytensor/tensor/nlinalg.py, tests/link/jax/test_basic.py, tests/link/jax/test_einsum.py, tests/link/jax/test_extra_ops.py, tests/link/jax/test_random.py, tests/link/jax/test_scan.py, tests/link/jax/test_sparse.py, tests/link/jax/test_tensor_basic.py, tests/link/pytorch/test_basic.py, tests/tensor/rewriting/test_elemwise.py, tests/unittest_tools.py
This PR does a bunch of minor cleanups on the testing suite:
* Execute minimal rewrites in PyTorch and JAX backends (Numba already did it), so that we are sure to test the Op implementations.
*  Sometimes tests were defined with constant inputs and due to constant folding who ended up never testing the backend implementation.
* Fix incorrect configuration of pytest in pyproject.toml
* Make xfail strict (test fails if marked as xfail but actually passed)
----
📚 Documentation preview 📚: https://pytensor--1021.org.readthedocs.build/en/1021/
=> Direct tests for dispatch implementations in alternative backends

pytensor/graph/op.py, pytensor/scan/rewriting.py, pytensor/sparse/rewriting.py, pytensor/tensor/blockwise.py, pytensor/tensor/random/rewriting/basic.py, pytensor/tensor/rewriting/blas.py, pytensor/tensor/rewriting/blas_scipy.py, pytensor/tensor/rewriting/blockwise.py, pytensor/tensor/rewriting/elemwise.py, pytensor/tensor/rewriting/subtensor.py, pytensor/tensor/slinalg.py, pytensor/typed_list/rewriting.py, tests/tensor/test_blockwise.py, tests/tensor/test_slinalg.py
Reviving accidentally closed #577 
All scipy.linalg functions offer an `overwrite_a` and/or `overwrite_b` argument that can enhance performance by re-using the input memory for the outputs.  This PR implements re-writes that will set these flags to True at compile time.
These rewrites are also a nice example for the in-place docs [here](https://pytensor.readthedocs.io/en/latest/extending/inplace.html), so I'll update them with an example as a later commit to this PR.
We added a general inplace functionality to Blockwise, that automatically makes the core_op inplace. This will translate to the core_op if the Blockwise is later removed due to being useless (no batch dims actually exist).
----
📚 Documentation preview 📚: https://pytensor--1028.org.readthedocs.build/en/1028/
=> Implement destructive in-place rewrites for Cholesky and Solve Ops

pytensor/tensor/math.py, tests/tensor/test_math.py
Added support and test for median without creating a separate ```op``` for median as discussed in #53 . Hence, our implementation of median is standalone and not dependent on numpy. Also added test for it.
=> Added Support for Median

pytensor/tensor/blockwise.py, tests/tensor/test_blockwise.py
Bug surfaced in #1045. We were creating a single perform method per Blockwise Op, based on the node of which the Op was called the first time, even if the same Op was used for multiple nodes. This leads to incorrect results when the perform method depends on node info. This is valid behavior, so much that we pass `node` along to the perform method!
----
📚 Documentation preview 📚: https://pytensor--1048.org.readthedocs.build/en/1048/
=> Make blockwise perform method node dependent

pytensor/tensor/rewriting/blockwise.py, pytensor/tensor/rewriting/linalg.py, pytensor/tensor/slinalg.py, tests/link/jax/test_slinalg.py, tests/tensor/test_slinalg.py
- Add blockwise support for optimal control ops (`SolveDiscreteLyapunov`, `SolveContinuousLyapunov`, `SolveDiscreteARE`)
- Add rewrite to remove `BilinearSolveDiscreteLyapunov` in JAX mode. JAX can't call out to the necessary LAPACK functions, but we can still fall back to the direct method
- Simplify tests, adding batched cases
- Add/update typehints 
----
📚 Documentation preview 📚: https://pytensor--1045.org.readthedocs.build/en/1045/
=> Cleanup for Optimal Control Ops

pytensor/tensor/subtensor.py, tests/tensor/test_subtensor.py
Fix bug in gradient of IncSubtensor reported in https://discourse.pymc.io/t/marginalized-mixture-wont-begin-sampling-throws-assertion-error/15969/10?u=ricardov94
----
📚 Documentation preview 📚: https://pytensor--1036.org.readthedocs.build/en/1036/
=> Fix bug from too strict type check in `_sum_grad_over_bcasted_dims`

pytensor/compile/function/types.py, pytensor/gradient.py, pytensor/graph/null_type.py, pytensor/graph/op.py, pytensor/graph/type.py, pytensor/scalar/basic.py, pytensor/tensor/random/op.py, pytensor/tensor/type_other.py, tests/compile/function/test_types.py
We have way too much function overhead call. This PR tries to remove some of it.
I used this simple one Op function as a test:
```python
from pytensor.tensor.random.type import random_generator_type
rng = np.random.default_rng(123)
def numpy_normal(rng):
return rng.normal(np.array([0]), np.array([1]), size=(100,)) 
print("Direct numpy call:")
%timeit numpy_normal(rng)
rng_pt = random_generator_type()
x = pt.random.normal(rng=rng_pt, size=(100,))
fn = pytensor.function([pytensor.In(rng_pt, mutable=True)], x)
print("Fn call without trust input:")
%timeit fn(rng)
fn.trust_input = True
print("Fn call with trust input: ")
%timeit fn(rng)
fn.input_storage[0].storage[0] = rng
print("VM call bypassing Fn:")
%timeit fn.vm()
```
Note …
=> Reduce overhead of function call and deprecate rarely used utilities

tests/link/jax/test_elemwise.py
Temporary work-around for #1060 
----
📚 Documentation preview 📚: https://pytensor--1061.org.readthedocs.build/en/1061/
=> Temporarily remove heaviest param of jax test_logsumexp_benchmark

pytensor/scalar/basic.py, pytensor/scalar/loop.py, pytensor/tensor/rewriting/math.py, pytensor/tensor/variable.py, tests/scalar/test_basic.py, tests/scan/test_printing.py, tests/tensor/rewriting/test_math.py
Closes #1037 
It also refactors the two rewrites to avoid so much duplicated code
The fix revealed some subtle bugs in the C implementation of Scalar Ops with negative literal constants, that were also fixed.
----
📚 Documentation preview 📚: https://pytensor--1059.org.readthedocs.build/en/1059/
=> Fix downcasting bug in `local_[mul|div]_switch_sink` rewrite

pytensor/tensor/subtensor.py, pytensor/tensor/variable.py, tests/tensor/test_subtensor.py, tests/tensor/test_variable.py
This is a special-edge case that behaves differently than other boolean indexing. It adds a new dimension (either empty or with one entry). The logic in `make_node` and `infer_shape` don't handle this.
Small cleanup around #442. I suspect the extra logic needed in the Op (and rewrites) to accommodate this special rule aren't justified or needed (since nobody requested it until now). If someone wants to work on it, they can of course!
The PR simply raises an informative error instead of failing cryptically like before.
----
📚 Documentation preview 📚: https://pytensor--1063.org.readthedocs.build/en/1063/
=> Raise NotImplementedError for boolean scalar indexing

.github/workflows/test.yml, pytensor/link/c/cmodule.py, pytensor/tensor/blas.py, tests/link/c/test_cmodule.py
This just adds a test of the `Accelerate` framework flag to test in `blas__ldflags`. ~~I haven't written a test because it proved to be a PITA. I've tested it locally and it seems to work. The only thing that I can say is that we should run the test suite on Mac and ensure that the `blas__ldflags` should be `-framework Accelerate -rpath some_path`.~~ I written a test to mock this, but I've also added a macos-latest runner that tries to test blas, and also asserts that the blas__ldflags get set to accelerate.
----
📚 Documentation preview 📚: https://pytensor--1056.org.readthedocs.build/en/1056/
=> Add Accelerate framework `blas__ldflags` tests

pytensor/link/pytorch/dispatch/__init__.py, pytensor/link/pytorch/dispatch/blockwise.py, tests/link/pytorch/test_blockwise.py, tests/tensor/test_blockwise.py
Adds the blockwise operator for torch (using torch.vmap), and adds a test.
=> Add Pytorch implementation of Blockwise

pytensor/tensor/rewriting/basic.py, tests/tensor/rewriting/test_basic.py
The existing constant_folding makes use of `Op.do_constant_folding` to decide whether to apply itself or not, even when all inputs are constant. This is a hackish way of trying to not perform constant_folding in cases where it may lead to a sub-optimal graph (basically requiring extra copies). It is also used for rewrites to have a chance to apply themselves.
This PR adds a constant_folding helper that does not follow this logic. It is not registered in the database. It's meant for advanced users / libraries to force constant_folding whenever it it is actually possible to.
----
📚 Documentation preview 📚: https://pytensor--1068.org.readthedocs.build/en/1068/
=> Implement unconditional constant_folding rewrite

pytensor/graph/basic.py, pytensor/tensor/rewriting/math.py, tests/tensor/rewriting/test_math.py
Introduced in 4f7d7096ea98fa1285b50a9d583373b5963d425d
Apparently no test covered this condition :)
=> Fix bug in `local_div_switch_sink` rewrite

pytensor/graph/basic.py, tests/graph/test_basic.py
Implements the feature requested in https://github.com/pymc-devs/pytensor/issues/1084
----
📚 Documentation preview 📚: https://pytensor--1085.org.readthedocs.build/en/1085/
=> support `on_unused_input` for string parameter names in `eval`

pytensor/link/jax/dispatch/scalar.py, pytensor/scalar/math.py, pytensor/tensor/math.py, pytensor/tensor/rewriting/math.py, tests/link/jax/test_scalar.py, tests/tensor/rewriting/test_math.py, tests/tensor/test_math_scipy.py
Needed for https://github.com/pymc-devs/pymc-experimental/pull/389
Related to https://github.com/pymc-devs/pytensor/discussions/1038
CC @AuguB 
----
📚 Documentation preview 📚: https://pytensor--1081.org.readthedocs.build/en/1081/
=> Implement Kve Op and Kv helper

pytensor/gradient.py
Ensures that verify_grad can handle cases where an RNG is not explicitly provided
Ensures that verify_grad can handle cases where an RNG is not explicitly provided, improving the function's usability and robustness. Added a new test case, test_verify_grad_no_rng, to verify that the verify_grad function works correctly without requiring an explicit RNG (random number generator) argument.
=> Add test for 'verify_grad' without explicit RNG

pytensor/link/pytorch/dispatch/elemwise.py, tests/link/pytorch/test_elemwise.py
In the event the operator `Elemwise` is broadcasting over doesn't have a direct torch function, we can leverage `vmap` and `broadcast_tensors` to replicate the ufunc machinery. 
----
📚 Documentation preview 📚: https://pytensor--1032.org.readthedocs.build/en/1032/
=> Allow for more elemwise torch functions using `broadcast_tensor` and `vmap`

pytensor/link/pytorch/dispatch/basic.py, pytensor/link/pytorch/dispatch/blockwise.py, pytensor/link/pytorch/linker.py, pytensor/link/utils.py, tests/link/pytorch/test_basic.py, tests/link/pytorch/test_blockwise.py
The torch compiler was having an issue running pytensor graphs with subgraphs. The way pytorch / module resolution worked was causing pytorch guards to fail during creation. Torch requires the guards to be created, and for them to be correct at runtime, so not being able to make one meant things couldn't get compiled. This tries to bandaid that by putting the modules we generate onto a module, essentially giving an explicit lifecycle to that module. This means we don't need to have graph breaks. That means faster compiler times, and better compiler results.
for this code
```py
import torch._dynamo as dynamo
from pytensor.configdefaults import config
from pytensor.compile.builders import OpFromGraph
from pytensor.compile.function import function
from pytensor.tensor.type …
```
=> Track generated functions for torch compile

pytensor/link/pytorch/dispatch/elemwise.py, pytensor/link/pytorch/dispatch/scalar.py, tests/link/pytorch/test_basic.py
I was goofing around with pymc using the pytorch backend. I implemented a beta binomial model and had an issue when supporting some scipy methods, and was missing softplus. I wrote some small shims. Let me know your thoughts on the importlib stuff.
----
📚 Documentation preview 📚: https://pytensor--1066.org.readthedocs.build/en/1066/
=> Torch dispatch for scipy-like functions and Softplus

doc/library/tensor/random/index.rst, doc/tutorial/examples.rst, doc/tutorial/prng.rst
----
📚 Documentation preview 📚: https://pytensor--1091.org.readthedocs.build/en/1091/
=> Cross link across random variable docs

pytensor/tensor/rewriting/subtensor.py, pytensor/tensor/subtensor.py, tests/link/numba/test_subtensor.py
Follow up to #818
It's simple to support multidimensional boolean set_subtensor. The corresponding integer indexing would be slightly trickier because it requires reshaping y as well.
Although there are still cases that are not covered outside of object mode (np.newaxis, non-contiguous adv index, broadcasted integer indexing, mixed boolean/integer indexing) I think it's fine to close #772. Efforts can be directed on a per-need basis. Numpy indexing is just too wild :)
----
📚 Documentation preview 📚: https://pytensor--1108.org.readthedocs.build/en/1108/
=> Support multidimensional boolean set/inc_subtensor in Numba via rewrite

pytensor/compile/function/types.py, pytensor/link/basic.py, pytensor/link/jax/linker.py, pytensor/link/numba/linker.py, pytensor/link/pytorch/linker.py, tests/link/jax/test_basic.py, tests/link/numba/test_basic.py, tests/link/pytorch/test_basic.py, tests/link/pytorch/test_elemwise.py
This reduces the overhead on the benchmarked numba function from ~10us to 2.5us on my machine, with trust_input=True
It will hopefully go further down when we remove deprecated function stuff like output_subset and dict returns
----
📚 Documentation preview 📚: https://pytensor--1101.org.readthedocs.build/en/1101/
=> Reduce jitted function overhead

pytensor/link/numba/dispatch/__init__.py, pytensor/link/numba/dispatch/blockwise.py, pytensor/link/numba/dispatch/random.py, pytensor/tensor/blockwise.py, pytensor/tensor/random/rewriting/numba.py, pytensor/tensor/rewriting/__init__.py, pytensor/tensor/rewriting/numba.py, tests/link/numba/test_basic.py, tests/link/numba/test_blockwise.py, tests/tensor/test_blockwise.py
It uses the machinery developed for RVs and Elemwise. The hard part has to do with multiple number of inputs and numba fussiness.
It also improves Blockwise shape inference based on the infer_shape of the core ops
The small cholesky benchmark I added here test runs 10x faster after this PR on my local machine.
=> Add Numba implementation of Blockwise

pytensor/__init__.py
----
📚 Documentation preview 📚: https://pytensor--1113.org.readthedocs.build/en/1113/
=> Make OpFromGraph available at root scope

pytensor/link/jax/dispatch/extra_ops.py, pytensor/tensor/__init__.py, pytensor/tensor/interpolate.py, tests/link/jax/test_extra_ops.py, tests/tensor/test_interpolate.py
Adds a new file, `interpolation.py`. Objective is to match a useful subset of `scipy.interpolate`. So far I have 1d interpolation with different strategies. Example:
```py
from pytensor.tensor.interpolate import interpolate1d
import matplotlib.pyplot as plt
x = np.linspace(-2, 6, 10)
y = np.sin(x)
f_linear = interpolate1d(x, y, method='linear')
f_nearest = interpolate1d(x, y, method='nearest')
f_first = interpolate1d(x, y, method='first')
f_last = interpolate1d(x, y, method='last')
f_mean = interpolate1d(x, y, method='mean')
x_hat = pt.dvector('x_hat')
ops = [f_linear, f_nearest, f_first, f_last, f_mean]
MODE = 'FAST_RUN'
funcs = [
pytensor.function([x_hat], op(x_hat), mode=MODE) for op in ops
]
inputs = np.linspace(-2.5, 6.5, 1000)
labels = ['linear', 'nearest', …
```
=> Pytensor-native interpolation functions 

pytensor/tensor/rewriting/subtensor.py
Closes #1132
The rewrite is not supposed to apply in the case behind the described bug. It was not accounting for uint integer indices, only signed ones :)
Separately but importantly, to run in pure Numba mode in this model we would need to address #1138
=> More robust check for multiple integer indices in numba ravel_multidimensional_idx rewrites

pytensor/link/numba/dispatch/elemwise.py, tests/link/numba/test_basic.py, tests/link/numba/test_elemwise.py
Closes #1130
----
📚 Documentation preview 📚: https://pytensor--1137.org.readthedocs.build/en/1137/
=> Fix dispatch of Elemwised ScalarLoop in Numba backend

doc/extending/creating_a_numba_jax_op.rst, pytensor/link/numba/dispatch/basic.py, pytensor/link/numba/dispatch/blockwise.py, pytensor/link/numba/dispatch/elemwise.py, pytensor/link/numba/dispatch/extra_ops.py, pytensor/link/numba/dispatch/scalar.py, tests/link/numba/test_basic.py, tests/link/numba/test_scalar.py
Closes #1145 
----
📚 Documentation preview 📚: https://pytensor--1147.org.readthedocs.build/en/1147/
=> Use more conservative fastmath flags in numba backend

pytensor/__init__.py, pytensor/gradient.py, pytensor/link/jax/dispatch/tensor_basic.py, pytensor/scan/basic.py, pytensor/scan/rewriting.py, pytensor/sparse/basic.py, pytensor/tensor/basic.py, pytensor/tensor/conv/abstract_conv.py, pytensor/tensor/extra_ops.py, pytensor/tensor/rewriting/basic.py, pytensor/tensor/rewriting/elemwise.py, pytensor/tensor/rewriting/math.py, pytensor/tensor/rewriting/shape.py, pytensor/tensor/rewriting/subtensor.py, pytensor/tensor/shape.py, pytensor/tensor/slinalg.py, pytensor/tensor/subtensor.py, pytensor/tensor/variable.py, tests/tensor/rewriting/test_math.py, tests/tensor/test_basic.py, tests/tensor/test_blockwise.py, tests/tensor/test_elemwise.py, tests/tensor/test_slinalg.py
In PyTensor we have tho following similar utilities
1. `pytensor.get_underlying_scalar_constant`
1. `pytensor.tensor.basic.get_underlying_scalar_constant_value`
1. `pytensor.tensor.basic.get_scalar_constant_value`
1. `pytensor.tensor.basic.extract_constant`
1. `pytensor.tensor.rewriting.math.get_constant`
This PR removes and deprecates all except:
1. `pytensor.tensor.basic.get_underlying_scalar_constant_value`
1. `pytensor.tensor.basic.get_scalar_constant_value`
The reason for this distinction, is that the core utility, `get_underlying_scalar_constant_value` actually works for non-scalar inputs, if it can find a single scalar value underlies a potential n-dimensional tensor (say as in pt.zeros(5, 3, 2)). This is powerful, but can lead to subtle bugs when the caller forgets about it. This …
=> Deprecate redundant utilities for extracting constants

pytensor/compile/compilelock.py, pytensor/configdefaults.py, pytensor/configparser.py, pytensor/d3viz/formatting.py, pytensor/graph/rewriting/basic.py, pytensor/link/c/cmodule.py, pytensor/link/vm.py, pytensor/printing.py, pytensor/scan/op.py, pytensor/tensor/blas.py, pytensor/tensor/blas_scipy.py, pytensor/tensor/rewriting/blas_scipy.py, tests/d3viz/test_d3viz.py, tests/d3viz/test_formatting.py, tests/scan/test_printing.py, tests/tensor/test_blas_scipy.py, tests/test_printing.py
Smaller scope changes from #1161 
Before:
```
1.2942 root       pytensor                                
0.9677 project    pytensor.scalar                         
0.7629 project    pytensor.scalar.math                    
0.5800 dependency scipy.stats                             
0.4957 transitive scipy.stats._stats_py                    from scipy.stats
0.2706 transitive scipy.stats.distributions                from scipy.stats._stats_py
0.2090 transitive scipy.stats._continuous_distns           from scipy.stats.distributions
0.2042 project    pytensor.scalar.basic                   
0.1879 project    pytensor.printing                       
0.1587 dependency scipy.special                           
0.1301 project    pytensor.compile                        
0.1294 project …
```
=> Speedup pytensor import

doc/install.rst
Change spelling from `conda-force` to `conda-forge`
----
📚 Documentation preview 📚: https://pytensor--1173.org.readthedocs.build/en/1173/
=> Fix typo in installation instructions for conda-forge

pytensor/tensor/rewriting/math.py, tests/tensor/rewriting/test_math.py
Small rewrite that simplifies powers of base 1, since `1 ** x = 1` for any x.
=> Add rewrite for `1 ** x = 1`

pytensor/graph/rewriting/db.py, tests/graph/rewriting/test_db.py
----
📚 Documentation preview 📚: https://pytensor--1119.org.readthedocs.build/en/1119/
=> Add overwrite_existing flag

doc/library/compile/mode.rst, doc/troubleshooting.rst, pytensor/link/c/cmodule.py, pytensor/tensor/blas_headers.py
It replaces the old eager warning that does not actually apply by a lazy yet more informative and actionable warning.
This however means users won't notice something is wrong with their installation until PyTensor actually accesses the `config.blas__ldflags` to decide on some behavior. 
These flags are accessed to either not trigger the introduction of more efficient COps (CGEMv,  sparse Usmm, ...), or to use the Python or C implementation for Ops that have both (Dot22, BatchedDot, ...). 
**The new warning will happen only when a function is compiled that triggers those code-paths.**
***
*Technically the old warning was wrong:*
The specific warning message was about Ops that might use the alternative blas_headers, which rely on the Numpy C-API.
However, regular PyTensor user has not used …
=> Make BLAS flags check lazy and more actionable

pytensor/graph/rewriting/__init__.py, pytensor/tensor/math.py, pytensor/tensor/rewriting/math.py, tests/link/jax/test_elemwise.py, tests/link/jax/test_tensor_basic.py, tests/link/numba/test_elemwise.py, tests/link/numba/test_tensor_basic.py, tests/tensor/rewriting/test_math.py, tests/tensor/test_basic.py, tests/tensor/test_elemwise.py
Dot is basically a fused broadcasted multiplication and reduction. When we have cases that correspond just to multiplication there is no advantage of using Dot, specially in vectorized graphs where we'll have Blockwised versions of the Dot.
This PR adds a rewrite for these cases.
Initially I was rewritting the non-blockwise versions as well, but those interfere with the BLAS pipeline. Testing locally BLAS for the outer product is not always faster (depends on the size), but it's generally faster for when doing the rank1 matrix update, so I don't want to mess with that for now. 
I think we should introduce BLAS in those cases only when doing an update, not when doing the outer product alone. The rewrite is easy to toggle to allow addressing the non-blockwised version.
----
📚 Documentation …
=> Rewrite batched dots that do not reduce as multiplication

doc/core_development_guide.rst, doc/extending/creating_a_c_op.rst, doc/extending/creating_an_op.rst, doc/extending/inplace.rst, doc/extending/other_ops.rst, doc/library/tensor/random/index.rst, doc/tutorial/examples.rst
Fixes a bunch of broken references, mostly due to capitalization
----
📚 Documentation preview 📚: https://pytensor--1180.org.readthedocs.build/en/1180/
=> Fix broken docs references

pytensor/link/numba/dispatch/basic.py, pytensor/link/numba/dispatch/elemwise.py, tests/link/numba/test_elemwise.py
Did not see any change in performance running the existing benchmark tests on my machine
The `__mm_cheap` option was moved elsewhere in https://github.com/numba/numba/commit/a5e2195aac1906b5c8ebae95b37f4398bb829004
If anybody sees differences in performance it seems like the new internal API is controlled by setting `_loopvect` and `_opt_level` private attributes, so we could patch those, depending on the installed numba version (not very keen on this)
=> Fix numba 0.61 compatibility

pytensor/tensor/einsum.py, tests/tensor/test_einsum.py
A shortcut in the numpy implementation of einsum_path when there's nothing to optimize, creates a default path that can combine more than 2 operands. Our implementation only works with 2 or 1 operand operations at each step.
https://github.com/numpy/numpy/blob/cc5851e654bfd82a23f2758be4bd224be84fc1c3/numpy/_core/einsumfunc.py#L945-L951
Closes #1184
----
📚 Documentation preview 📚: https://pytensor--1185.org.readthedocs.build/en/1185/
=> Fix bug einsum

pytensor/link/pytorch/dispatch/basic.py, pytensor/link/pytorch/dispatch/scalar.py, pytensor/link/pytorch/dispatch/shape.py, pytensor/link/pytorch/dispatch/subtensor.py, pytensor/link/pytorch/linker.py, tests/link/pytorch/test_basic.py
When we have static inputs, inlining helps torch not breaking the graph. 
Related to #1110 
----
📚 Documentation preview 📚: https://pytensor--1118.org.readthedocs.build/en/1118/
=> PyTorch inline constants in dispatch to avoid graph breaks

pytensor/link/vm.py, pytensor/tensor/extra_ops.py, tests/tensor/test_extra_ops.py
Nobody asked for it, and nobody probably ever needed it (it exists since 2012), but it was a fun challenge.
Also cleaned up a bit the implementation by not allowing negative axis on the Op itself like we do in other cases (the helper repeat handles the conversion to positive axis)
doctest fails due to an unrelated print that should be solved by #1193 
----
📚 Documentation preview 📚: https://pytensor--1192.org.readthedocs.build/en/1192/
=> Implement gradient for vector repetitions

pytensor/scalar/basic.py, pytensor/scalar/math.py, pytensor/tensor/inplace.py, pytensor/tensor/math.py, pytensor/tensor/xlogx.py, tests/tensor/test_math_scipy.py
Some cleanup of unused code in scalar/math.py. 
Also speedup a bit the perform method by avoiding allocating intermediate variables and attribute acces for a helper function
----
📚 Documentation preview 📚: https://pytensor--1169.org.readthedocs.build/en/1169/
=> Speedup scalar Op python implementations

pytensor/graph/rewriting/basic.py, pytensor/tensor/elemwise.py, pytensor/tensor/rewriting/shape.py, pytensor/tensor/shape.py, pytensor/tensor/slinalg.py, tests/tensor/rewriting/test_basic.py, tests/tensor/rewriting/test_elemwise.py, tests/tensor/rewriting/test_shape.py, tests/tensor/test_shape.py
We canonicalize so that reshape is only used for the behavior that is unique to it (mixing dimensions). Expand_dims and squeeze-like behavior are canonicalized into the respective forms of DimShuffle. This allows other rewrites that know how to reason about these (but not reshape, which is too flexible), such as in the following graph:
```python
x = pt.vector("x", shape=(9,))
out = pt.repeat(x[None], 12, axis=0)
pytensor.function([x], out).dprint(print_type=True)   
```
Which before this PR generated this graph:
```
```
And now simplifies:
```
```
Or a naive broadcast + elemwise comparison:
```python
x = pt.vector("x", shape=(3,))
y = pt.vector("y", shape=(9,))
out = x[None, :].repeat(9, axis=0) <= …
```
=> Rewrite reshapes that only expand or squeeze dims

pytensor/tensor/math.py, tests/tensor/test_math.py
This eagerly simplifies the graph in cases where tensordot is just a fancy dot (potentially with transposes) 
Closes #1201 
----
📚 Documentation preview 📚: https://pytensor--1202.org.readthedocs.build/en/1202/
=> Only do reshapes in `tensordot` when needed

pytensor/link/numba/dispatch/_LAPACK.py, pytensor/link/numba/dispatch/basic.py, pytensor/link/numba/dispatch/slinalg.py, pytensor/tensor/slinalg.py, tests/link/numba/test_nlinalg.py, tests/link/numba/test_slinalg.py, tests/tensor/test_slinalg.py
Goal of this PR is to give numba mode full coverage of `scipy.linalg.solve` options. We currently only support `assume_a = "gen"`. If users select a different solver, they get incorrect results (see #422 ). This PR should fix that bug, plus add:
We get the `lu_factor` and `lu_solve` Ops kind of "for free" because I'm adding overloads for `dgetrs` and `dgetrf`. We just have to write the Ops and do the JAX dispatch. JVP for `lu_factor` is [here](https://github.com/jax-ml/jax/blob/494c15733c5b600f64c3128978c143a82537a830/jax/_src/lax/linalg.py#L1557).  Help wanted. I might decide that these Ops are out of scope for this PR and open another one.
----
📚 Documentation preview 📚: https://pytensor--1146.org.readthedocs.build/en/1146/
=> Add LAPACK overloads for all variants of solve in Numba backend 

pytensor/link/numba/dispatch/random.py, pytensor/tensor/random/basic.py, tests/link/numba/test_random.py
Also changes the python implementation to use numpy instead of scipy. The overhead doesn't make sense for this trivial RV.
Long term we should replace these by OpFromGraph: #1221 
----
📚 Documentation preview 📚: https://pytensor--1223.org.readthedocs.build/en/1223/
=> Implement multinomial and inverse gamma in numba backend

pytensor/tensor/blockwise.py, tests/link/numba/test_blockwise.py, tests/link/numba/test_random.py
To implement Blockwise and RandomVariables in numba we use an `OpWithCoreShape` OpFromGraph subclass, that extends the original node with a core_shape input. This approach would fail whenever the original node had repeated inputs, as OpFromGraph raises by default when that's the case.
For now I think simply allowing OpFromGraph to ignore those disconnected inputs should work fine. We can revisit later and use a `node.clone_with_new_inputs` or whatever is called to mask the fact the inputs are identical. I have a 90% confidence this won't be needed so I'm trying the simple approach until reality proves it wrong.
----
📚 Documentation preview 📚: https://pytensor--1222.org.readthedocs.build/en/1222/
=> Fix Blockwise and RandomVariable in Numba with repeated arguments

pytensor/compile/function/pfunc.py, pytensor/compile/function/types.py, pytensor/compile/nanguardmode.py, pytensor/scalar/basic.py, pytensor/scalar/loop.py, pytensor/scalar/math.py, pytensor/scan/basic.py, pytensor/tensor/basic.py, pytensor/tensor/conv/abstract_conv.py, pytensor/tensor/math.py, pytensor/tensor/rewriting/blas.py, pytensor/tensor/rewriting/math.py, pytensor/tensor/rewriting/special.py, pytensor/tensor/rewriting/subtensor.py, pytensor/tensor/variable.py, tests/tensor/test_basic.py, tests/tensor/test_type.py
Notably changes the behavior of `__bool__` to always raise. Before there was a hack based on whether a variable had been compared to something before.
This should avoid surprising behavior such as:
```python
x = pt.zeros(())
if x:
print("Variable is nonzero!")  # Always triggered
else:
print("Variable is zero")  # Never triggered
```
After this PR it raises
```
TypeError: TensorVariable cannot be converted to Python boolean. Call `.astype(bool)` for the symbolic equivalent.
```
The correct behavior as per the API standard is to raise in these cases: https://data-apis.org/array-api/latest/design_topics/lazy_eager.html
There is still surprising behavior with (in)equality checks, but we can't do anything about those as they are needed for Python hashing behavior. …
=> Raise explicitly on Python methods that are incompatible with lazy variables

.github/workflows/test.yml, pyproject.toml, tests/link/jax/test_tensor_basic.py
----
📚 Documentation preview 📚: https://pytensor--1199.org.readthedocs.build/en/1199/
=> Support Python 3.13

pytensor/link/numba/dispatch/slinalg.py, tests/link/numba/test_slinalg.py
Issue #1233 found a bug in the numba mode of `solve_triangular`. Basically, we can't get around copying the incoming matrices if they're not already F-contiguous. Also adds a regression test for this bug.
----
📚 Documentation preview 📚: https://pytensor--1235.org.readthedocs.build/en/1235/
=> Fix solve_triangular output when overwrite_b=True

pytensor/printing.py, pytensor/tensor/type.py
I added an extra argument `print_shape` to `debugprint` and `_debugprint`, which, when True, prints the shape of every `Variable` in the graph.
```python
x = pt.matrix("x", shape=(None, 3))
y = pt.broadcast_to(x * 5, (5, 7, 3))
y.dprint(print_shape = True)
```
Additionally, I also simplified the `__str__` function logic of `class TensorType` to easily find the formatted shape. 
```python
formatted_shape = str(shape).replace("None", "?")
```
----
📚 Documentation preview 📚: https://pytensor--1236.org.readthedocs.build/en/1236/
=> Add `print_shape` and `print_memory_map` option to `debugprint`

pytensor/tensor/rewriting/shape.py, tests/tensor/rewriting/test_shape.py
Found out when trying to bump the PyTensor dependency: https://github.com/pymc-devs/pymc/pull/7688 
----
📚 Documentation preview 📚: https://pytensor--1242.org.readthedocs.build/en/1242/
=> Fix bug in `local_reshape_to_dimshuffle`

pytensor/link/numba/dispatch/subtensor.py, tests/link/numba/test_subtensor.py
This shows up in some imputation models in PyMC. Numba supports this case, so no reason to block it.
----
📚 Documentation preview 📚: https://pytensor--1243.org.readthedocs.build/en/1243/
=> Don't use numba objectmode with vector boolean `inc_subtensor`

pytensor/link/jax/dispatch/elemwise.py, pytensor/link/numba/dispatch/elemwise.py, pytensor/link/pytorch/dispatch/elemwise.py, pytensor/tensor/c_code/dimshuffle.c, pytensor/tensor/elemwise.py, pytensor/tensor/shape.py, tests/link/numba/test_elemwise.py, tests/tensor/test_elemwise.py, tests/tensor/test_extra_ops.py, tests/tensor/test_shape.py
Remove the unused inplace option, less branching is always helpful
~~Implementation based on `as_strided` that mimicks the old (and now current again) C-backend approach. This is debatable since the Python implementation has historically been there more for readability than performance. However it's useful for fast compiling graphs not to suck?~~
`as_strided` is actually insanely slow in python, so I'm back to transpose+reshape. The removal of some checks and unnecessary `asarray` calls provide a small speedup, although this is obviously not critical.
Use `as_strided` which simplifies the implementation by a ton with two benefits:
1. Much faster compilation / caching. The new benchmark runs on 1.6s (includes many runs) after caching, vs 4.6s. When checking a simple function directly I saw …
=> Speedup DimShuffle and Reshape in C and Numba backends

pytensor/tensor/random/basic.py, tests/tensor/random/test_basic.py
So it's easier to integrate from PyMC and matches numpy API when using `RandomStream`
----
📚 Documentation preview 📚: https://pytensor--1252.org.readthedocs.build/en/1252/
=> Handle MvNormal method in Op call

pytensor/compile/function/types.py, pytensor/compile/mode.py, pytensor/link/jax/dispatch/scan.py, pytensor/link/numba/dispatch/basic.py, pytensor/link/numba/dispatch/scan.py, pytensor/link/numba/dispatch/subtensor.py, pytensor/link/pytorch/dispatch/basic.py, pytensor/scan/op.py, pytensor/sparse/rewriting.py, tests/link/numba/test_basic.py
JAX needs no special handling because it excludes inplace rewrites.
----
📚 Documentation preview 📚: https://pytensor--1247.org.readthedocs.build/en/1247/
=> Fix inner graph inplace rewrites in Numba / PyTorch backends

pytensor/tensor/elemwise.py, pytensor/tensor/math.py
Improve elemwise math function docstrings; remove generic docstring from being appended.
----
📚 Documentation preview 📚: https://pytensor--1255.org.readthedocs.build/en/1255/
=> Improve elemwise docstrings

pytensor/link/numba/dispatch/subtensor.py, pytensor/tensor/rewriting/subtensor.py, pytensor/tensor/subtensor.py, scripts/mypy-failing.txt, scripts/run_mypy.py, tests/link/jax/test_pad.py, tests/link/numba/test_subtensor.py, tests/tensor/test_subtensor.py
Support more cases of multi-dimensional advanced indexing and updating in Numba
Extends pre-existing rewrite to ravel multidimensional integer indices, to handle multiple inputs (if no broadcasting is needed) and to place them consecutively if they were not. It also extends it to Set/IncSubtensor as long as y is not broadcasted and advanced indices are consecutive. 
The following cases should now be supported without object mode:
* Advanced integer indexing (not mixed with basic or boolean indexing) that do not require broadcasting of indices
* Consecutive advanced integer indexing updating (set/inc) (not mixed with basic or boolean indexing) that do not require broadcasting of indices or y.
Also fixes bug in infer_shape of AdvancedIndexing with slices (which were mistakenly treated as …
=> Support more cases of numba advanced indexing

pytensor/link/jax/dispatch/slinalg.py, pytensor/link/numba/dispatch/slinalg.py, pytensor/tensor/slinalg.py, tests/link/jax/test_slinalg.py, tests/link/numba/test_slinalg.py, tests/tensor/test_slinalg.py
Adds a `transposed` argument to `pt.linalg.solve`. The signature now matches `scipy.linalg.solve` 1-to-1. It also fixes gradients for `pt.linalg.solve_triangular` when `trans` is either `"T"` or `"C"` (though we don't really support complex inputs anyway)
It also adds a bunch of tests for the two implicated solve Ops.
----
📚 Documentation preview 📚: https://pytensor--1231.org.readthedocs.build/en/1231/
=> Allow `transposed` argument in `linalg.solve`

pytensor/tensor/c_code/dimshuffle.c, tests/tensor/test_elemwise.py
Our changes in #1226 led to failures in the PyMC test suited due to our BLAS implementation (at least GEMV) not handling 0 strides well: #1262 
The value of the strides for length-1 dimensions is actually arbitrary. In that PR I set it to zero, in this one I set it to itemsize of the array. 1 would be odd? and I don't want to do a silly second loop to give the same sort of strides that `np.expand_dims` or `reshape` do.
----
📚 Documentation preview 📚: https://pytensor--1267.org.readthedocs.build/en/1267/
=> Do not introduce 0 strides for broadcastable dimensions in DimShuffle

pytensor/tensor/variable.py, tests/tensor/test_variable.py
Added np.ndarray as a typecheck along tuple and list for dimshuffle so tensor.transpose would accept numpy inputs. 
----
📚 Documentation preview 📚: https://pytensor--1258.org.readthedocs.build/en/1258/
=> Allow passing numpy arrays to transpose

pytensor/tensor/random/basic.py
This reduces pytensor import time from average 0.9 to 0.45s on my machine
Before:
```
python -m benchmark_imports pytensor
0.8324 root       pytensor                                
0.3692 project    pytensor.tensor.random                  
0.3689 project    pytensor.tensor.random.rewriting        
0.3649 project    pytensor.tensor.random.rewriting.jax    
0.3640 project    pytensor.tensor.random.basic            
0.3616 dependency scipy.stats                             
0.2857 transitive scipy.stats._stats_py                    from scipy.stats
0.2108 project    pytensor.scalar                         
0.1785 project    pytensor.scalar.math                    
0.1615 dependency scipy.special                           
0.1484 transitive scipy.stats.distributions                from …
```
=> Speedup pytensor import time with lazy import of scipy.stats

pytensor/tensor/blas.py, pytensor/tensor/math.py, pytensor/tensor/rewriting/blas.py, pytensor/tensor/utils.py, tests/tensor/test_blas.py
This should be merged after #1194 to avoid conflicts.
Closes #608
----
📚 Documentation preview 📚: https://pytensor--1215.org.readthedocs.build/en/1215/
=> Deprecate batched blas stuff

pytensor/tensor/basic.py, tests/tensor/test_basic.py
Modified `atleast_Nd` to accept only one positional argument. Also modified the tests to account for this change.
After the changes, in `atleast_Nd(x, 1)`, `x` is interpreted as an array and 1 is interpreted as the dimension. This change is reflected in the tests too.
----
📚 Documentation preview 📚: https://pytensor--1291.org.readthedocs.build/en/1291/
=> Modify atleast_Nd to accept only one positional argument

pytensor/compile/mode.py, pytensor/configdefaults.py, pytensor/link/jax/dispatch/scan.py, pytensor/link/numba/dispatch/scan.py, pytensor/scan/op.py, pytensor/scan/rewriting.py, pytensor/scan/utils.py, pytensor/tensor/basic.py, pytensor/tensor/subtensor.py, tests/link/numba/test_scan.py, tests/scan/test_printing.py, tests/scan/test_rewriting.py, tests/tensor/test_subtensor.py
This PR does a bunch of small optimizations for the Scan, mostly in the Numba backend, but to a lesser extent also in the C and  JAX backends.
Tweaks:
0. Fix failure in trimming number of steps  in Scan when the new n_step would be a constant integer. The isinstance(x, int) does not work for `np.integer`.
1. Do not try to reduce buffer size just to save the space occupied by the initial values. Scan is always created with a buffer size for the recurring inputs with a size of taps + steps. The scan returned to the user slices away the taps, so the user doesn't see the initial values there. When the user wants the whole returned trace (instead of say only the last state) AND no gradient is requested (the gradient makes use of the initial taps in the trace), the Scan save memory would trim …
=> Speedup Scan in different backends

pytensor/link/jax/dispatch/slinalg.py, pytensor/link/numba/dispatch/slinalg.py, pytensor/tensor/basic.py, pytensor/tensor/slinalg.py, tests/tensor/test_slinalg.py
Accompanying notebook: https://gist.github.com/ricardoV94/005fb4b48d274bcf383a3eb5456462d3
Also fixes #1271 
We want to implement solve_banded and solveh_banded, which allows working directly with the sparse representation of the matrix which is much more practical. Will do that in a follow up PR as it requires more work.
Would also be nice to implement the tridiagonal / banded solvers for numba.
----
📚 Documentation preview 📚: https://pytensor--1273.org.readthedocs.build/en/1273/
=> Allow more specialized solve routines

pytensor/link/numba/dispatch/slinalg.py, tests/link/numba/test_basic.py, tests/link/numba/test_slinalg.py
1. Numba's `_copy_to_fortran_order` does not seem to do the right thing with vectors and doesn't always copy them. 
2. Most methods were forgetting inputs still need to be F-contiguous even if they don't need to be copied.
PR did some tricks to avoid copying C-contiguous arrays when not needed. 
Proof of the `_copy_to_fortran_order` thing:
```python
import numba
from numba.np.linalg import _copy_to_fortran_order
@numba.njit
def foo(x):
out = _copy_to_fortran_order(x)
return out
x = np.zeros((10, 1))
y = foo(x)
y[0] = np.pi
assert (x == 0).all()
x = np.zeros((10))
y = foo(x)
y[0] = np.pi
assert (x == 0).all()  # AssertionError
```
=> Fix inplace/layout bugs in Numba lapack routines

pytensor/link/numba/dispatch/basic.py, pytensor/tensor/basic.py, tests/link/numba/test_basic.py
Added a numba overload in `Nonzero` by adding the `@nb.njit` decorator as `np.nonzero` is supported by `numba` already.
----
📚 Documentation preview 📚: https://pytensor--1289.org.readthedocs.build/en/1289/
=> Add numba overload for Nonzero

pytensor/tensor/math.py, tests/tensor/test_math_scipy.py
I added an additional function `kn` in the `pytensor/tensor/math.py` file which just calls `kv` function under the hood. This is to provide functionality similar to that offered by `scipy.special.kn`.
`scipy` has two functions for computing modified Bessel functions of the second kind: `scipy.special.kv` (which works for functions of real order) and `scipy.special.kn` (which works for functions of integer order). pytensor has a function `pytensor.tensor.kv` which is similar to scipy, but it lacks a `kn` counterpart. Thus I added an extra helper function `kn` which just calls `kv` under the hood, as `kv` also works for integers.
----
📚 Documentation preview 📚: https://pytensor--1313.org.readthedocs.build/en/1313/
=> Add scipy-like `kn` helper

pytensor/link/jax/dispatch/random.py, tests/link/jax/test_random.py
Move the jax rng splits from the `jax_sample_fn` of each RandomVariable dispatch to `jax_funcify_RandomVariable`
----
📚 Documentation preview 📚: https://pytensor--1315.org.readthedocs.build/en/1315/
=> Simplify dispatch of JAX random variables by handling rng split automatically

pytensor/graph/op.py
Added an error message ```f"grad not implemented for Op {self}"``` in the `NotImplementedError` for the grad function of  `Op` class.
This change helps in finding the Op which has an unimplemented grad when many Ops are strung together.
----
📚 Documentation preview 📚: https://pytensor--1314.org.readthedocs.build/en/1314/
=> Include Op in message when raising `NotImplementedError` from grad

pytensor/tensor/basic.py, tests/tensor/test_basic.py
Modified `arange` such that in scenarios where we are able to infer the shape from the arguments i.e the arguments are constant,  `type.shape` is updated accordingly.
For example : 
```python
print(pt.arange(1,10,1).type.shape) #Returns (9, ). Earlier used to return (None, )
``` 
Tests are also added to test the new addition.
----
📚 Documentation preview 📚: https://pytensor--1302.org.readthedocs.build/en/1302/
=> Modify `arange` to directly determine the shape from the arguments if possible

pytensor/tensor/nlinalg.py, tests/tensor/test_nlinalg.py
Implement the support for gradient in the QR decomposition. It is only defined when R is a square matrix.
----
📚 Documentation preview 📚: https://pytensor--1303.org.readthedocs.build/en/1303/
=> Implement gradient for QR decomposition

pytensor/link/numba/dispatch/basic.py, pytensor/link/numba/dispatch/linalg/_LAPACK.py, pytensor/link/numba/dispatch/linalg/decomposition/cholesky.py, pytensor/link/numba/dispatch/linalg/solve/cholesky.py, pytensor/link/numba/dispatch/linalg/solve/general.py, pytensor/link/numba/dispatch/linalg/solve/norm.py, pytensor/link/numba/dispatch/linalg/solve/posdef.py, pytensor/link/numba/dispatch/linalg/solve/symmetric.py, pytensor/link/numba/dispatch/linalg/solve/triangular.py, pytensor/link/numba/dispatch/linalg/solve/tridiagonal.py, pytensor/link/numba/dispatch/linalg/solve/utils.py, pytensor/link/numba/dispatch/linalg/utils.py, pytensor/link/numba/dispatch/slinalg.py, pytensor/tensor/slinalg.py, tests/link/numba/test_slinalg.py
Also refactors the lapack codegen
----
📚 Documentation preview 📚: https://pytensor--1311.org.readthedocs.build/en/1311/
=> Implement tridiagonal solve in numba backend

pytensor/link/jax/dispatch/__init__.py, pytensor/link/jax/dispatch/signal/__init__.py, pytensor/link/jax/dispatch/signal/conv.py, pytensor/link/numba/dispatch/__init__.py, pytensor/link/numba/dispatch/signal/__init__.py, pytensor/link/numba/dispatch/signal/conv.py, pytensor/tensor/__init__.py, pytensor/tensor/signal/__init__.py, pytensor/tensor/signal/conv.py, tests/link/jax/signal/test_conv.py, tests/link/numba/signal/test_conv.py, tests/tensor/signal/test_conv.py
Spinoff from #548. It was obvious the old fast Ops were not really fast, just not as slow as the `AbstractConv` Ops. I suggest we start removing those, by more sane implementations.
This PR implements a simple convolve1d (that can be batched by blockwise). This is actually not offered by either scipy.signal nor numpy.convolve. The scipy impl has no concept of batch dims, so if you pass two 2d inputs you get a convolve2d. The numpy one doesn't support batch dims, period.
Because the 1d case implemented here matches with the one you would get from calling `scipy.convolve` I added a small wrapper that allows you to go that route. Consider it WIP.
Also note that `same` behaves differently between numpy and scipy. In numpy it returns something with the shape of the largest of the two inputs, …
=> Implement batched convolve1d

pytensor/link/jax/dispatch/random.py, tests/link/jax/test_random.py
Closes #1327 
----
📚 Documentation preview 📚: https://pytensor--1328.org.readthedocs.build/en/1328/
=> Fix nan for valid parameters in jax implementation of Multinomial

pytensor/compile/mode.py, pytensor/tensor/rewriting/subtensor.py, pytensor/tensor/subtensor.py
This optimization is actually a slow down, because the implementations always requset a cast of indices to intp. We used to do it explicitly in `AdvancedSubtensor1` but the underlying numpy C function also does it: https://github.com/numpy/numpy/blob/c23886c226012a50da11066d3be98fd94e571101/numpy/_core/src/multiarray/item_selection.c#L247-L251
Local benchmark on a PyMC model that uses AdavncedSubtensor1/Inc shows a slowdown compared to when the optimization is not used.
This PR removes the rewrite from these backends. It also makes the rewrite apply only after `specialization` to avoid too many passes when other rewrites introduce things like `x.shape[i]` which will be removed anyway.
----
📚 Documentation preview 📚: https://pytensor--1335.org.readthedocs.build/en/1335/
=> Don't run local uint constant indices in C/Python backends

pytensor/link/jax/dispatch/random.py
#1328 was not good enough for the test in PyMC :(
I changed it to stop taking draws once `remaining_n` drops to zero. This should be more robust against numerical precision issues for valid parameters. It's also what our numba implementation is doing, so at least they are aligned:
https://github.com/pymc-devs/pytensor/blob/75789deba3f1e4514ad56c9922083a93542313f2/pytensor/link/numba/dispatch/random.py#L166-L167
Or I should perhaps just gone with the suggestion @educhesne gave.
I confirm PyMC is now happy
----
📚 Documentation preview 📚: https://pytensor--1339.org.readthedocs.build/en/1339/
=> More stable fix for JAX Multinomial

pytensor/link/numba/dispatch/basic.py, tests/link/numba/test_basic.py
This PR introduces Numba compiled function `sort`  and  `argsort` for certain kind of sorting algorithms that are supported by Numba (See [this](https://numba.readthedocs.io/en/stable/reference/numpysupported.html)).
----
📚 Documentation preview 📚: https://pytensor--1309.org.readthedocs.build/en/1309/
=> Support numba compiled `sort` and `argsort` functions

pytensor/link/numba/dispatch/tensor_basic.py, pytensor/tensor/basic.py, tests/link/jax/test_tensor_basic.py, tests/tensor/test_basic.py
This makes Split (which shows up in the gradient of Join) much faster as it doesn't do useless copies.
I see a speedup of ~10x, obviously the comparison would scale with the ammount of copying that is now avoided
```python
x = pt.matrix("x", shape=(100, 200))
ys = pt.split(x, [10]*10, 10)
profile = None
fn = pytensor.function(
[pytensor.In(x, borrow=True)], 
[pytensor.Out(y, borrow=True) for y in ys],
trust_input=True,
profile=profile,
)
fn.dprint()
x_test = np.zeros((100, 200))
%timeit fn(x_test)
%timeit fn(x_test)
%timeit fn(x_test)
if profile:
fn.profile.summary()
```
Also added static output shape and cleanup other methods of Split
----
📚 Documentation preview 📚: https://pytensor--1343.org.readthedocs.build/en/1343/
=> Propagate static output shapes in Split and avoid copy in C-impl

pytensor/link/numba/dispatch/vectorize_codegen.py, pytensor/scalar/basic.py, pytensor/scalar/loop.py, pytensor/tensor/rewriting/elemwise.py, tests/link/numba/test_elemwise.py, tests/scalar/test_loop.py, tests/tensor/rewriting/test_elemwise.py, tests/tensor/test_math_scipy.py
Closes #138 
This allows inplacing arbitrary number of inputs in Elemwise Composite (i.e., fused) Ops. The restriction was there because in the original codegen writing to the aliased outputs could affect the computations of other outputs that still referenced the just overridden aliased inputs.  
The fix was trivial, only use the output names in the end after all nodes are computed. Until then the variables are stored in temporary variables as already happens for regular intermediate nodes in the Composite.
Did the same for `ScalarLoop`. The final outputs are only defined once the inner loop is finished, so no worries about aliasing too soon.
Also a typo-bug in the Numba vectorize code that's fixed. 
----
📚 Documentation preview 📚: https://pytensor--1322.org.readthedocs.build/en/1322/
=> Inplace Composite and ScalarLoop Ops with multiple outputs

pytensor/tensor/type.py, tests/tensor/test_type.py
The following is now allowed
```python
pt.dmatrix(shape=(3, 4))
```
Whereas before only the generic `matrix` function allowed it. The reason we didn't make `dmatrix` and alike just helper functions like `matrix` was that they are used to parametrize `itypes/otypes` of Ops without `make_node`, and they need to be PyTensor types for that.
----
📚 Documentation preview 📚: https://pytensor--1355.org.readthedocs.build/en/1355/
=> Allow specializing shape of predefined tensor types

.github/workflows/pypi.yml, pyproject.toml
```
* Building wheel... /tmp/build-env-vi5sasbz/lib/python3.12/site-packages/setuptools/config/_apply_pyprojecttoml.py:82: SetuptoolsDeprecationWarning: `project.license` as a TOML table is deprecated !!
********************************************************************************
Please use a simple string containing a SPDX expression for `project.license`. You can also use `project.license-files`. (Both options available on setuptools>=77.0.0).
By 2026-Feb-18, you need to update your project and remove deprecated calls
or your builds will no longer be supported.
See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details.
********************************************************************************
!!
corresp(dist, value, root_dir) …
```
=> Update pyproject license schema according to deprecation warnings

pytensor/tensor/blas.py
This is just a minor typo fix in the batched_tensordot deprecation warning message
----
📚 Documentation preview 📚: https://pytensor--1364.org.readthedocs.build/en/1364/
=> Fix typo in warning message

pytensor/link/jax/dispatch/slinalg.py, pytensor/link/numba/dispatch/basic.py, pytensor/link/numba/dispatch/linalg/decomposition/lu.py, pytensor/link/numba/dispatch/linalg/decomposition/lu_factor.py, pytensor/link/numba/dispatch/linalg/solve/general.py, pytensor/link/numba/dispatch/linalg/solve/lu_solve.py, pytensor/link/numba/dispatch/slinalg.py, pytensor/tensor/blockwise.py, pytensor/tensor/elemwise.py, pytensor/tensor/slinalg.py, tests/link/jax/test_slinalg.py, tests/link/numba/test_slinalg.py, tests/tensor/test_blockwise.py, tests/tensor/test_elemwise.py, tests/tensor/test_slinalg.py
This PR will add the following Ops:
As well as dispatches for numba/jax (and maybe torch, though help is welcome there).
The reason for wanting these is that it will make the gradients of solve faster. I think this is a major reason why jax has faster gradients than us (at least when solve is implicated). They route everything to `lu_solve(lu_factor(A), b)`, and reuse `lu_factor(A)` in the backward pass. 
----
📚 Documentation preview 📚: https://pytensor--1218.org.readthedocs.build/en/1218/
=> Add Ops for LU Factorization

pytensor/link/c/cmodule.py, pytensor/utils.py, tests/compile/function/test_function.py, tests/link/c/test_cmodule.py, tests/link/c/test_op.py
I'm having hard times creating new environments with working compiler dependencies.
My debugging attempts show that `shell=False` could fix this, however this observation contradicts the comments next to that line.
~Further testing may be required.~ Tested on another machine.
I also removed an old workaround for Python 2..
Hints?
----
📚 Documentation preview 📚: https://pytensor--1324.org.readthedocs.build/en/1324/
=> Use `shell=False` for `Popen` on Windows

pytensor/link/jax/dispatch/signal/conv.py, pytensor/link/numba/dispatch/signal/conv.py, pytensor/tensor/rewriting/__init__.py, pytensor/tensor/rewriting/conv.py, pytensor/tensor/signal/conv.py, tests/link/numba/signal/test_conv.py, tests/tensor/signal/test_conv.py
Reimplementing the core logic in the numba overload of `convolve/correlate` gives a speedup of 6x in the benchmarked test with relatively small inputs. I guess the overloads don't optimize/propagate constant checks as well? It's a bit surprising but the results are crystal clear.
Also added a rewrite to optimize the gradient of valid convolutions wrt to the smallest inputs, in which case we don't need a full convolve. This is done at the rewrite level because static shape may not be known at the time of grad.
Finally, renamed `Conv1d` to `Convolve1d` which is more in line with the user-facing function
=> Faster convolve1d in numba backend

pytensor/link/jax/dispatch/subtensor.py, pytensor/link/numba/dispatch/slinalg.py, pytensor/link/numba/dispatch/subtensor.py, pytensor/link/pytorch/dispatch/subtensor.py, pytensor/tensor/basic.py, pytensor/tensor/rewriting/subtensor.py, pytensor/tensor/slinalg.py, pytensor/tensor/subtensor.py, tests/tensor/test_subtensor.py
These are some of the biggest drags in the C-backend. This PR does some tweaks that increase performance substantically.
<details>
<summary>Before</summary>
```
---------------------------------------------------------------------------------------------------- benchmark: 4 tests ---------------------------------------------------------------------------------------------------
Name (time in us)                                            Min                Max              Mean            StdDev            Median               IQR            Outliers  OPS (Kops/s)            Rounds  Iterations
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- …
```
=> Speedup AdvancedSubtensor1 and AdvancedIncSubtensor1 in C backend

pytensor/link/c/c_code/lazylinker_c.c, pytensor/link/c/lazylinker_c.py
This is part of the Python ABI since 3.9. It saves a tiny ~20ns per thunk call, but costs us nothing :).
----
📚 Documentation preview 📚: https://pytensor--1383.org.readthedocs.build/en/1383/
=> Use `PyObject_CallNoArgs` to call thunks from VM

pytensor/tensor/blas_c.py, tests/tensor/test_blas_c.py
Related #1388 
Benchmark results for the new test
```
------------------------------------------------------------------------------------------------------------------- benchmark: 8 tests ------------------------------------------------------------------------------------------------------------------
Name (time in us)                                                            Min                   Max                  Mean              StdDev                Median                 IQR            Outliers          OPS            Rounds  Iterations
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ …
```
=> Avoid copy of flipped A matrices in GEMV

pytensor/tensor/slinalg.py, tests/tensor/test_slinalg.py
Closes #1376 
----
📚 Documentation preview 📚: https://pytensor--1394.org.readthedocs.build/en/1394/
=> Fix lu_solve with batch inputs

pyproject.toml, pytensor/compile/builders.py, pytensor/compile/function/types.py, pytensor/graph/op.py, pytensor/ifelse.py, pytensor/link/basic.py, pytensor/link/c/basic.py, pytensor/link/c/op.py, pytensor/link/numba/dispatch/basic.py, pytensor/link/numba/dispatch/cython_support.py, pytensor/link/numba/dispatch/extra_ops.py, pytensor/link/numba/dispatch/slinalg.py, pytensor/link/numba/dispatch/subtensor.py, pytensor/link/utils.py, pytensor/scalar/basic.py, pytensor/scalar/loop.py, pytensor/tensor/basic.py, pytensor/tensor/blockwise.py, pytensor/tensor/elemwise.py, pytensor/tensor/random/basic.py, pytensor/tensor/random/utils.py, pytensor/tensor/shape.py, pytensor/tensor/type.py, pytensor/tensor/utils.py, tests/tensor/random/test_basic.py, tests/tensor/test_blockwise.py
`numpy.vectorize` has a lot of overhead which is problematic for Blockwise because we don't have a C implementation.
This PR strips down to the bare minimum we need to try to reduce Python overhead as much as possible.
----
📚 Documentation preview 📚: https://pytensor--1391.org.readthedocs.build/en/1391/
=> Speedup Python implementation of Blockwise

pytensor/link/numba/dispatch/random.py, tests/link/numba/test_random.py
Closes https://github.com/pymc-devs/pymc/issues/7778
----
📚 Documentation preview 📚: https://pytensor--1402.org.readthedocs.build/en/1402/
=> Implement numba dispatch of StudentT

pytensor/tensor/blas.py
The gcc 15 runtime was complaining about missing `clock_gettime64` in https://github.com/pymc-devs/pytensor/issues/1401. I strongly suspect that removing the dead code related to profiling will solve the issue.
NOTE: This is untested
----
📚 Documentation preview 📚: https://pytensor--1403.org.readthedocs.build/en/1403/
=> Remove dead C code importing time.h

pytensor/tensor/basic.py
Closes #1360.
It also allows ExtractDiagonal to be a view (it's on by default). Under the hood numpy has returned non-writeable views since 1.9.0, and we have a lower pin of 1.17.0. It's as simple as swapping the flag [citation needed].
----
📚 Documentation preview 📚: https://pytensor--1392.org.readthedocs.build/en/1392/
=> Implement C code for ExtractDiagonal and ARange

pytensor/link/c/cmodule.py, pytensor/tensor/blas.py, pytensor/tensor/special.py
The `iostream` include seems to be unused, and it's actually leading to #1398, so an alternative resolution is to remove the include.
We'll see if the test suite still passes...
----
📚 Documentation preview 📚: https://pytensor--1400.org.readthedocs.build/en/1400/
=> Remove iostream include for C backend

pytensor/compile/mode.py, pytensor/scan/rewriting.py, pytensor/tensor/__init__.py, pytensor/tensor/_linalg/__init__.py, pytensor/tensor/_linalg/solve/__init__.py, pytensor/tensor/_linalg/solve/rewriting.py, pytensor/tensor/rewriting/linalg.py, tests/tensor/linalg/test_rewriting.py, tests/tensor/test_blockwise.py
Requires #1394 
This PR adds the rewrites to reuse an LU decomposition of the same A matrix across multiple solves:
1. Distinct Solve operations such as in a graph containing both the forward and backward pass of Solve)
2. Blockwise Solve where A is broadcasted by b
3. Scan Solve where A is a composed only of non-sequences inputs, but not b
It does not propagate the `check_finite` flag which I think we should rework out of Solve
Closes #1374 
----
📚 Documentation preview 📚: https://pytensor--1396.org.readthedocs.build/en/1396/
=> Reuse LU decomposition in Solve

pytensor/tensor/blas_c.py, tests/tensor/test_blas.py, tests/tensor/test_blas_c.py
Fix bug in handling of row/column matrices in GEMV c_code
Bug was caused by reusing the blas-friendly readjusted strides in the logic to decide whether the call to GEMV should be transposed or not.
Particularly the old +1 in the strides was causing the last error branch to be triggered when the matrix had shape (1, 1).  The +1 was supposedly there for the cases of matrix with length 0, but that has it's own branch where the adjusted strides are never used. [That branch is actually useless, and was also removed in this PR]
This bug was introduced in afe934b229f15be4dcd96bbd3960e7ed328d99fa, before it we were using the unadjusted strides, but that is also suboptimal since strides for length1 dimensions are meaningless and any value is valid by the numpy standard.
The bug showed up in …
=> Fix bug in gemv c code

pytensor/tensor/rewriting/subtensor.py, tests/tensor/rewriting/test_subtensor.py
This showed up when trying to vectorize statespace models
----
📚 Documentation preview 📚: https://pytensor--1405.org.readthedocs.build/en/1405/
=> Fix bug in local_blockwise_advanced_inc_subtensor

pytensor/link/numba/dispatch/basic.py, pytensor/link/numba/dispatch/elemwise.py, pytensor/link/numba/dispatch/linalg/decomposition/lu.py, pytensor/link/numba/dispatch/nlinalg.py, pytensor/link/numba/dispatch/scalar.py, tests/link/numba/test_basic.py, tests/link/numba/test_nlinalg.py, tests/link/numba/test_scalar.py
This lead to failures in statespace models, as the Elemwise raises if the inputs are not arrays.
Closes https://github.com/pymc-devs/pymc-extras/issues/476
----
📚 Documentation preview 📚: https://pytensor--1406.org.readthedocs.build/en/1406/
=> Fix numba dispatch not returning arrays or wrong dtypes

pytensor/tensor/blockwise.py, pytensor/tensor/signal/conv.py
The numpy C-API function isn't great because it requires flipping the second input and doesn't allow reusing the output buffer, but it's easy enough to implement like this
----
📚 Documentation preview 📚: https://pytensor--1404.org.readthedocs.build/en/1404/
=> C impl of convolve1d

pytensor/tensor/_linalg/solve/rewriting.py, pytensor/tensor/type.py, tests/tensor/linalg/test_rewriting.py
There is a test failing in PyMC that uses `check_finite=False` explicitly to test other stuff behaves correctly with NANs...
It's still a shame that scipy/we default to `check_finite=False`, wonder if there is a way to test once at runtime whether the involved lapack functions do crash/not-terminate with nan/infs...
----
📚 Documentation preview 📚: https://pytensor--1417.org.readthedocs.build/en/1417/
=> Respect check_finite in LU decomposition rewrites

pytensor/xtensor/rewriting/shape.py, pytensor/xtensor/shape.py, pytensor/xtensor/type.py, tests/xtensor/test_shape.py
@AllenDowney I cherry-picked your changes from #1427, I squashed all the transpose related changes into a single one, and split unrelated changes into other 2 commits.
I pushed a fourth commit with changes that I'm listing here, and I would appreciate if you could in turn review them:
1. Moved the `missing_dims` out of the `Op` since this is not really a parameter that affects how the `Op` behaves at runtime, and is therefore useless. I put the behavior in the helper that calls the `Transpose` `Op` instead. The `Op` will expect dims to be correctly specified and raise if not.
2. Merged the helper `expand_ellipsis` into the `make_node` since that's the only place it's used and it's not insanely complex.
3. Put the 2 new transpose tests closer to the original one, and simplified the last …
=> Implement Transpose for XTensorVariables

pytensor/xtensor/rewriting/shape.py, pytensor/xtensor/shape.py, pytensor/xtensor/type.py, tests/xtensor/test_shape.py
@OriolAbril I am opening a branch with your code here on PyTensor. It can be from your fork if you prefer, but that would have to be you doing it.
Copying your messages:
> First pass at unstack. It is working already, need to sort out tests and double check the order in which unstack happens.
> @ricardoV94 let me know if the PR should have been done in a different way and how the code looks. As I commented in the test code itself, tests currently pass but I am only checking matching shapes with xarray, the actual elements are different. I have to figure out if the idea I had of testing the complementary operation to circumvent the fact that xarray's unstack needs coordinates can't actually be used or if I am inverting some `stack(new_dim=["a", "b"]` while the other has `["b", "a"]`.
---- …
=> Add unstack for xtensors

pytensor/scan/rewriting.py, pytensor/tensor/rewriting/basic.py, tests/scan/test_rewriting.py
The check we had for whether a variable was a default scan buffer (that's not also broadcasting the initval), always failed for single tapped outputs. There's a conservative check that the original value is not being broadcast to the number of initial taps, but that doesn't matter for single taps.
Also added some checks that we are actually only keeping buffers of the expected size in the test.
----
📚 Documentation preview 📚: https://pytensor--1395.org.readthedocs.build/en/1395/
=> Avoid default allocation for taps of length 1 in ScanSaveMem

pytensor/link/jax/linker.py, tests/link/jax/test_random.py
This should make it possible to do forward sampling in more PyMC models that use dims to define variables shapes
```python
def test_random_scalar_shape_input():
dim0 = pt.scalar("dim0", dtype=int)
dim1 = pt.scalar("dim1", dtype=int)
out = pt.random.normal(0, 1, size=dim0)
jax_fn = compile_random_function([dim0], out)
assert jax_fn(np.array(2)).shape == (2,)
assert jax_fn(np.array(3)).shape == (3,)
out = pt.random.normal(0, 1, size=[dim0, dim1])
jax_fn = compile_random_function([dim0, dim1], out)
assert jax_fn(np.array(2), np.array(3)).shape == (2, 3)
assert jax_fn(np.array(4), np.array(5)).shape == (4, 5)
```
These was already a special rewrite to replace make_vector, expand_dims in the shape of RVs, but without handling these inputs from the outside it wouldn't achieve much for PyTensor …
=> Support RandomVariable graphs with scalar shape parameters in JAX backend

pytensor/scan/op.py, tests/scan/test_basic.py
This should also fix some regressions in the recent release. Add a `None` check for `compute_map` in `make_thunk`
Closes #1425
=> Handle `compute_map=None` in Scan

pytensor/tensor/subtensor.py, pytensor/xtensor/indexing.py, pytensor/xtensor/rewriting/indexing.py, pytensor/xtensor/type.py, tests/xtensor/test_indexing.py
This builds on top of #1429 to support index assignment and increment `x[idx] = y` and `x[idx] += y`, following xarray indexing and broadcasting semantics.
As with regular TensorVariables, due to immutability/hashability constraints of PyTensor, it is not possible to use the python native operations, so one has to write `z = x[idx].set(y)` and `z = x[idx].inc(y)`
----
📚 Documentation preview 📚: https://pytensor--1438.org.readthedocs.build/en/1438/
=> XTensorVariable indexing update

pytensor/gradient.py, pytensor/scalar/basic.py, pytensor/sparse/rewriting.py
There were some bugs that survived along time, until numpy 2.3.0 where it finally fails.
first showed up in #1182 
----
📚 Documentation preview 📚: https://pytensor--1456.org.readthedocs.build/en/1456/
=> Fix invalid numpy dtype

pytensor/compile/mode.py, pytensor/link/numba/dispatch/linalg/solve/tridiagonal.py, pytensor/tensor/_linalg/solve/rewriting.py, pytensor/tensor/_linalg/solve/tridiagonal.py, pytensor/tensor/rewriting/subtensor.py, pytensor/tensor/subtensor.py, tests/link/numba/linalg/solve/test_tridiagonal.py, tests/tensor/linalg/test_rewriting.py, tests/tensor/rewriting/test_subtensor.py
This PR builds on top of #1396, extending it to the tridiagonal case. 
It also adds a rewrite for when extracting diagonals out a symbolically allocated diagonal matrix (via set_subtensor or AllocDiag after it gets inlined during specialization)
=> Decompose Tridiagonal Solve into core steps

pytensor/tensor/optimize.py, tests/tensor/test_optimize.py
Implement scipy optimization routines, with implicit gradients. This PR should add:
It would also be nice to have rewrites to transform e.g. `root` to `scalar_root` when we know that there is only one input.
The implementation @ricardoV94 and I cooked up (ok ok it was mostly him) uses the graph to implicitly define the inputs to the objective function. For example:
```py
from pytensor.tensor.optimize import minimize
x = pt.scalar("x")
a = pt.scalar("a")
c = pt.scalar("c")
b = a * 2
b.name = "b"
out = (x - b * c) ** 2
minimized_x, success = minimize(out, x, debug=False)
```
We optimize `out` with respect to `x`, so `x` becomes the control variable. By graph inspection we find that `out` also depends on `a` and `c`, so the generated graph includes them as …
=> Implement symbolic `minimize` and `root` `Ops` 

.github/workflows/test.yml, pyproject.toml, pytensor/graph/features.py, pytensor/ipython.py, tests/graph/test_features.py
I can imagine this being very powerful for debugging or reasoning about rewrites?
https://github.com/user-attachments/assets/9246abf1-015a-49d4-a05c-1197d082a3ee
```python
from pytensor.graph.fg import FunctionGraph
from pytensor.graph.features import FullHistory
from pytensor.graph.rewriting.utils import rewrite_graph
x = pt.scalar("x")
out = pt.log(pt.exp(x) / pt.sum(pt.exp(x)))
fg = FunctionGraph(outputs=[out])
history = FullHistory()
fg.attach_feature(history)
rewrite_graph(fg, clone=False, include=("canonicalize", "stabilize"))
history.start()
pytensor.dprint(fg)
pytensor.config.optimizer_verbose = True
for i in range(3):    
print()
print(">>> ", end="")
pytensor.dprint(history.next())
for i in range(3):
print()
print(">>> ", end="") …
```
=> Add Feature that can go back and forward in rewrite history

pytensor/link/numba/dispatch/tensor_basic.py
Spinoff from #811
----
📚 Documentation preview 📚: https://pytensor--1329.org.readthedocs.build/en/1329/
=> Simplify Numba implementation of Alloc

pytensor/ipython.py
Allow controlling the rewrite database and the dprint settings. Also allow attaching an existing FG which already has the history feature.
Marking as no releasenotes, because we didn't yet release PyTensor with the widget
----
📚 Documentation preview 📚: https://pytensor--1469.org.readthedocs.build/en/1469/
=> QoL improvements to InteractiveRewrite widget

pytensor/tensor/_linalg/solve/rewriting.py, tests/tensor/linalg/test_rewriting.py, tests/tensor/test_blockwise.py
We now have some rewrite machinery that reuses LU decomposition in graphs that repeatedly solve against the same `A` matrix with different `b`. This comes up in the gradients of `pt.solve` (or any graph with `pt.solve(A, b)`, `pt.solve(A, c)`), as well as `scan` and `Blockwise` graphs.
The same trick -- rewriting `pt.solve(A, b)` to `pt.lu_solve(pt.lu_factor(A), b)` -- can be done with `cholesky` and `cho_solve`. This PR extends the rewrites to cover this case. It also renames the rewrites to have more neutral names, since we no longer always LU decompose.
----
📚 Documentation preview 📚: https://pytensor--1467.org.readthedocs.build/en/1467/
=> Reuse `cholesky` decomposition with `cho_solve` in graphs with multiple `pt.solve` when `assume_a = "pos"`

pytensor/xtensor/rewriting/shape.py, pytensor/xtensor/shape.py, pytensor/xtensor/type.py, tests/xtensor/test_shape.py
This PR adds support for the `expand_dims` operation in PyTensor's labeled tensor system, allowing users to add new dimensions to labeled tensors with explicit dimension names.
- New `ExpandDims` operation that adds a new dimension to an XTensorVariable
- Support for both static and symbolic dimension sizes
- Automatic broadcasting when size > 1
- Integration with existing tensor operations
- Full compatibility with xarray's expand_dims behavior
The implementation includes:
1. New `ExpandDims` class in `pytensor/xtensor/shape.py` that handles:
- Adding new dimensions with specified names
- Support for both static and symbolic sizes
- Shape inference and validation
2. Rewriting rule in `pytensor/xtensor/rewriting/shape.py` that:
- Converts labeled tensor operations to standard tensor …
=> Adding expand_dims for xtensor

pytensor/xtensor/shape.py, pytensor/xtensor/type.py, tests/xtensor/test_shape.py
The first pass did not handle the `drop` and `axis` parameters.
Also cleaning up the tests.
----
📚 Documentation preview 📚: https://pytensor--1473.org.readthedocs.build/en/1473/
=> Add missing features to xtensor.squeeze()

doc/library/tensor/basic.rst, pytensor/tensor/subtensor.py
Some basic correction from this documentation page: 
https://pytensor.readthedocs.io/en/latest/library/tensor/basic.html#indexing
----
📚 Documentation preview 📚: https://pytensor--1463.org.readthedocs.build/en/1463/
=> Correct indexing links in docs

pytensor/tensor/blockwise.py, tests/tensor/test_blockwise.py
This PR fixes a bug found in the work to add batch dimensions to the Statespace module in pymc-extras. The gradient of a Blockwise'd scan with a specific broadcastable signature in the inner graph (i.e., shape=(1,)), was failing, because Blockwise was creating a dummy node with variables that didn't respect the core shapes (i.e., shape=(None,)).
The fix is a one liner (second commit).
The last commit refactors the L_op implementation since the helper function isn't used anywhere else, and some parts that were copied from Elemwise don't make sense (such as worrying that core.op L_op might return `None`).
----
📚 Documentation preview 📚: https://pytensor--1482.org.readthedocs.build/en/1482/
=> Fix bug in gradient of Blockwise'd Scan

pytensor/link/jax/linker.py
Minor code cleanup, generators don't have dtype
----
📚 Documentation preview 📚: https://pytensor--1470.org.readthedocs.build/en/1470/
=> Simplify typify of Generators in JAXLinker

pytensor/tensor/slinalg.py, tests/link/numba/test_slinalg.py, tests/tensor/test_slinalg.py
* Now skips 2D checks in perform
* Updated the default arguments for `check_finite` to false to match documentation
* Add benchmark test case
Adds `_cholesky` method to `slinalg.Cholesky` to replace the `scipy.linalg.cholesky` wrapper. It is almost identical to [the corresponding scipy function](https://github.com/scipy/scipy/blob/63025cd1028cdb46de42400df21c60aa13f68743/scipy/linalg/_decomp_cholesky.py#L15) but it skips the 2d check and the batching wrapper.
Previous performance (with `check_finite=False`):
```
benchmark: 5.1.0 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
--------------------------------------------------- benchmark: 1 tests …
```
=> Use lapack func instead of `scipy.linalg.cholesky`

doc/tutorial/gradients.rst, pytensor/gradient.py, pytensor/graph/replace.py, pytensor/tensor/basic.py, tests/tensor/test_basic.py, tests/test_gradient.py
Seeing about a 3.5x, (2x for larger x) time speedup for this trivial case:
```python
from pytensor.gradient import jacobian
from pytensor import function
x = pt.vector("x", shape=(3,))
y = pt.outer(x, x)
print(y.type.shape)
jac_y = jacobian(y, x, vectorize=False)
print(jac_y.type.shape)
fn = function([x], jac_y, profile=True)
fn.dprint(print_type=True)
%timeit fn([0, 1, 2])
fn([0, 1, 2])
```
Memory footprint will grow though, specially if intermediate operations are much larger than the final jacobian. Also not all graphs will be safely vectorizable, so I would leave the Scan option as a default for a while.
=> Implement vectorized jacobian and allow arbitrary expression shapes

pytensor/tensor/rewriting/linalg.py, pytensor/tensor/rewriting/math.py, tests/tensor/rewriting/test_linalg.py, tests/tensor/rewriting/test_math.py
Small optimization that rewrites `solve(a,b) -> b / a` when the core shape of `a` is `(1, 1)`. This avoids calling a LAPACK routine in a case where it's simply not necessary.
This came up in the gradient of `minimize`, for cases where the function being minimized has only one input. The L_op in that case requires a bunch of linear algebra, but it can all be rewritten away when we're just dealing with scalars.
I also tweaked `rewrite_cholesky_diag_to_sqrt_diag` to apply to the (1, 1) case -- this allows `cho_solve` to be rewritten to just b / a ** 2, without any linalg calls. ~~The only bummer is that the `sqr` and `sqrt` don't cancel. I get this graph:~~ 
Here is the graph, including the new sqr/sqrt cancellation:
```
x = pt.tensor('x', …
```
=> Rewrite scalar solve to division

pytensor/graph/destroyhandler.py, pytensor/tensor/rewriting/blockwise.py, pytensor/tensor/rewriting/elemwise.py, tests/tensor/rewriting/test_elemwise.py, tests/tensor/test_blockwise.py
Closes #1420 
There was a performance-related hack in the ElemwiseInplaceOptimizer where it tried to avoid validating the graph after replacing each node.
This is a bad idea because it may revert valid rewrites that happen to be caught in the same "check" window as an invalid rewrite. More importantly since we started inplacing on multi-output Elemwise, it could trigger an exception when trying to call `has_destroyers` on subsequent nodes, due to a previous invalid replacement.
It was hard to track down this issue because the special behavior was only triggered once a graph had more than 500 nodes.
After the refactor I noticed that most of the logic of the rewrite can be shared with Blockwise, so I went ahead and refactored it, which also closes #1457
----
📚 Documentation preview 📚: …
=> Do not skip validation between consecutive Elemwise inplace replacements

pytensor/xtensor/__init__.py, pytensor/xtensor/shape.py, tests/xtensor/test_shape.py, tests/xtensor/util.py
#1514 had the wrong base branch
----
📚 Documentation preview 📚: https://pytensor--1519.org.readthedocs.build/en/1519/
=> Implement `full_like`, `ones_like`, and `zeros_like` for XTensorVariables

.github/workflows/pypi.yml
This was mostly Claude-generated changes, so appreciate careful review.
Trying to save tons of compute time we wast building the cython-scan extension on the ubuntu wheel for every PR and push to main. Closes #219 
----
📚 Documentation preview 📚: https://pytensor--1363.org.readthedocs.build/en/1363/
=> Don't run the PyPi job all the time

pytensor/scalar/math.py, tests/scalar/test_math.py
Modified the C implementation of psi to handle negative inputs too using the reflection formula for the digamma function. Added tests to verify the functionality.
----
📚 Documentation preview 📚: https://pytensor--1523.org.readthedocs.build/en/1523/
=> Extend C implementation of psi to support negative inputs

pytensor/tensor/basic.py, tests/tensor/test_basic.py
Converts negative constant axis to positive if present in `Join(COp)`
DISCLAIMER: Completely vibe coded in Claude Sonnet 3.7. May well be complete non-sense, and if so please close immediately.
=> Converts negative constant axis to positive if present in `Join(COp)`

pytensor/link/jax/dispatch/basic.py, pytensor/link/pytorch/dispatch/basic.py, pytensor/raise_op.py, pytensor/tensor/rewriting/basic.py, tests/tensor/rewriting/test_basic.py, tests/tensor/rewriting/test_elemwise.py, tests/tensor/test_extra_ops.py, tests/tensor/test_math.py, tests/test_raise_op.py
This showed up mysteriously in #1471 
I wanted to make constant_fold use python mode (no reason to compile C stuff for a single eval), and some tests started failing. After digging, found out the C-implementation was broken when the conditions were tensors.
I simplified the Op but converting all inputs to boolean scalars. I also decided not to constant_fold Asserts that would fail (remember that before this PR they would wrongly constant_fold without raising), so users can still decide what to do with them after graph rewrite. 
I changed the JAX dispatch to raise the error if the Assert would be known to have failed (now that it is not constant-folded)
This PR also changes the constant_fold to use Python (the reason I found the bug in the first place)
----
📚 Documentation preview 📚: …
=> Fix `CheckAndRaise` Op C implementation

pyproject.toml, pytensor/printing.py
Get rid of pydot-ng because it's deprecated since 7 years
----
📚 Documentation preview 📚: https://pytensor--1534.org.readthedocs.build/en/1534/
=> Get rid of pydot-ng because it's deprecated since 7 years

tests/link/numba/test_elemwise.py
Minor cleanup of `test_Elemwise`. Carryover from #1535.
1) Removes a constant `exec` param since it never changes
2) Introduce ids to improve test readability
3) Removes a dangling context manager
----
📚 Documentation preview 📚: https://pytensor--1536.org.readthedocs.build/en/1536/
=> Clean `test_Elemwise`

pytensor/xtensor/reduction.py, pytensor/xtensor/type.py, tests/xtensor/test_reduction.py
Also add docstrings to most methods and properties so they show up in the docs.
Removes broadcast as a method, since it is not one in xarray
----
📚 Documentation preview 📚: https://pytensor--1533.org.readthedocs.build/en/1533/
=> Fix mean, var and std for XTensorVariables

pytensor/link/jax/dispatch/nlinalg.py, pytensor/link/jax/dispatch/slinalg.py, pytensor/link/numba/dispatch/linalg/_LAPACK.py, pytensor/link/numba/dispatch/linalg/decomposition/qr.py, pytensor/link/numba/dispatch/nlinalg.py, pytensor/link/numba/dispatch/slinalg.py, pytensor/link/pytorch/dispatch/__init__.py, pytensor/link/pytorch/dispatch/nlinalg.py, pytensor/link/pytorch/dispatch/slinalg.py, pytensor/tensor/nlinalg.py, pytensor/tensor/slinalg.py, tests/link/jax/test_nlinalg.py, tests/link/jax/test_slinalg.py, tests/link/numba/test_nlinalg.py, tests/link/numba/test_slinalg.py, tests/link/pytorch/conftest.py, tests/link/pytorch/test_nlinalg.py, tests/link/pytorch/test_slinalg.py, tests/tensor/test_nlinalg.py, tests/tensor/test_slinalg.py
This PR updates the QRFull Op, adding static shape checking, infer_shape, and destroy_map. It also optimizes the perform method for the C backend, and tries to improve the gradient graph by checking static shapes (to avoid an ifelse).
I renamed it to QR, because I don't know what was Full about the old one. I also moved it from the numpy implementation to scipy, which gives us all the usual benefits (inplace, etc). I also went ahead and unpacked the scipy wrapper and used the LAPACK functions directly. This will give us better error handling (that is to say, none -- it should eventually return a matrix of NaN on failure) and some performance boost by caching workspace requirements.
Still a WIP, because it breaks everything by moving QR from nlinalg to slinalg. I thought about using this …
=> Refactor and update QR Op

pytensor/tensor/rewriting/subtensor.py, tests/tensor/rewriting/test_subtensor.py, tests/tensor/rewriting/test_subtensor_lift.py
----
📚 Documentation preview 📚: https://pytensor--1541.org.readthedocs.build/en/1541/
=> Canonicalize subtensor negative integer indices

pytensor/tensor/subtensor.py, tests/tensor/test_subtensor.py
Can't take the min of an empty index. This Op is useless, but depending on how the graph is build / optimizations done, there are no guarantees it will be removed.
----
📚 Documentation preview 📚: https://pytensor--1551.org.readthedocs.build/en/1551/
=> Fix AdvancedIncSubtensor1 C-compilation with empty indices

pytensor/tensor/extra_ops.py, pytensor/tensor/rewriting/math.py, pytensor/xtensor/rewriting/shape.py, tests/tensor/rewriting/test_math.py, tests/tensor/test_extra_ops.py
This PR adds a rewrite to optimize matrix multiplication involving block diagonal matrices. When we have a a matrix `X = BlockDiag(A, B)`, when you do `Z = X @ Y`, there's no interaction between terms in the `A` part and `B` part of the `X` matrix. So the dot can be instead computed as `row_stack(A @ Y[:X.shape[0]], B @ Y[X.shape[0]:]` (or in the general case, `Y` can be split into `n` pieces with appropriate shapes, and do `row_stack([diag_component @ y_split for diag_component, y_split in zip(BlockDiag.inputs, split(Y, *args)])`. If the case where the blockdiag matrix is right-multiplying, you instead col_stack and slice on axis=1. 
Anyway, it's a lot faster to do this, because matmuls scale really badly in the dimension of the input, so doing two smaller operations is preferred. Here …
=> Optimize matmuls involving block diagonal matrices

pytensor/tensor/subtensor.py, pytensor/tensor/type_other.py, pytensor/tensor/variable.py, tests/tensor/test_subtensor.py
Closes #1532 
Closes #1565 
Logic could be slightly simplified after #1564
----
📚 Documentation preview 📚: https://pytensor--1566.org.readthedocs.build/en/1566/
=> Implement static shape inference for AdvancedSubtensor

pytensor/tensor/elemwise.py, pytensor/tensor/elemwise_cgen.py
Everything is `npy_intp` now which is the type of numpy array shape and strides anyway. 
CI started failing recently in the macos test, because there the old ssize_t was a long, and we were trying to initialize an int array out of it.
----
📚 Documentation preview 📚: https://pytensor--1602.org.readthedocs.build/en/1602/
=> Fix failure with narrowing of ssize_t to int in macos

pytensor/graph/rewriting/db.py, pytensor/scan/rewriting.py
Tweak to avoid Scan rewrites being triggered when there is no single Scan Op in the graph (which happens many many times). 
This avoids multiple iterations over the graph and repeated checks for `isinstance(node.op, Scan)`, in every compilation stage. Note that all Scan rewrites are implemented as standalone in2out to enforce rewrite ordering, which means each one tries to traverse the whole graph at least once every time we compile a function.
The functionality needed (customize the rewriter created by the Equilibrium database), is something I also needed at some point elsewhere
----
📚 Documentation preview 📚: https://pytensor--1600.org.readthedocs.build/en/1600/
=> Skip scan rewrites if there is no Scan Op in the graph

doc/library/config.rst, pytensor/configdefaults.py, pytensor/configparser.py, pytensor/link/numba/dispatch/basic.py
It makes it easier for users to let us know what kind of graph isn't actually compiling this way.
----
📚 Documentation preview 📚: https://pytensor--1520.org.readthedocs.build/en/1520/
=> Add `compiler_verbose` config flag

environment-osx-arm64.yml, environment.yml, pytensor/link/numba/dispatch/linalg/decomposition/lu.py, pytensor/link/numba/dispatch/linalg/decomposition/lu_factor.py, pytensor/link/numba/dispatch/linalg/decomposition/qr.py, pytensor/link/numba/dispatch/linalg/solve/lu_solve.py, pytensor/tensor/conv/abstract_conv.py
I noticed that `scipy` is used quite a bit and that you're using mypy. SciPy doesn't support type-checking on its own, so you'll need [scipy-stubs](https://github.com/scipy/scipy-stubs/) to get the full static typing benefits, such as improved IDE support (e.g. import autocompletion and inline documentation).
I'm it to the conda deps, which I assume is what you use for development.
I'm afraid I wasn't able to locally run the mypy script (using `uv` (because I'm a conda noob) on the main branch it reports that 8 files "unexpectedly failed"). So I can't guarantee that the CI will pass in one go 😅.
----
📚 Documentation preview 📚: https://pytensor--1598.org.readthedocs.build/en/1598/
=> Add `scipy-stubs` as development depedency

pytensor/scalar/basic.py, pytensor/tensor/rewriting/elemwise.py, tests/tensor/rewriting/test_elemwise.py, tests/test_printing.py
FusionOptimizer can be one of the slower rewrites during compilation. This PR speedups it up by a factor of 4-3x in the benchmarked graphs.
Each commit provides a substantial speedup (except maybe for 2-> 3).
The main speedups come from:
1. Reducing number of inner graph clonings when creating CompositeOp
2. Reducing number of toposort computation
3. Using bitsets and bitflags to efficiently compute multiset ancestor dependencies (to ask: do these variables depend on these others?)
The logic for finding valid fused kernels is also more clear now imo, avoiding the need for backtracking. 
<details><summary>Benchmark per commit</summary>
```
HEAD is now at 774792356 Benchmark another FusionOptimizer graph
---------------------------------------------------------------------------------------- …
```
=> Speedup FusionOptimizer

doc/gallery/applications/normalizing_flows_in_pytensor.ipynb
Enjoyed reading this. Some very minor types
----
📚 Documentation preview 📚: https://pytensor--1611.org.readthedocs.build/en/1611/
=> Fix (minor) typos in normalizing_flows_in_pytensor notebook
